### ISSUE TITLE
xMrVizzy/button-toolbar

### ISSUE THREAD

**Issue by samhaa** [hacs/integration#1695] opened 2020-12-04 10:16 UTC
## Describe why you are flagging this

_This template should **only** be used if a repository **needs** to be removed/blacklisted from HACS_

Component removed from GitHub

**Comment by Virtlink** [comment] 2020-12-04 21:58
## button-toolbar repository has been removed

The `xMrVizzy/button-toolbar` returns a 404:

```
ERROR (MainThread) [custom_components.hacs.factory] xMrVizzy/button-toolbar - GitHub returned 404 for https://api.github.com/repos/xMrVizzy/button-toolbar
```

I believe this is also causing none of the other frontend repositories to load, resulting in the _No repositories_ message in a new HACS installation.

**Comment by martinhoess** [comment] 2020-12-05 12:36
there is a fork https://github.com/michalbern/button-toolbar 
maybe there should be some account/repository where stuff like this is archived

**Comment by ludeeus** [comment] 2020-12-05 14:04
duplicate of #1696

**Closed by ludeeus** 2020-12-05 14:04 UTC
Labels: flag
