### ISSUE TITLE
calendar-card wont update - need more details of errors

### ISSUE THREAD

**Issue by ljmerza** [hacs/integration#925] opened 2020-01-14 17:08 UTC
## Version of HACS
0.20.7

https://github.com/ljmerza/calendar-card/issues/76
Users are reporting the calendar card wont update and just gets `Download was not complete`. Looks like there's just a big try catch block on that area of code so there's no way to see what exactly failed. (via comment https://github.com/ljmerza/calendar-card/issues/76#issuecomment-574174386)

The HACS json is:

```
{
    "name": "Calendar Card",
    "render_readme": true,
    "filename": "dist/calendar-card.js"
}
```
The calendar card is relatively big (over half a MB) so that's the only difference I see between this card and all my other cards that update just fine. Considering the HACS setup is the same for all other cards and it's only my calendar-card that doesn't work I'm inclined to think it's a HACS issue but not sure.

If anything, I think more try/catch blocks and more detailed error messages on the referenced area of code in HACS would be helpful. I do not have this issue so am unable to resolve without more debugging details on HACS` end.

**Comment by ludeeus** [comment] 2020-01-14 17:17
partially duplicate of https://github.com/hacs/integration/issues/9228

**Comment by ljmerza** [comment] 2020-01-14 18:32
this goes to 404?

**Comment by ludeeus** [comment] 2020-01-14 18:49
updated

**Comment by ludeeus** [comment] 2020-01-14 19:13
Looks like this is different, I still need to rewrite that entire thing though.

**Comment by ludeeus** [comment] 2020-01-14 19:22
Fixed with https://github.com/hacs/integration/releases/tag/0.20.8

**Closed** 2020-01-14 19:22 UTC
