### ISSUE TITLE
Request for removal of custom-components/sensor.trakt

### ISSUE THREAD

**Issue by rjbarrosog** [hacs/integration#3579] opened 2024-04-07 15:04 UTC
### Repository

custom-components/sensor.trakt

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

The repositiory is not updated for more than 2 years and the author replied that it cannot be mantained anymore. The API beeing used is deprecrated and without update the app does not work

### Link to issue

https://github.com/custom-components/sensor.trakt/issues/72#issuecomment-1967605941

**Comment by ludeeus** [comment] 2024-04-09 15:59
Duplicate of #3561

**Closed by ludeeus** 2024-04-09 15:59 UTC
Labels: flag
