### ISSUE TITLE
Request for removal of Villhellm/lovelace-animated-background

### ISSUE THREAD

**Issue by cjramseyer** [hacs/integration#3130] opened 2023-05-20 21:14 UTC
### Repository

Villhellm/lovelace-animated-background

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Unfortunately, the author of this repository passed away.  This no longer functions in Home Assistant and this should be removed.
Hopefully someone can fork this repo and continue working on this to make it functional again.
The author passed away in 2020

### Link to issue

https://github.com/Villhellm/lovelace-animated-background/issues/57

**Comment by ludeeus** [comment] 2023-05-20 21:29
Duplicate of #3115

**Closed by ludeeus** 2023-05-20 21:29 UTC
Labels: flag
