### ISSUE TITLE
HACS showing updates available, with strange version numbers

### ISSUE THREAD

**Issue by Tyrian81** [hacs/integration#2705] opened 2022-05-27 07:49 UTC
### Web browser

Chrome

### Web browser version

Versie 102.0.5005.63 (Officiële build) (64-bits)

## System Health

version | core-2022.5.5
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.13.0-44-generic
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4695
Installed Version | 1.25.1
Stage | running
Available Repositories | 1063
Downloaded Repositories | 47

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 28
views | 13
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

hacs showing updates, but they are not up-dateable , also have a strange update version number.
Tried removing the custom integrations and reinstall , but did not help 
all the integrations do still seem to work...

### Reproduction steps

1. open HACS 
2. see updates which are invalid

### Screenshots

https://imgur.com/a/ynpke6v

### Javascript logs from your browser console

```text
NEERSLAG-CARD  2022.02.10.0
:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=303101606172:1          Failed to load resource: the server responded with a status of 404 (Not Found)
:8123/hacsfiles/upcoming-media-card/upcoming-media-card.js?hacstag=146783593043:1          Failed to load resource: the server responded with a status of 404 (Not Found)
swipe-navigation.js?hacstag=183995552136:51 ≡ swipe-navigation      ⋮ 
version 1.3.6            
mini-graph-card-bundle.js?hacstag=1512800620110:1  MINI-GRAPH-CARD  0.11.0 
slider-entity-row.js?hacstag=1448997001721:1 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.
(anonymous) @ slider-entity-row.js?hacstag=1448997001721:1
slider-entity-row.js?hacstag=1448997001721:59 SLIDER-ENTITY-ROW 17.2.1 IS INSTALLED 
simple-thermostat.js:204 simple-thermostat: 0.38.0
bar-card.js:4855   BAR-CARD   Version 3.1.7    
entities.js:28   SPOTIFY-CARD   Version 2.4.0    
button-card.js:425   BUTTON-CARD   Version 3.4.2 
utils.ts:1  BATTERY-STATE-CARD  2.1.1
card.js?hacstag=2153271951110:295 
  RGB Light Card  v1.11.0  
light-entity-card.js?hacstag=168744428500:6868   LIGHT-ENTITY-CARD     Version 5.0.0       
meteoalarm-card.js?hacstag=3612056631141:285  METEOALARM-CARD  1.14.1 
card-mod.js?hacstag=190927524314:5 CARD-MOD 3.1.4 IS INSTALLED
card-mod.js?hacstag=190927524314:5 You may not be getting optimal performance out of card-mod.
See https://github.com/thomasloven/lovelace-card-mod#performance-improvements
slider-button-card.js?hacstag=3754399611103:497   SLIDER-BUTTON-CARD  v1.10.3 
alarmo-card.js?hacstag=391372854140:880   ALARMO-CARD    Version: v1.4.0 
multiple-entity-row.js?hacstag=178921037441:1  MULTIPLE-ENTITY-ROW  4.4.1 
mwc-list-item-base.ts:224 Uncaught (in promise) http://192.168.188.106:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=303101606172
frigate-hass-card.js?hacstag=394082552300:21563   FRIGATE-HASS-CARD   Version 3.0.0    
mushroom.js?hacstag=444350375188:2578 🍄 Mushroom 🍄 - 1.8.8
mwc-list-item-base.ts:224 Uncaught (in promise) http://192.168.188.106:8123/hacsfiles/upcoming-media-card/upcoming-media-card.js?hacstag=146783593043
2:8123/config:1 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mushroom-action-picker" has already been used with this registry
e318687c.js:2 Uncaught (in promise) Error: Map container is already initialized.
    at i._initContainer (e318687c.js:2:37860)
    at i.initialize (e318687c.js:2:26233)
    at new i (e318687c.js:2:2911)
    at Object.ee [as map] (e318687c.js:2:46362)
    at ha-entity-marker.ts:6:1
    at async l.value (ha-entity-marker.ts:6:1)
hacs:1 Uncaught (in promise) Object
icon.png:1          Failed to load resource: the server responded with a status of 404 ()
```

**Comment by ludeeus** [comment] 2022-05-27 07:50
Duplicate of #2703

**Closed by ludeeus** 2022-05-27 07:50 UTC
Labels: issue:frontend
