### ISSUE TITLE
Add new item list should be filtered by your current ui tab.

### ISSUE THREAD

**Issue by niemyjski** [hacs/integration#1211] opened 2020-05-22 13:47 UTC
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## The idea

There are three categories on top (Integrations, Frontend, Automation). The  add button should filter the integrations by the page you are currently on, so if you are on front end tab, you don't see integrations listed in the add dialog. This would also make much more sense for the automation tab because I don't even know how to add an automation to this section...

**Comment by ludeeus** [comment] 2020-05-22 13:51
Hi @niemyjski, like I said in <https://github.com/hacs/integration/issues/1194>, this needs to be split into multiple FR's.

Leaving it as is would become messy, quite fast.

**Comment by niemyjski** [comment] 2020-05-22 14:02
@ludeeus updated, sorry about that

**Comment by ludeeus** [comment] 2020-05-22 14:41
Duplicate of https://github.com/hacs/integration/issues/1189

**Closed by ludeeus** 2020-05-22 14:41 UTC
Labels: Feature Request
