### ISSUE TITLE
Text Missing From Tab in Frontend or Integration Windows

### ISSUE THREAD

**Issue by rcblackwell** [hacs/integration#2328] opened 2021-12-05 03:04 UTC
### Web browser

Google Chrome, Home Assistant for IOS on Apple iPhone 12

### Web browser version

Version 96.0.4664.45 (Official Build) (64-bit), Home Assistant IOS

## System Health

version | core-2021.11.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.75
arch | aarch64
timezone | America/Toronto

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4829
Installed Version | 1.18.0
Stage | running
Available Repositories | 911
Installed Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | December 22, 2021, 7:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | failed to load: timeout

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 113.9 GB
disk_used | 6.8 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | SSH & Web Terminal (9.1.1), File editor (5.3.3), Node-RED (10.2.0), Home Assistant Google Drive Backup (0.105.2), Samba share (9.5.1), Check Home Assistant configuration (3.9.0), Network UPS Tools (0.9.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 5
-- | --
resources | 5
views | 23
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Since updating to HACS version 1.18.0, Frontend Version 20211128181314, text on either the Frontend or Integration tab is missing from each of the alternate views. The attached image illustrated what I mean - HACS is open to the Integrations tab. Test for the Frontend tab should appear left of that tab. Using the ,mouse, one can highlight the tab then click on it to change to the Frontend window. Once the Frontend window is selected, text on the Integration tab is missing. An image of what I see is attached.

This occurs when I'm using either Google Chrome, Microsoft Edge or Home Assistant IOS

![HACS Missing Tab Text](https://user-images.githubusercontent.com/70527431/144731563-8b1cfb25-7e77-4aab-a956-53553a5b3a54.png)

Please disregard the need for me to restart HA. This has been done. Issue remains.
. 

### Reproduction steps

1. Open HACS from the Home Assistant menu bar
2. Select the Frontend or Integration tab
3. Observe the tabs at the top of the open window - text for the alternate tab is missing
...

### Screenshots

![HACS Missing Tab Text](https://user-images.githubusercontent.com/70527431/144731738-6ffe170e-1f2e-4dc8-9065-1c1526875fd6.png)
)

### Javascript logs from your browser console

```text
Don't know if this is what your after -
﻿
styles.ts:365 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. See https://lit.dev/msg/deprecated-import-path for more information.

If not, let me know what is needed and I'll try to provide
```

**Comment by ludeeus** [comment] 2021-12-05 09:23
Duplicate of https://github.com/hacs/integration/issues/2316

**Closed by ludeeus** 2021-12-05 09:23 UTC
Labels: issue:frontend
