### ISSUE TITLE
HACS No aparecen ni se pueden añadir los repositorios

### ISSUE THREAD

**Issue by Agusope** [hacs/integration#3550] opened 2024-03-16 14:39 UTC
### Web browser

Firefox

### Web browser version

123.0.1 (64-bit)

## System Information

version | core-2024.3.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.20-haos
arch | aarch64
timezone | Europe/Madrid
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1473
Downloaded Repositories | 1
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.03.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 28.0 GB
disk_used | 4.7 GB
healthy | true
supported | true
board | green
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.10.0), File editor (5.8.0), Node-RED (17.0.9)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 10 de marzo de 2024, 16:41
-- | --
current_recorder_run | 15 de marzo de 2024, 23:19
estimated_db_size | 2.90 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues

### Reproduction steps

1. Instalar HACS
2.Reinicio HomeAssistant Green
3. Borrar la caché del navegador
4. Añade la integración
5. Añade la integración
6. Aceptar uso
7. Registro de dispositivos
8. Autorizar HACS
9.Cambiar las opciones de HACS
10. Haga clic en enviar y espere la confirmación
11. Todos los pasos anteriores OK
12.Reinicio HomeAssistant Green
13. Inicio HACS
14.no aparecen los Repositorios (adjunto captura de pantalla)
15. Intento agregar los Repositorios (con el botón + Browse Repositorios)
16.Indica mensaje en pantalla (Browse dialog removed) 
...

### Screenshots

<img width="1201" alt="Captura de pantalla 2024-03-16 a las 15 12 05" src="https://github.com/hacs/integration/assets/163587302/f23124cc-c4bb-48f0-b371-58d0570bc954">
<img width="1815" alt="Captura de pantalla 2024-03-16 a las 15 11 35" src="https://github.com/hacs/integration/assets/163587302/36853863-22dc-4b73-b870-703a45dc6b27">

### Javascript logs from your browser console

```text
No se como extraer el registro de Javascript en Firefox ¿me podrían indicar como hacerlo?
```

### Diagnostics dump

[config_entry-hacs-3bfa07d6d30a5daf8c861f9bbbbb6afc.json](https://github.com/hacs/integration/files/14623888/config_entry-hacs-3bfa07d6d30a5daf8c861f9bbbbb6afc.json)

**Comment by ludeeus** [comment] 2024-03-16 15:12
See allready open/close issues.
Duplicate of quite a few allready.

**Closed by ludeeus** 2024-03-16 15:12 UTC
Labels: issue:frontend
