### ISSUE TITLE
an "update all" button

### ISSUE THREAD

**Issue by pejotigrek** [hacs/integration#1314] opened 2020-06-07 20:12 UTC
## Category

- [ ] Backend/Integration
- [X] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [X] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

a convenient way to run all pending updates - just like it was in the "old" UI.

## Implementation

I can imagine a button "update all" that shows up when there are some pending updates. right now it requires few clicks to get all updates running.

## Alternatives

can't see any.

## Additional context

none.

**Comment by ludeeus** [comment] 2020-06-07 20:16
Duplicate of https://github.com/hacs/integration/issues/1254

**Closed by ludeeus** 2020-06-07 20:16 UTC
Labels: Feature Request
