### ISSUE TITLE
Unable to add new repository - Integration Category (haven't tested others)

### ISSUE THREAD

**Issue by SeLLeRoNe** [hacs/integration#1169] opened 2020-05-20 12:29 UTC
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         | 0.24.5
Home Assistant version         | 0.110.0
Installation method for HA    | python env
Web browser                         | Chrome
Web browser version            | 81.0.4044.138

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.

## Describe the issue
Impossible to add new repository (integration)

A clear and concise description of what the issue is.
Once I click to add the new repository nothing happen

### Steps to reproduce

1. Add this repo: https://github.com/franc6/ics_calendar
2. Select "Integration" as Category
3. Click "save" button

## Javascript logs from your browser console
```
Uncaught TypeError: Cannot read property 'selectedItem' of undefined
    at HTMLElement.Save (frontend-20200426112021.js:2437)
    at T.handleEvent (frontend-20200426112021.js:1)
    at HTMLElement.T.__boundHandleEvent (frontend-20200426112021.js:1)
```
<details>
  <summary>Logs</summary>

```text

2020-05-20 14:28:26 ERROR (MainThread) [frontend.js.latest.202005190] https://*********/hacsfiles/frontend-20200426112021.js:2437:1387 Uncaught TypeError: Cannot read property 'selectedItem' of undefined

```

</details>

**Comment by ludeeus** [comment] 2020-05-20 12:31
duplicate of https://github.com/hacs/integration/issues/1143

**Closed by ludeeus** 2020-05-20 12:31 UTC
Labels: issue:frontend

**Comment by SeLLeRoNe** [comment] 2020-05-20 12:34
Ah sorry, I did check only the "still open" issues ^^

**Comment by ludeeus** [comment] 2020-05-20 12:35
I use issues as a task list, so they get closed when they are fixed in master
