### ISSUE TITLE
Add Custom Repositories Not Working

### ISSUE THREAD

**Issue by c0nt4x** [hacs/integration#2887] opened 2022-10-11 13:00 UTC
### Web browser

Google Chrome

### Web browser version

Version 106.0.5249.103 (Official Build) (32-bit)

## System Information

version | core-2022.10.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.67
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4480
Installed Version | 1.28.0
Stage | running
Available Repositories | 1128
Downloaded Repositories | 26

</details>

<details><summary>AccuWeather</summary>

error | failed to load: unknown
-- | --

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | October 21, 2022 at 1:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-west-2-5.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.0
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.0
agent_version | 1.3.0
docker_version | 20.10.17
disk_total | 62.3 GB
disk_used | 7.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), Terminal & SSH (9.6.1), File editor (5.4.1), AdGuard Home (4.7.4), AirCast (3.4.1), Grafana (8.0.2), Home Panel (2.5.0), InfluxDB (4.5.0), Tor (4.0.2), WireGuard (0.7.0), Git pull (7.13.1), Home Assistant Google Drive Backup (0.108.4), AppDaemon (0.9.3), Mosquitto broker (6.1.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 10
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 1, 2022 at 10:38 AM
-- | --
current_recorder_run | October 11, 2022 at 1:28 PM
estimated_db_size | 307.42 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When selecting the 'Explore and Download Repositories' button, then when on the Home Assistant Community Store - Explore page selecting the 3 dots then 'Custom Repositories, nothing happens. There is nowhere to add the custom repository link like there was before.

I have tried on Google Chrome and Safari and via the Home Assistant Companion app but with the same result.

### Reproduction steps

1.  Select HACS
2.  Select Explore and Download Repositories
3.  Home Assistant Community Store - Explore opens
4.  Select the 3 menu dots
5. Select Custom Repositories
6. No popup for custom link
...

### Screenshots

![HACS](https://user-images.githubusercontent.com/70321584/195097406-539ad460-8f11-4304-b97d-786cbaa70621.png)

### Javascript logs from your browser console

```text
card-mod.js:5 CARD-MOD 3.1.5 IS INSTALLED
:8123/local/custom-brand-icons.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)
:8123/lovelace/home:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://192.168.1.68:8123/local/custom-brand-icons.js
hass-hue-icons.js:2018  HASS-HUE-ICONS  Version 1.2.45 
fold-entity-row.js?hacstag=150781994220:78 FOLD-ENTITY-ROW 2.2.0 IS INSTALLED 
button-card.js?hacstag=146194325342:425   BUTTON-CARD   Version 3.4.2 
mini-graph-card-bundle.js?hacstag=1512800620110:1  MINI-GRAPH-CARD  0.11.0 
hass-hue-icons.js?hacstag=3844345221245:2018  HASS-HUE-ICONS  Version 1.2.45 
weather-radar-card.js?hacstag=487680971210:1291   WEATHER-RADAR-CARD   Version 2.1.0    
mushroom.js?hacstag=444350375213:2823 🍄 Mushroom 🍄 - 2.1.3
e318687c.js:2 Uncaught (in promise) Error: Map container is already initialized.
    at i._initContainer (e318687c.js:2:37860)
    at i.initialize (e318687c.js:2:26233)
    at new i (e318687c.js:2:2911)
    at Object.ee [as map] (e318687c.js:2:46362)
    at ha-entity-marker.ts:6:1
    at async c.value (ha-entity-marker.ts:6:1)
localhost:5000/mushroom.js:1          Failed to load resource: net::ERR_CONNECTION_REFUSED
cebaf2eb.js:1 Uncaught (in promise) http://localhost:5000/mushroom.js
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
hassio-ingress-view.ts:70 Uncaught (in promise) 3
icon.png:1          Failed to load resource: the server responded with a status of 404 ()
icon.png:1          Failed to load resource: the server responded with a status of 404 ()
icon.png:1          Failed to load resource: the server responded with a status of 404 ()
core.8b15dd5b.js:1 WebSocket connection to 'ws://192.168.1.68:8123/api/websocket' failed: 
i @ core.8b15dd5b.js:1
core.8b15dd5b.js:1 WebSocket connection to 'ws://192.168.1.68:8123/api/websocket' failed: 
i @ core.8b15dd5b.js:1
core.8b15dd5b.js:1 WebSocket connection to 'ws://192.168.1.68:8123/api/websocket' failed: 
i @ core.8b15dd5b.js:1
​ Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
e._parseColor @ :8123/api/hassio_ing…WCLYScJwAlZoCXJQ/:1
​ [ttyd] websocket connection opened
​ Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
e._drawToCache @ :8123/api/hassio_ing…WCLYScJwAlZoCXJQ/:1
​ [ttyd] WebGL renderer enabled
core.8b15dd5b.js:1 WebSocket connection to 'ws://192.168.1.68:8123/api/websocket' failed: 
i @ core.8b15dd5b.js:1
core.8b15dd5b.js:1 WebSocket connection to 'ws://192.168.1.68:8123/api/websocket' failed: 
i @ core.8b15dd5b.js:1
core.8b15dd5b.js:1 WebSocket connection to 'ws://192.168.1.68:8123/api/websocket' failed: 
i @ core.8b15dd5b.js:1
core.8b15dd5b.js:1 WebSocket connection to 'ws://192.168.1.68:8123/api/websocket' failed: 
i @ core.8b15dd5b.js:1
:8123/developer-tools/yaml:1 Uncaught (in promise) Object
:8123/developer-tools/yaml:1 Uncaught (in promise) Object
:8123/developer-tools/yaml:1 Uncaught (in promise) Object
:8123/developer-tools/yaml:1 Uncaught (in promise) Object
:8123/developer-tools/yaml:1 Uncaught (in promise) Object
:8123/developer-tools/yaml:1 Uncaught (in promise) Object
:8123/developer-tools/yaml:1 Uncaught (in promise) Object
:8123/developer-tools/yaml:1 Uncaught (in promise) Object
c.59603ecb.js:1202 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at F.render (c.59603ecb.js:1202:22)
    at F.update (main-bd0f996b.js:1:23426)
    at F.performUpdate (main-bd0f996b.js:1:14355)
    at F.scheduleUpdate (main-bd0f996b.js:1:14002)
    at F._$EC (main-bd0f996b.js:1:13910)
c.59603ecb.js:1202 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at F.render (c.59603ecb.js:1202:22)
    at F.update (main-bd0f996b.js:1:23426)
    at F.performUpdate (main-bd0f996b.js:1:14355)
    at F.scheduleUpdate (main-bd0f996b.js:1:14002)
    at F._$EC (main-bd0f996b.js:1:13910)
:8123/config/repairs:1 Uncaught (in promise) Object
```

### Diagnostics dump

[config_entry-hacs-195264a99441d6c595e411f45571b6e8.json.txt](https://github.com/hacs/integration/files/9755930/config_entry-hacs-195264a99441d6c595e411f45571b6e8.json.txt)

**Comment by ludeeus** [comment] 2022-10-11 13:01
duplicate of #2886

**Closed by ludeeus** 2022-10-11 13:01 UTC
Labels: issue:frontend
