### ISSUE TITLE
"Remote Home-Assistant" integration keeps appearing as new integration although dismissed a few times

### ISSUE THREAD

**Issue by christophebaraer** [hacs/integration#1797] opened 2021-01-07 20:21 UTC
I noticed that the the integration called "Remote Home-Assistant" keep reappearing to the list of new integrations although I have already dismissed it a few times (see image). Additionally, I've noticed that this integration is listed as a Custom repositories (see image) although I have never added it.

<img width="50%" alt="Screenshot 2021-01-07 at 21 15 26" src="https://user-images.githubusercontent.com/38278243/103940579-d68ee800-512d-11eb-91dd-aeb30d2304b3.png">

<img width="50%" alt="Screenshot 2021-01-07 at 21 15 38" src="https://user-images.githubusercontent.com/38278243/103940581-d7277e80-512d-11eb-9212-3762677ea1c0.png">

**Details :**
HA Version : 2021.1.0
HA Installation Type : Home Assistant OS
HACS Installed Version : 1.9.0

How can I get rid of this message / repo ?

**Comment by SeraphimSerapis** [comment] 2021-01-16 13:00
Same issue. I also noticed that "HomeWizard Energy" ([repo](https://github.com/DCSBL/ha-homewizard-energy)) got added to the list of custom repos.

Regarding "Remote Home-Assistant": I even "cleaned" my HACS installation by removing it completely from my HA installation (including deleting the files in .storage) and re-installing. A couple of minutes later, "Remote Home-Assistant" was back

**Comment by DCSBL** [comment] 2021-01-16 21:55
I am the developer of "HomeWizard Energy" and can reproduce the problem. I think the issue has to do with a repo that is transferred:

- Transferred "Unsigus/hass-homewizard-energy" to [DCSBL/ha-homewizard-energy](https://github.com/DCSBL/ha-homewizard-energy) with GitHub
- Added this change to defaults/integrations, but PR is still pending (https://github.com/hacs/default/pull/765)

This also seems to be happened to `Remote Home Assistant`, it was transferred from lukas-hetzenecker/remote_homeassistant to [custom-components/remote_homeassistant](https://github.com/custom-components/remote_homeassistant)

**Comment by andriej** [comment] 2021-01-20 08:05
+1
I have the same problem and it's with both of those transfered repositories

**Comment by dutchcandy** [comment] 2021-02-03 12:33
Exactly the same issue for me

**Comment by johntdyer** [comment] 2021-02-07 15:04
Same issue for both home-energy and home-assistant-remote... every restart they are new and I have to dismiss again

**Comment by mgiebels** [comment] 2021-02-07 16:12
Same issue here both wil every reboot come back

**Comment by aaamoeder** [comment] 2021-02-08 03:31
same issue here..

**Comment by rasmusbe** [comment] 2021-02-09 15:21
Now it is getting crazy
![image](https://user-images.githubusercontent.com/2124386/107385102-e1ed7e80-6af2-11eb-89df-d5769c55b2f1.png)

**Comment by DCSBL** [comment] 2021-02-09 15:39
@rasmusbe Last hours, new repositories are added to HACS. So the 'new repository' message is for real this time. You can dismiss it via the HACS menu. Only 'Remote Home-Assistant' will reappear, but they are working on that.

I am not sure why it pops up at the custom repository list, but those also go away after a restart.

**Comment by rccoleman** [comment] 2021-02-26 03:45
It's still popping up on every HA restart for me.

**Comment by mgiebels** [comment] 2021-02-26 05:14
Here the same after reboot its back

**Comment by sondreen** [comment] 2021-03-02 08:34
Still an issue

**Comment by rccoleman** [comment] 2021-03-06 00:44
https://github.com/hacs/default/pull/757, hopefully

**Closed** 2021-03-06 00:49 UTC
