### ISSUE TITLE
HACS is stuck at 'HACS is setting up' on new installation

### ISSUE THREAD

**Issue by outlooknerd** [hacs/integration#1721] opened 2020-12-14 10:55 UTC
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.8.0
| Home Assistant version     |2020.12.6
| Installation method for HA |Proxmox VE

## Checklist

- [x ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x ] I have enabled debug logging for my installation.
- [x ] I have filled out the issue template to the best of my ability.
- [x ] I have read <https://hacs.xyz/docs/issues>
- [x ] This issue is related to the backend of HACS.
- [x ] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Just installed HA Supervised on a Proxmox and then tried to install HACS. Followed the instructions and then used the HA Intregrations to finish the final steps. HACS shows up in the left sidepanel, but never gets past 'HACS is setting up'. When locking at HA logs, there is an error setup up HACS. Se details below.

Logger: homeassistant.config_entries
Source: core.py:174
First occurred: 11.42.03 (1 occurrences)
Last logged: 11.42.03

Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 30, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 67, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 92, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 197, in async_hacs_startup
    async_call_later(hacs.hass, 5, hacs.startup_tasks())
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1179, in async_call_later
    return async_track_point_in_utc_time(
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1133, in async_track_point_in_utc_time
    job = action if isinstance(action, HassJob) else HassJob(action)
  File "/usr/src/homeassistant/homeassistant/core.py", line 174, in __init__
    raise ValueError("Coroutine not allowed to be passed to HassJob")
ValueError: Coroutine not allowed to be passed to HassJob

### Steps to reproduce

1.Run HA Supervised on Proxmox
2.Copy HACS installation files via SAMBA to HA custom_components folder
3.Install HACS as new Integration

## Debug logs

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by Kajkac** [comment] 2020-12-14 11:11
I have the same issue:

HACS version | 1.8.0
Home Assistant version : 2020.12.0
Installation method for HA | HYPER-V

[home-assistant.log](https://github.com/hacs/integration/files/5688369/home-assistant.log)

**Comment by salvatooo** [comment] 2020-12-14 12:19
same problem here as well...

**Comment by n3tkiller** [comment] 2020-12-14 12:46
+1

**Comment by Kajkac** [comment] 2020-12-14 12:49
This fixes for me : it's a version problem

zuzumandanas on discord posted
Fix /config/custom_components/hacs/operational/setup.py for new 2020 version

https://pastebin.pl/view/1d67e852

**Comment by outlooknerd** [comment] 2020-12-14 13:01
> This fixes for me : it's a version problem
> 
> zuzuman on discord posted
> Fix /config/custom_components/hacs/operational/setup.py for new 2020 version
> 
> https://pastebin.pl/view/1d67e852

That worked for me as well - thank you @Kajkac :-)

**Comment by MrLukson** [comment] 2020-12-14 13:03
It's working with solution from @Kajkac

**Comment by n3tkiller** [comment] 2020-12-14 13:05
haha indeed, that was a hidden egg by HA team :D
beta release notes handled the version as 1.0 and yesterday it came out as 2020.12... :)

**Comment by salvatooo** [comment] 2020-12-14 13:05
> This fixes for me : it's a version problem
> 
> zuzuman on discord posted
> Fix /config/custom_components/hacs/operational/setup.py for new 2020 version
> 
> https://pastebin.pl/view/1d67e852

This works for me too.. thanks! @Kajkac

**Comment by outlooknerd** [comment] 2020-12-14 13:20
Well. There must be other problems. The solution with replacing setup.py for initial setup worked, but afterwards HACS has been disabled without further information.

**Comment by Kajkac** [comment] 2020-12-14 13:25
For me is working i have added themes and integrations normaly.

**Comment by outlooknerd** [comment] 2020-12-14 13:31
During the setup of HACS through Integrations, I dont get to paste the Personal Access Token from Github - I just have to authorize the device. Isn't that wrong?

**Comment by Kajkac** [comment] 2020-12-14 13:36
On version 1.6 u have access token , later when its bumped to 1.8 outh is used trough device authorization, if u wanna use github access token then u need to do manual configuration.

https://hacs.xyz/docs/configuration/legacy

**Comment by Depechie** [comment] 2020-12-14 14:37
Can the solution be paste somewhere else than pastebin? Somehow I'm unable to open the site. It gives a timeout.

**Comment by Kajkac** [comment] 2020-12-14 14:39
[setup.txt](https://github.com/hacs/integration/files/5689404/setup.txt)

just rename it to .py

**Comment by outlooknerd** [comment] 2020-12-14 14:40
I got it to work after I deleted the HACS integration, deleted the HACS folder in config\.storage and the hacs.critical, hacs.hacs and hacs.repositories file. After which I reinstall it again.

**Comment by JurajNyiri** [comment] 2020-12-14 17:24
Getting the same, reinstall did not help.

I modified the setup.py, even though it id not throw an error, it still doesn't show the tab and the URL /hacs returns 404.

**Comment by raflaisaahole** [comment] 2020-12-14 18:18
> [setup.txt](https://github.com/hacs/integration/files/5689404/setup.txt)
> 
> just rename it to .py

that works!!!

**Comment by jugla** [comment] 2020-12-14 22:36
The setup.txt has not worked for me.
I revert to 0.118.5 HA and works again

**Comment by Sowjetlev** [comment] 2020-12-14 23:00
Still have the issue with the modified setup.py

**Comment by Sowjetlev** [comment] 2020-12-14 23:04
Now after a restart it worked

**Comment by JurajNyiri** [comment] 2020-12-15 00:07
I have tried reinstalling the component, restarting, replaced setup.py, restarted and now it worked.

**Comment by ludeeus** [comment] 2020-12-15 00:21
Duplicate of <https://github.com/hacs/integration/issues/1693> use <https://github.com/hacs/integration/releases/tag/1.9.0>

**Closed by ludeeus** 2020-12-15 00:21 UTC
Labels: issue:backend

**Comment by speedbrown** [comment] 2021-01-13 06:33
> This fixes for me : it's a version problem
> 
> zuzuman on discord posted
> Fix /config/custom_components/hacs/operational/setup.py for new 2020 version
> 
> https://pastebin.pl/view/1d67e852

This works, but like @outlooknerd said you have to also delete any file that starts with "hacs" (ie hacs.critacal, hacs.hacs, etc) in the the \config\.storage folder of of HA

**Comment by andrist** [comment] 2021-02-07 09:02
"removing hacs.critical + restart" fixed it for me (I did not have any other hacs.* files in .storage)
