### ISSUE TITLE
bpost integration is removed from githib

### ISSUE THREAD

**Issue by schumi2309** [hacs/integration#2472] opened 2022-01-25 11:20 UTC
### System Health details

I cannot remove the bpost integration and is giving un uncomplete hacs status
sdebruyn / homeassistant-bpost-integration
### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Unable to remove add-on. the repo was deleted

### Reproduction steps

1. delete ( not fonction)
2.update is ok
3.
...

### Debug logs

```text
no log
```

**Comment by ludeeus** [comment] 2022-01-25 11:23
Duplicate of #2470

**Comment by schumi2309** [comment] 2022-01-25 11:24
no issue ??

**Closed by ludeeus** 2022-01-25 11:23 UTC
Labels: issue:backend

**Comment by schumi2309** [comment] 2022-01-25 11:28
what is the solution please ?

**Comment by ludeeus** [comment] 2022-01-25 11:28
Duplicate of #2470

**Comment by schumi2309** [comment] 2022-01-25 11:30
yes, I understood correctly, but there is no answer, and we can no longer post in #2470.
What to do ?

**Comment by ludeeus** [comment] 2022-01-25 11:31
You wait until it's resolved.

**Comment by schumi2309** [comment] 2022-01-25 11:33
ok, thanks
