### ISSUE TITLE
Cannot add custom repositories

### ISSUE THREAD

**Issue by petarvucetin** [hacs/integration#1171] opened 2020-05-20 18:57 UTC
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         | 0.24.5
Home Assistant version         | 0.110.0
Installation method for HA    | VM
Web browser                         | firefox
Web browser version            | 76.0.1

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.

## Describe the issue

Cannot save custom repositories

### Steps to reproduce

1. Try adding any custom repository

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

Logger: frontend.js.latest.202005190
Source: components/system_log/__init__.py:209
First occurred: 8:54:35 AM (45 occurrences)
Last logged: 9:18:55 AM



    https://zzzzzzzzzzz.ui.nabu.casa/hacsfiles/frontend-20200426112021.js:2437:1358 TypeError: e.composedPath(...)[2].children[1] is undefined
    https://zzzzzzzzzzzzzzui.nabu.casa/hacsfiles/frontend-20200426112021.js:21594:31 TypeError: ev.composedPath(...)[2].children[1] is undefined

```
FIREFOX
```
TypeError: ev.composedPath(...)[2].children[1] is undefinedfrontend-20200426112021.js:21594:31
    Save https://zzzzzz.ui.nabu.casa/hacsfiles/frontend-20200426112021.js:21594
    handleEvent https://zzzzzzz.ui.nabu.casa/hacsfiles/frontend-20200426112021.js:1090
    __boundHandleEvent https://zzzzzz.ui.nabu.casa/hacsfiles/frontend-20200426112021.js:1056
```
</details>

**Comment by ludeeus** [comment] 2020-05-20 18:58
duplicate of https://github.com/hacs/integration/issues/1143

**Closed by ludeeus** 2020-05-20 18:58 UTC
Labels: issue:frontend
