### ISSUE TITLE
Not possible in HACS to remove an integration which is not exist anymore on github

### ISSUE THREAD

**Issue by zigomatichub** [hacs/integration#2473] opened 2022-01-26 14:00 UTC
### Repository

https://api.github.com/repos/sdebruyn/homeassistant-bpost-integration

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Hello, I'm facing an issue to remove completely from HACS an integration
1. I install one integration and I used for some days
2. Owner of the integration remove the reference in Github
3. I Remove successfully the integration in HA but in HACS, it's not possible to remove the same.

2022-01-26 14:51:05 DEBUG (MainThread) [custom_components.hacs] Running uninstall for sdebruyn/homeassistant-bpost-integration
2022-01-26 14:51:05 DEBUG (MainThread) [custom_components.hacs] <Integration sdebruyn/homeassistant-bpost-integration> Getting repository information
2022-01-26 14:51:06 ERROR (MainThread) [custom_components.hacs] <Integration sdebruyn/homeassistant-bpost-integration> GitHub returned 404 for https://api.github.com/repos/sdebruyn/homeassistant-bpost-integration
2022-01-26 14:51:06 ERROR (MainThread) [custom_components.hacs] Could not use repository with ID 433968883 ('NoneType' object has no attribute 'get_releases')

### Link to issue

https://github.com/sdebruyn

**Comment by ludeeus** [comment] 2022-01-26 14:01
duplicate of #2470

**Closed by ludeeus** 2022-01-26 14:01 UTC
Labels: flag
