### ISSUE TITLE
Error setting up entry for hacs

### ISSUE THREAD

**Issue by Garulf** [hacs/integration#1615] opened 2020-10-29 10:17 UTC
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.6.1
| Home Assistant version     |   0.116.4
| Installation method for HA | Docker

## Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

HACS never initiates and is stuck "setting up".

### Steps to reproduce

1. Installed HACS to custom_components folder 
2. Restart Home assistant docker
3. Added HACS intergration and added github key

## Debug logs

<details>
  <summary>Logs</summary>

```

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 30, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 62, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 87, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 188, in async_hacs_startup
    async_call_later(hacs.hass, 5, hacs.startup_tasks())
TypeError: startup_tasks() missing 1 required positional argument: '_event'

```

</details>

**Comment by ludeeus** [comment] 2020-10-29 10:36
Duplicate of #1614

**Closed by ludeeus** 2020-10-29 10:36 UTC
Labels: issue:backend

**Comment by Garulf** [comment] 2020-10-29 13:18
Sorry, it seems we both opened the same issue within the same hour. Thanks for the fix!
