### ISSUE TITLE
Javascript error when clicking on the + button

### ISSUE THREAD

**Issue by robcos** [hacs/integration#1203] opened 2020-05-22 08:41 UTC
[localhost-1590136745651.log](https://github.com/hacs/integration/files/4666964/localhost-
1590136745651.log)
<img width="512" alt="Screenshot 2020-05-22 at 09 40 35" src="https://user-images.githubusercontent.com/64998/82648953-68ce9400-9c10-11ea-8332-e8e6d7198bbe.png">

Home Assistant 0.110.1

**Comment by ludeeus** [comment] 2020-05-22 08:43
Invalid issue (missing issue template), duplicate of https://github.com/hacs/integration/issues/1190

**Closed by ludeeus** 2020-05-22 08:43 UTC
Labels: invalid
