### ISSUE TITLE
Installing frontend cards never finishes with Lovelace in "yaml" mode and at least one dashboard in "storage" mode

### ISSUE THREAD

**Issue by rccoleman** [hacs/integration#2308] opened 2021-11-22 22:57 UTC
## System Health

version | core-2021.11.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.78
arch | x86_64
timezone | America/Los_Angeles

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4936
Installed Version | 1.17.2
Stage | running
Available Repositories | 970
Installed Repositories | 30

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | December 16, 2021, 4:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | us-west-2-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.0.rc1
-- | --
update_channel | beta
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.9
disk_total | 36.7 GB
disk_used | 7.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.2.1), Glances (0.14.0), File editor (5.3.3), Samba share (9.5.1), Remote Backup (v0.4.8), ESPHome (2021.11.1), Log Viewer (dev), SSH & Web Terminal (9.1.1), Portainer (2.0.0)

</details>

<details><summary>Universal Devices ISY994</summary>

host_reachable | ok
-- | --
device_connected | true
last_heartbeat | November 22, 2021, 2:44 PM
websocket_status | connected

</details>

<details><summary>keymaster</summary>

zwave_integration | zwave_js
-- | --
network_status | on

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 16
views | 6
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

I have Lovelace primarily in YAML mode, but I also have one dashboard in storage mode for which I have taken control.  Whenever I install, update, or re-install a Lovelace card, the card is installed properly, but it appears that HACS attempts to install the resource and fails.  I'm managing resources myself in `configuration.yaml`, so I don't expect HACS to install a resource, but I suspect that it's getting confused and doesn't think that the installation process has completed.  When the resource installation fails (as seen in the log), the installation dialog stays on the screen forever with the install button spinning until I hit the "x" to dismiss it.

![image](https://user-images.githubusercontent.com/860888/142946092-e084070d-b496-459b-a259-236d586ea8c6.png)

I can see the card dashboard updating in the background behind the installation dialog, so it's clear that HACS is doing its job, just not closing the dialog.  The issue is cosmetic, but it's unexpected to have to dismiss the dialog manually.

### Reproduction steps

1. Configure Lovelace in "yaml" mode and configure the primary dashboard
2. Add a dashboard in storage mode
3. Install frontend cards through HACS and observe that the installation dialog never completes.

### Debug logs

```text
2021-11-22 14:48:40 DEBUG (MainThread) [custom_components.hacs] Running update for nervetattoo/simple-thermostat
2021-11-22 14:48:40 DEBUG (MainThread) [custom_components.hacs] <Plugin nervetattoo/simple-thermostat> Getting repository information
2021-11-22 14:48:41 DEBUG (MainThread) [custom_components.hacs] <Plugin nervetattoo/simple-thermostat> Running checks against v2.4.3
2021-11-22 14:48:42 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-11-22 14:48:42 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-11-22 14:48:42 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.repositories'. Content did not change
2021-11-22 14:48:47 DEBUG (MainThread) [custom_components.hacs] Running install for nervetattoo/simple-thermostat
2021-11-22 14:48:47 DEBUG (MainThread) [custom_components.hacs] <Plugin nervetattoo/simple-thermostat> Getting repository information
2021-11-22 14:48:47 DEBUG (MainThread) [custom_components.hacs] <Plugin nervetattoo/simple-thermostat> Running checks against v2.4.2
2021-11-22 14:48:48 INFO (MainThread) [custom_components.hacs] Running pre installation steps
2021-11-22 14:48:48 INFO (MainThread) [custom_components.hacs] Pre installation steps completed
2021-11-22 14:48:48 INFO (MainThread) [custom_components.hacs] Running installation steps
2021-11-22 14:48:48 DEBUG (MainThread) [custom_components.hacs] <Plugin nervetattoo/simple-thermostat> Getting repository information
2021-11-22 14:48:48 DEBUG (MainThread) [custom_components.hacs] <Plugin nervetattoo/simple-thermostat> Running checks against v2.4.2
2021-11-22 14:48:49 DEBUG (MainThread) [custom_components.hacs] 
2021-11-22 14:48:49 DEBUG (MainThread) [custom_components.hacs] Checking out tasks to execute
2021-11-22 14:48:49 DEBUG (MainThread) [custom_components.hacs] Starting queue execution for 1 tasks
2021-11-22 14:48:49 DEBUG (MainThread) [custom_components.hacs] Downloading simple-thermostat.js
2021-11-22 14:48:49 DEBUG (MainThread) [custom_components.hacs] Downloading https://github.com/nervetattoo/simple-thermostat/releases/download/v2.4.2/simple-thermostat.js
2021-11-22 14:48:49 INFO (MainThread) [custom_components.hacs] Download of simple-thermostat.js completed
2021-11-22 14:48:49 DEBUG (MainThread) [custom_components.hacs] Queue execution finished for 1 tasks finished in 0.72 seconds
2021-11-22 14:48:49 INFO (MainThread) [custom_components.hacs] Installation steps completed
2021-11-22 14:48:49 INFO (MainThread) [custom_components.hacs] Running post installation steps
2021-11-22 14:48:49 INFO (MainThread) [custom_components.hacs] Post installation steps completed
2021-11-22 14:48:49 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-11-22 14:48:49 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-11-22 14:48:51 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140441220829968] Received invalid command: lovelace/resources/update
```
```

**Comment by ludeeus** [comment] 2021-11-22 23:15
Duplicate of https://github.com/hacs/integration/issues/2294 fixed in Home Assistant 2021.12

**Closed by ludeeus** 2021-11-22 23:15 UTC
Labels: issue:backend
