### ISSUE TITLE
ModuleNotFoundError: No module named 'aiogithubapi'

### ISSUE THREAD

**Issue by danygi79** [hacs/integration#836] opened 2019-12-01 19:53 UTC
hacs not work, log is this:

2019-12-01 18:57:05 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.hacs. Make sure all dependencies are installed
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 346, in _load_file
module = importlib.import_module(path)
File "/usr/local/lib/python3.7/importlib/init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1006, in _gcd_import
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "", line 728, in exec_module
File "", line 219, in _call_with_frames_removed
File "/config/custom_components/hacs/init.py", line 8, in
from aiogithubapi import AIOGitHub
ModuleNotFoundError: No module named 'aiogithubapi'

Raspberry 3b+ whit duster and docker, hass.io ver 0.102.3, hacs ver. 0.17.4

**Comment by ludeeus** [comment] 2019-12-01 19:54
duplicate of  https://github.com/hacs/integration/issues/828

**Closed** 2019-12-01 19:54 UTC
