### ISSUE TITLE
Update want downgrade my Version

### ISSUE THREAD

**Issue by Jey-Pee** [hacs/integration#2514] opened 2022-02-16 07:41 UTC
### Web browser

Google Chrome

### Web browser version

 98.0.4758.82 (Offizieller Build) (64-Bit)

## System Health

version | core-2022.2.5
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 4.4.180+
arch | x86_64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4987
Installed Version | 1.22.0
Stage | running
Available Repositories | 1049
Downloaded Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 0
views | 6
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Just download HACS for my Docker Container - works good.
Now i want to add a new Device but must downgrade before i can use it.
Look at the screenshot.

### Reproduction steps

1. download hacs for docker
2. restart home Assistant
3. click on hECs
...

### Screenshots

![image](https://user-images.githubusercontent.com/99790965/154217612-06082aba-dacf-4cb8-b837-e579df7f81ea.png)

### Javascript logs from your browser console

```text
what ?
```

### Diagnostics dump

[config_entry-hacs-56d70c976560e40a378f5f0777ffc6dd.json.txt](https://github.com/hacs/integration/files/8077745/config_entry-hacs-56d70c976560e40a378f5f0777ffc6dd.json.txt)

**Comment by ludeeus** [comment] 2022-02-16 07:42
Duplicate of #2495

**Closed by ludeeus** 2022-02-16 07:42 UTC
Labels: issue:frontend

**Comment by Jey-Pee** [comment] 2022-02-16 07:47
Sorry my - fail - new at github  - please delete it.
