### ISSUE TITLE
Custom Repositories option does not work after upgrade

### ISSUE THREAD

**Issue by thelordzero** [hacs/integration#2881] opened 2022-10-09 19:20 UTC
### Web browser

Edge

### Web browser version

106.0.1370.30 

### System Health details

n/a

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The ability to open the custom repositories dialog has ceased working. Clicking on it does nothing.

### Reproduction steps

1. Open menu for more options within HACS
2. Click on Custom Repositories
3. No action occurs

### Screenshots

![image](https://user-images.githubusercontent.com/1511794/194775542-93d8dd8d-6d88-4001-986e-02ccd3eaa9c3.png)

### Javascript logs from your browser console

```text
n/a
```

### Diagnostics dump

[config_entry-hacs-def9b0350e870b2daba284aaa6620caf.json.txt](https://github.com/hacs/integration/files/9742393/config_entry-hacs-def9b0350e870b2daba284aaa6620caf.json.txt)

**Comment by ludeeus** [comment] 2022-10-09 19:22
Duplicate of #2880

**Closed by ludeeus** 2022-10-09 19:22 UTC
Labels: issue:frontend

**Comment by riddik14** [comment] 2022-10-12 12:42
why do you close the reports? at least you are at work for the resolution? thank you
