### ISSUE TITLE
GUI navigate link for updated integrations not working

### ISSUE THREAD

**Issue by WallyDW** [hacs/integration#2657] opened 2022-05-05 09:00 UTC
### Web browser

Several

### Web browser version

Newest

### System Health details

Home Assistant Community Store
GitHub API 	ok
GitHub Content 	ok
GitHub Web 	ok
GitHub API Calls Remaining 	4692
Installed Version 	1.24.5
Stage 	running
Available Repositories 	1031
Downloaded Repositories 	45

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

doing an update in HACS that requires a restart, then the Navigate link in the text that pops up does not work anymore.
Probably due to changes in the HA menu structure.
The result of clicking the link is just a black page in the area that had the HACS menus.

### Reproduction steps

Update something that requires a restart.

### Screenshots

![billede](https://user-images.githubusercontent.com/86269202/166891280-0bdd5a85-89fb-4e36-a36d-19eaff3fc311.png)

### Javascript logs from your browser console

```text
Not sure what you want here
```

### Diagnostics dump

I do not seem to have that option available

**Comment by ludeeus** [comment] 2022-05-05 09:02
Duplicate of https://github.com/hacs/integration/issues/2655

**Closed by ludeeus** 2022-05-05 09:02 UTC
Labels: issue:frontend
