### ISSUE TITLE
Doesnt seem to recognize that its uninstalled the logbook_cache

### ISSUE THREAD

**Issue by johntdyer** [hacs/integration#1502] opened 2020-08-30 16:14 UTC
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.5.2
| Home Assistant version     |104.3
| Installation method for HA | standard

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Itkeeps prompting me that I should uninstall logbook_cache, and I believe it actually did uninstall it, but hac's doesnt seem to recognize that it did and keeps prompting me to uninstall it again.

### Steps to reproduce

Unknown ??  

## Debug logs

<details>
  <summary>Logs</summary>

```text

2020-08-30 11:58:01 ERROR (MainThread) [custom_components.hacs.api.repository] Could not uninstall
2020-08-30 11:59:29 ERROR (MainThread) [custom_components.hacs.api.repository] Could not uninstall
2020-08-30 12:05:16 ERROR (MainThread) [custom_components.hacs.api.repository] Could not uninstall
2020-08-30 12:05:38 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.139846191718512] Received {'type': 'hacs/repository', 'action': 'uninstall', 'repository': '235453407', 'id': 82}
2020-08-30 12:05:38 DEBUG (MainThread) [custom_components.hacs.api.repository] Running uninstall for amelchio/logbook_cache
2020-08-30 12:05:38 ERROR (MainThread) [custom_components.hacs.api.repository] Could not uninstall
2020-08-30 12:05:38 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event hacs/error[L]: message=Could not uninstall>
2020-08-30 12:05:38 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.139846877279040] Sending {'id': 25, 'type': 'event', 'event': {'event_type': 'hacs/error', 'data': {'message': 'Could not uninstall'}, 'origin': 'LOCAL', 'time_fired': datetime.datetime(2020, 8, 30, 16, 5, 38, 98276, tzinfo=<UTC>), 'context': {'id': 'a50b75bfeada11ea9bae6308d9ac6b32', 'parent_id': None, 'user_id': None}}}
2020-08-30 12:05:38 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: name=custom_components.hacs.api.repository, message=['Could not uninstall'], level=ERROR, source=['custom_components/hacs/api/hacs_repository.py', 102], timestamp=1598803538.0981405, exception=, count=1, first_occurred=1598803538.0981405>
2020-08-30 12:05:38 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.139846877279040] Sending {'id': 25, 'type': 'event', 'event': {'event_type': 'system_log_event', 'data': {'name': 'custom_components.hacs.api.repository', 'message': ['Could not uninstall'], 'level': 'ERROR', 'source': ['custom_components/hacs/api/hacs_repository.py', 102], 'timestamp': 1598803538.0981405, 'exception': '', 'count': 1, 'first_occurred': 1598803538.0981405}, 'origin': 'LOCAL', 'time_fired': datetime.datetime(2020, 8, 30, 16, 5, 38, 106480, tzinfo=<UTC>), 'context': {'id': 'a50cb650eada11eab3dfc9c40c92b8b9', 'parent_id': None, 'user_id': None}}}
2020-08-30 12:05:38 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.139846730130528] Sending {'id': 2, 'type': 'event', 'event': {'event_type': 'system_log_event', 'data': {'name': 'custom_components.hacs.api.repository', 'message': ['Could not uninstall'], 'level': 'ERROR', 'source': ['custom_components/hacs/api/hacs_repository.py', 102], 'timestamp': 1598803538.0981405, 'exception': '', 'count': 1, 'first_occurred': 1598803538.0981405}, 'origin': 'LOCAL', 'time_fired': datetime.datetime(2020, 8, 30, 16, 5, 38, 106480, tzinfo=<UTC>), 'context': {'id': 'a50cb650eada11eab3dfc9c40c92b8b9', 'parent_id': None, 'user_id': None}}}
2020-08-30 12:06:39 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.139846191265824] Received {'type': 'hacs/repository', 'action': 'uninstall', 'repository': '235453407', 'id': 45}
2020-08-30 12:06:39 DEBUG (MainThread) [custom_components.hacs.api.repository] Running uninstall for amelchio/logbook_cache
2020-08-30 12:06:39 ERROR (MainThread) [custom_components.hacs.api.repository] Could not uninstall
2020-08-30 12:06:39 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event hacs/error[L]: message=Could not uninstall>
2020-08-30 12:06:39 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.139846877279040] Sending {'id': 25, 'type': 'event', 'event': {'event_type': 'hacs/error', 'data': {'message': 'Could not uninstall'}, 'origin': 'LOCAL', 'time_fired': datetime.datetime(2020, 8, 30, 16, 6, 39, 4688, tzinfo=<UTC>), 'context': {'id': 'c9590aa1eada11ea9ddd7bc7a35b4518', 'parent_id': None, 'user_id': None}}}
2020-08-30 12:06:39 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event system_log_event[L]: name=custom_components.hacs.api.repository, message=['Could not uninstall'], level=ERROR, source=['custom_components/hacs/api/hacs_repository.py', 102], timestamp=1598803599.0045922, exception=, count=1, first_occurred=1598803599.0045922>
2020-08-30 12:06:39 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.139846877279040] Sending {'id': 25, 'type': 'event', 'event': {'event_type': 'system_log_event', 'data': {'name': 'custom_components.hacs.api.repository', 'message': ['Could not uninstall'], 'level': 'ERROR', 'source': ['custom_components/hacs/api/hacs_repository.py', 102], 'timestamp': 1598803599.0045922, 'exception': '', 'count': 1, 'first_occurred': 1598803599.0045922}, 'origin': 'LOCAL', 'time_fired': datetime.datetime(2020, 8, 30, 16, 6, 39, 11826, tzinfo=<UTC>), 'context': {'id': 'c95a219aeada11ea8e333f515e0ac6d5', 'parent_id': None, 'user_id': None}}}
2020-08-30 12:06:39 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.139846730130528] Sending {'id': 2, 'type': 'event', 'event': {'event_type': 'system_log_event', 'data': {'name': 'custom_components.hacs.api.repository', 'message': ['Could not uninstall'], 'level': 'ERROR', 'source': ['custom_components/hacs/api/hacs_repository.py', 102], 'timestamp': 1598803599.0045922, 'exception': '', 'count': 1, 'first_occurred': 1598803599.0045922}, 'origin': 'LOCAL', 'time_fired': datetime.datetime(2020, 8, 30, 16, 6, 39, 11826, tzinfo=<UTC>), 'context': {'id': 'c95a219aeada11ea8e333f515e0ac6d5', 'parent_id': None, 'user_id': None}}}
16:10:23 root@coruscant.local ~ 

```

</details>

It uninstalled this app but it doesnt seem to think it has and keeps prompting me.

**Comment by ludeeus** [comment] 2020-08-30 16:15
duplicate of https://github.com/hacs/integration/issues/1472

**Closed by ludeeus** 2020-08-30 16:15 UTC
Labels: issue:backend
