### ISSUE TITLE
HACS menu page doesn't follow dark mode

### ISSUE THREAD

**Issue by mynameisdaniel32** [hacs/integration#1674] opened 2020-11-23 22:50 UTC
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.6.2
| Home Assistant version     | 0.118.2
| Installation method for HA | Core in venv
| Web browser                | Chrome (Windows)
| Web browser version        | Latest

## Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

See screenshot below, the entry page for HACS (/hacs/entry) does not correctly show the background when using dark mode during the day (my Windows PC is pernamently in dark mode). All other pages (i.e. integrations) work fine and it's okay on iOS (if you refresh after switching to night mode).

I don't run any themes, etc. HA just follows my 

### Steps to reproduce

1. Set computer to dark mode
2. Go to /hacs/entry
3. Be blinded ;)

### Screenshots

![image](https://user-images.githubusercontent.com/24840952/100023465-f21b8900-2e34-11eb-9540-2ec51f69ec46.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```
Picture probably sums this up better.
```
![image](https://user-images.githubusercontent.com/24840952/100024116-1af04e00-2e36-11eb-938c-34866fad8d75.png)

</details>

**Comment by ludeeus** [comment] 2020-11-23 22:55
Duplicate of https://github.com/hacs/integration/issues/1657

**Closed by ludeeus** 2020-11-23 22:55 UTC
Labels: issue:frontend
