### ISSUE TITLE
Cant add custom repos via settings

### ISSUE THREAD

**Issue by codeclinic** [hacs/integration#913] opened 2020-01-02 21:17 UTC
On the latest versions of HA & HACS I'm unable to add custom github repos via the settings page. 
The input boxes seem to refresh at random intervals causing them to lose the input url &/or project category.

If I'm lucky enough to get all the info added and press the save button, a popup imples that the repo has been added but nothing shows up anywhere in HACS to confirm this. So, it's not possible to then install the new project via HACS.

**Comment by ludeeus** [comment] 2020-01-02 21:18
Duplicate of hacs/frontend#58

**Closed** 2020-01-02 21:18 UTC

**Comment by DavidFW1960** [comment] 2020-01-03 08:56
Exactly same as I am seeing.
