### ISSUE TITLE
"Unexpected frontend version" since latest update

### ISSUE THREAD

**Issue by haseat** [hacs/integration#1351] opened 2020-06-22 06:37 UTC
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.1.1
| Home Assistant version     | 0.111.4
| Installation method for HA | Supervised
| Web browser                | Chrome
| Web browser version        | Version 83.0.4103.106 (Official Build) (64-bit)

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I just updated HACS to 1.1.1 (from 1.1.0). After restarting HA, I get this information in HACS:

Unexpected frontend version
You are running version 202006071141 of the HACS frontend, but version 202006201137 was ...

### Screenshots

![image](https://user-images.githubusercontent.com/61622258/85255930-85eec080-b463-11ea-868c-2c1142b60537.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment] 2020-06-22 06:38
duplicate of #1350

**Closed by ludeeus** 2020-06-22 06:38 UTC
Labels: issue:frontend
