### ISSUE TITLE
USA-RedDragon/badnest

### ISSUE THREAD

**Issue by sbryfcz** [hacs/integration#1593] opened 2020-10-20 14:48 UTC
It seems that BadNest repo is no longer alive.

**Comment by kubiani** [comment] 2020-10-21 19:40
Looks like the repo just needs to be updated in HACS. Maintainer moved it from USA-RedDragon to mattsch

https://github.com/mattsch/badnest

**Comment by camui-alexandru** [comment] 2020-10-24 09:35
How can we uninstall badnest ? If the repository is gone, HACS wont uninstall it it gives error that the repository dosen't exist

**Comment by tborychowski** [comment] 2020-10-25 15:15
I have the same issue.
I tried removing the files manually but that didn't do anything - "badnest" still shows up on the integrations list and now there's a notification on every restart that the integration is not found.
There also doesn't seem to be anything in the docs mentioning how to remove broken repos.
This is very annoying!

**Comment by kallejoken** [comment] 2020-10-28 22:36
does anyone already have a solution how to remove the repo?

**Comment by mmmmmmbeer** [comment] 2020-10-31 12:38
I stumbled upon a solution. I don't know if all these steps are necessary, but this is what I did:

1) Removed any references to badnest from configuration.yaml
2) Deleted badnest folder and files from custom_components directory
3) In Lovelace UI, browse to "Community" in lefthand menu; Click "Integrations"
4) On the integrations page, click the vertical ellipsis (three dot menu) in the very top-right corner
5) Select "Custom repositories" and click the trash can.

It's possible steps 3-5 alone will do it, but I had already attempted 1 and 2 with no success. Badnest is now gone, and still gone upon restart. No more errors in log.

**Comment by tborychowski** [comment] 2020-10-31 13:01
Thanks so much @mmmmmmbeer!
This worked for me too!
With the exception of no 3. - I don't see "Community" anywhere. In my dashboard it's just called "HACS".

**Comment by mmmmmmbeer** [comment] 2020-10-31 13:04
Yes, I've seen that as well on a previous install - I think it has something to do with the way HACS is installed/configured on your Home Assistant. I'll add that to my answer for clarity. Thanks!

**Comment by KTibow** [comment] 2020-10-31 14:36
Duplicate of #1619

**Comment by tborychowski** [comment] 2020-10-31 17:38
@KTibow This issue was created earlier, so it's the pther way around 😉

**Comment by kallejoken** [comment] 2020-11-02 08:21
Thank you!

**Comment by ludeeus** [comment] 2020-11-04 21:28
This is not a default repo, and can therefore not be removed here, remove it from your custom repositories:
 - https://hacs.xyz/docs/faq/custom_repositories

- https://hacs.xyz/docs/default_repositories
- https://github.com/hacs/default

**Closed by ludeeus** 2020-11-04 21:28 UTC
Labels: flag
