### ISSUE TITLE
Request for removal of Villhellm/lovelace-animated-background

### ISSUE THREAD

**Issue by datenzar** [hacs/integration#3149] opened 2023-06-11 06:50 UTC
### Repository

Villhellm/lovelace-animated-background

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

Unfortunately the author of this popular package passed away. With the latest HA changes, this plugin breaks. Another user has created a fork which might be used as a replacement: https://github.com/dreimer1986/lovelace-animated-background

### Link to issue

https://github.com/Villhellm/lovelace-animated-background/issues/56

**Comment by tjorim** [comment] 2023-06-11 15:39
Duplicate of #3115 and #3130.

**Closed** 2023-06-17 15:41 UTC
Labels: flag
