### ISSUE TITLE
Night mode support

### ISSUE THREAD

**Issue by ckesc** [hacs/integration#1465] opened 2020-08-17 13:40 UTC
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.3.3
| Home Assistant version     |0.114.0
| Installation method for HA |

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ ] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [ ] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue
When new HA night mode enabled it's hard to read anything in HACS page

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2548610/90402486-3239d580-e0a8-11ea-98c0-85170a8fa6c6.png">

### Steps to reproduce

1. Enable night mode in HA
1. Go to HACS page

**Comment by ludeeus** [comment] 2020-08-17 13:41
Duplicate of #1447

**Closed by ludeeus** 2020-08-17 13:41 UTC
Labels: issue:backend
