### ISSUE TITLE
Can't add any custom repo

### ISSUE THREAD

**Issue by finity69x2** [hacs/integration#910] opened 2019-12-31 19:43 UTC
## Version of HACS

0.20.4

## Describe the bug

I'm trying to add a custom repo under the "settings" tab. Every time I click on the spot to paste/type in the repo github address after a couple of seconds any entry that I made disappears and the field goes blank again. The same thing happens if I click on the drop down menu for selecting which type of repo it is. As soon as I click on a repo type it fills the box then a second or two later it goes back to being blank.

## Debug log

```
2019-12-31 14:20:17 DEBUG (MainThread) [hacs] Configuration type: yaml
2019-12-31 14:20:17 INFO (MainThread) [hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 0.20.4
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2019-12-31 14:20:17 DEBUG (MainThread) [hacs.repository.integration.hacs.integration] Checking repository.
2019-12-31 14:20:22 INFO (MainThread) [hacs.repository.integration.hacs.integration] Registration complete
2019-12-31 14:20:22 INFO (MainThread) [hacs.data] Restore started
2019-12-31 14:20:23 INFO (MainThread) [hacs.data] Restore done
2019-12-31 14:20:23 WARNING (MainThread) [hacs] Configuration option 'theme' is deprecated and you should remove it from your configuration, HACS will know if you use 'theme' in your Home Assistant configuration, this option will be removed in a future release.
2019-12-31 14:20:41 DEBUG (MainThread) [hacs] 4182
2019-12-31 14:20:41 DEBUG (MainThread) [hacs] 2019-12-31 19:37:48
2019-12-31 14:20:42 INFO (MainThread) [hacs] Loading known repositories
2019-12-31 14:20:49 DEBUG (MainThread) [hacs.factory] No tasks to execute
2019-12-31 14:20:49 WARNING (MainThread) [hacs] You have maykar/compact-custom-header installed with HACS this repository has been blacklisted, please consider removing it.
2019-12-31 14:20:49 DEBUG (MainThread) [hacs] Starting recuring background task for installed repositories
2019-12-31 14:20:49 DEBUG (MainThread) [hacs] 4167
2019-12-31 14:20:49 DEBUG (MainThread) [hacs] 2019-12-31 19:37:48
2019-12-31 14:20:49 INFO (MainThread) [hacs.factory] Prosessing 53 tasks
2019-12-31 14:20:49 DEBUG (MainThread) [hacs.repository.integration.hacs.integration] Getting repository information
2019-12-31 14:20:49 DEBUG (MainThread) [hacs.repository.integration.custom-components.alexa_media_player] Getting repository information
2019-12-31 14:20:49 DEBUG (MainThread) [hacs.repository.integration.custom-components.weatheralerts] Getting repository information
2019-12-31 14:20:49 DEBUG (MainThread) [hacs.repository.integration.custom-components.authenticated] Getting repository information
2019-12-31 14:20:49 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.vertical-stack-in-card] Getting repository information
2019-12-31 14:20:49 DEBUG (MainThread) [hacs.repository.plugin.thomasloven.lovelace-slider-entity-row] Getting repository information
2019-12-31 14:20:49 DEBUG (MainThread) [hacs.repository.plugin.iantrich.aftership-card] Getting repository information
2019-12-31 14:20:49 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.list-card] Getting repository information
2019-12-31 14:20:49 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.button-card] Getting repository information
2019-12-31 14:20:49 DEBUG (MainThread) [hacs.repository.plugin.thomasloven.lovelace-fold-entity-row] Getting repository information
2019-12-31 14:20:49 DEBUG (MainThread) [hacs.repository.plugin.kalkih.mini-graph-card] Getting repository information
2019-12-31 14:20:49 DEBUG (MainThread) [hacs.repository.integration.custom-components.sensor.unifigateway] Getting repository information
2019-12-31 14:20:49 DEBUG (MainThread) [hacs.repository.plugin.thomasloven.lovelace-layout-card] Getting repository information
2019-12-31 14:20:49 DEBUG (MainThread) [hacs.repository.plugin.thomasloven.lovelace-state-switch] Getting repository information
2019-12-31 14:20:49 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.secondaryinfo-entity-row] Getting repository information
2019-12-31 14:20:50 DEBUG (MainThread) [hacs] Serving aftership-card/aftership-card.js from /config/www/community/aftership-card/aftership-card.js.gz
2019-12-31 14:20:50 DEBUG (MainThread) [hacs] Serving atomic_calendar/atomic_calendar.js from /config/www/community/atomic_calendar/atomic_calendar.js.gz
2019-12-31 14:20:50 DEBUG (MainThread) [hacs] Serving button-card/button-card.js from /config/www/community/button-card/button-card.js.gz
2019-12-31 14:20:50 DEBUG (MainThread) [hacs] Serving custom-header/custom-header.js from /config/www/community/custom-header/custom-header.js.gz
2019-12-31 14:20:50 DEBUG (MainThread) [hacs] Serving config-template-card/config-template-card.js from /config/www/community/config-template-card/config-template-card.js.gz
2019-12-31 14:20:50 DEBUG (MainThread) [hacs] Serving flex-horseshoe-card/flex-horseshoe-card.js from /config/www/community/flex-horseshoe-card/flex-horseshoe-card.js.gz
2019-12-31 14:20:50 DEBUG (MainThread) [hacs] Serving lovelace-battery-entity/battery-entity.js from /config/www/community/lovelace-battery-entity/battery-entity.js.gz
2019-12-31 14:20:50 DEBUG (MainThread) [hacs] Serving lovelace-card-mod/card-mod.js from /config/www/community/lovelace-card-mod/card-mod.js.gz
2019-12-31 14:20:50 DEBUG (MainThread) [hacs] Serving lovelace-fold-entity-row/fold-entity-row.js from /config/www/community/lovelace-fold-entity-row/fold-entity-row.js.gz
2019-12-31 14:20:50 DEBUG (MainThread) [hacs] Serving mini-graph-card/mini-graph-card-bundle.js from /config/www/community/mini-graph-card/mini-graph-card-bundle.js.gz
2019-12-31 14:20:50 DEBUG (MainThread) [hacs] Serving text-divider-row/text-divider-row.js from /config/www/community/text-divider-row/text-divider-row.js.gz
2019-12-31 14:20:50 DEBUG (MainThread) [hacs] Serving popup-backdrop-filter/popup-backdrop-filter.js from /config/www/community/popup-backdrop-filter/popup-backdrop-filter.js.gz
2019-12-31 14:20:50 DEBUG (MainThread) [hacs] Serving bar-card/bar-card.js from /config/www/community/bar-card/bar-card.js.gz
2019-12-31 14:20:50 DEBUG (MainThread) [hacs] Serving entity-attributes-card/entity-attributes-card.js from /config/www/community/entity-attributes-card/entity-attributes-card.js.gz
2019-12-31 14:20:51 DEBUG (MainThread) [hacs] Serving fan-control-entity-row/fan-control-entity-row.js from /config/www/community/fan-control-entity-row/fan-control-entity-row.js.gz
2019-12-31 14:20:51 DEBUG (MainThread) [hacs] Serving gauge-card/gauge-card.js from /config/www/community/gauge-card/gauge-card.js.gz
2019-12-31 14:20:51 DEBUG (MainThread) [hacs] Serving group-card/group-card.js from /config/www/community/group-card/group-card.js.gz
2019-12-31 14:20:51 DEBUG (MainThread) [hacs] Serving list-card/list-card.js from /config/www/community/list-card/list-card.js.gz
2019-12-31 14:20:51 DEBUG (MainThread) [hacs] Serving lovelace-card-templater/lovelace-card-templater.js from /config/www/community/lovelace-card-templater/lovelace-card-templater.js.gz
2019-12-31 14:20:51 DEBUG (MainThread) [hacs] Serving lovelace-home-feed-card/lovelace-home-feed-card.js from /config/www/community/lovelace-home-feed-card/lovelace-home-feed-card.js.gz
2019-12-31 14:20:51 DEBUG (MainThread) [hacs] Serving lovelace-slider-entity-row/slider-entity-row.js from /config/www/community/lovelace-slider-entity-row/slider-entity-row.js.gz
2019-12-31 14:20:51 DEBUG (MainThread) [hacs] Serving lovelace-state-switch/state-switch.js from /config/www/community/lovelace-state-switch/state-switch.js.gz
2019-12-31 14:20:51 DEBUG (MainThread) [hacs] Serving lovelace-swipe-navigation/swipe-navigation.js from /config/www/community/lovelace-swipe-navigation/swipe-navigation.js.gz
2019-12-31 14:20:51 DEBUG (MainThread) [hacs] Serving secondaryinfo-entity-row/secondaryinfo-entity-row.js from /config/www/community/secondaryinfo-entity-row/secondaryinfo-entity-row.js.gz
2019-12-31 14:20:51 DEBUG (MainThread) [hacs] Serving vertical-stack-in-card/vertical-stack-in-card.js from /config/www/community/vertical-stack-in-card/vertical-stack-in-card.js.gz
2019-12-31 14:20:51 DEBUG (MainThread) [hacs] Serving lovelace-auto-entities/auto-entities.js from /config/www/community/lovelace-auto-entities/auto-entities.js.gz
2019-12-31 14:20:51 DEBUG (MainThread) [hacs] Serving lovelace-card-tools/card-tools.js from /config/www/community/lovelace-card-tools/card-tools.js.gz
2019-12-31 14:20:51 DEBUG (MainThread) [hacs] Serving radar-forecast/radar-forecast.js from /config/www/community/radar-forecast/radar-forecast.js.gz
2019-12-31 14:20:51 DEBUG (MainThread) [hacs] Serving lovelace-layout-card/layout-card.js from /config/www/community/lovelace-layout-card/layout-card.js.gz
2019-12-31 14:20:51 DEBUG (MainThread) [hacs] Serving lovelace-theme-maker/theme-maker.js from /config/www/community/lovelace-theme-maker/theme-maker.js.gz
2019-12-31 14:20:51 DEBUG (MainThread) [hacs] Serving zha-network-card/zha-network-card.js from /config/www/community/zha-network-card/zha-network-card.js.gz
2019-12-31 14:20:56 DEBUG (MainThread) [hacs.repository.plugin.bundito.radar-forecast] Getting repository information
2019-12-31 14:20:56 DEBUG (MainThread) [hacs.repository.plugin.maykar.compact-custom-header] Getting repository information
2019-12-31 14:20:56 DEBUG (MainThread) [hacs.repository.plugin.thomasloven.lovelace-card-tools] Getting repository information
2019-12-31 14:20:56 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.bar-card] Getting repository information
2019-12-31 14:20:56 DEBUG (MainThread) [hacs.repository.plugin.thomasloven.lovelace-auto-entities] Getting repository information
2019-12-31 14:20:56 DEBUG (MainThread) [hacs.repository.plugin.atomic7777.atomic_calendar] Getting repository information
2019-12-31 14:20:56 DEBUG (MainThread) [hacs.repository.integration.custom-components.climate.programmable_thermostat] Getting repository information
2019-12-31 14:20:56 DEBUG (MainThread) [hacs.repository.plugin.gadgetchnnel.lovelace-home-feed-card] Getting repository information
2019-12-31 14:20:56 DEBUG (MainThread) [hacs.repository.integration.dcshoecomp.noaa_alerts] Getting repository information
2019-12-31 14:20:56 DEBUG (MainThread) [hacs.repository.plugin.cbulock.lovelace-battery-entity] Getting repository information
2019-12-31 14:20:56 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.text-divider-row] Getting repository information
2019-12-31 14:20:56 DEBUG (MainThread) [hacs.repository.plugin.thomasloven.lovelace-theme-maker] Getting repository information
2019-12-31 14:20:56 DEBUG (MainThread) [hacs.repository.integration.custom-components.breaking_changes] Getting repository information
2019-12-31 14:20:56 DEBUG (MainThread) [hacs.repository.plugin.maykar.lovelace-swipe-navigation] Getting repository information
2019-12-31 14:20:56 DEBUG (MainThread) [hacs.repository.plugin.gadgetchnnel.lovelace-card-templater] Getting repository information
2019-12-31 14:21:02 DEBUG (MainThread) [hacs.repository.integration.MatthewFlamm.nwsradar] Getting repository information
2019-12-31 14:21:02 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.entity-attributes-card] Getting repository information
2019-12-31 14:21:03 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.gauge-card] Getting repository information
2019-12-31 14:21:03 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.group-card] Getting repository information
2019-12-31 14:21:03 DEBUG (MainThread) [hacs.repository.plugin.thomasloven.lovelace-card-mod] Getting repository information
2019-12-31 14:21:03 DEBUG (MainThread) [hacs.repository.plugin.finity69x2.fan-control-entity-row] Getting repository information
2019-12-31 14:21:03 DEBUG (MainThread) [hacs.repository.integration.pnbruckner.ha-illuminance] Getting repository information
2019-12-31 14:21:03 DEBUG (MainThread) [hacs.repository.integration.mudape.iphonedetect] Getting repository information
2019-12-31 14:21:03 DEBUG (MainThread) [hacs.repository.integration.pnbruckner.ha-sun2] Getting repository information
2019-12-31 14:21:03 DEBUG (MainThread) [hacs.repository.integration.thomasloven.hass-browser_mod] Getting repository information
2019-12-31 14:21:03 DEBUG (MainThread) [hacs.repository.integration.pilotak.homeassistant-attributes] Getting repository information
2019-12-31 14:21:03 DEBUG (MainThread) [hacs.repository.appdaemon.apop880.config-check] Getting repository information
2019-12-31 14:21:03 DEBUG (MainThread) [hacs.repository.plugin.dmulcahey.zha-network-card] Getting repository information
2019-12-31 14:21:03 DEBUG (MainThread) [hacs.repository.integration.custom-components.templatesensor] Getting repository information
2019-12-31 14:21:04 DEBUG (MainThread) [hacs.repository.integration.dlashua.templatebinarysensor] Getting repository information
2019-12-31 14:21:09 DEBUG (MainThread) [hacs.repository.integration.custom-components.healthchecksio] Getting repository information
2019-12-31 14:21:09 DEBUG (MainThread) [hacs.repository.theme.bbbenji.synthwave-hass] Getting repository information
2019-12-31 14:21:09 DEBUG (MainThread) [hacs.repository.integration.thomasloven.hass-favicon] Getting repository information
2019-12-31 14:21:09 DEBUG (MainThread) [hacs.repository.plugin.gabe565.popup-backdrop-filter] Getting repository information
2019-12-31 14:21:09 DEBUG (MainThread) [hacs.repository.integration.twrecked.hass-momentary] Getting repository information
2019-12-31 14:21:09 DEBUG (MainThread) [hacs.repository.plugin.AmoebeLabs.flex-horseshoe-card] Getting repository information
2019-12-31 14:21:10 DEBUG (MainThread) [hacs.repository.integration.pinkywafer.Anniversaries] Getting repository information
2019-12-31 14:21:10 DEBUG (MainThread) [hacs.repository.plugin.maykar.custom-header] Getting repository information
2019-12-31 14:21:16 INFO (MainThread) [hacs.factory] Task prosessing of 53 tasks completed in 27 seconds
2019-12-31 14:21:16 DEBUG (MainThread) [hacs.data] Saving data
2019-12-31 14:21:16 DEBUG (MainThread) [hacs] Recuring background task for installed repositories done
2019-12-31 14:21:16 DEBUG (MainThread) [hacs.data] Saving data
2019-12-31 14:23:56 DEBUG (MainThread) [hacs] Serving lovelace-home-feed-card/moment.js from /config/www/community/lovelace-home-feed-card/moment.js.gz
2019-12-31 14:23:56 DEBUG (MainThread) [hacs] Serving lovelace-home-feed-card/custom-card-helpers.js from /config/www/community/lovelace-home-feed-card/custom-card-helpers.js.gz
2019-12-31 14:23:57 DEBUG (MainThread) [hacs] Serving lovelace-home-feed-card/fecha.js from /config/www/community/lovelace-home-feed-card/fecha.js.gz
2019-12-31 14:24:18 DEBUG (MainThread) [hacs] Running set_state for custom-components/breaking_changes
2019-12-31 14:24:18 DEBUG (MainThread) [hacs.data] Saving data
2019-12-31 14:24:18 DEBUG (MainThread) [hacs] Running update for custom-components/breaking_changes
2019-12-31 14:24:18 DEBUG (MainThread) [hacs.repository.integration.custom-components.breaking_changes] Getting repository information
2019-12-31 14:24:20 DEBUG (MainThread) [hacs.data] Saving data
```

**Comment by ludeeus** [comment] 2019-12-31 19:51
Duplicate of  https://github.com/hacs/frontend/issues/58

**Closed** 2019-12-31 19:51 UTC
