### ISSUE TITLE
Incompatibility with dynamic themes

### ISSUE THREAD

**Issue by agneevX** [hacs/integration#2090] opened 2021-06-18 06:31 UTC
### Web browser

Safari

### Web browser version

14.1

## System Health

version | core-2021.6.3
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
virtualenv | true
python_version | 3.8.5
os_name | Linux
os_version | 5.4.0-1036-raspi
arch | aarch64

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.12.4
Stage | running
Available Repositories | 845
Installed Repositories | 17

</details>
</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

When a dynamic theme is set, HACS iframe resets to the default Home Assistant theme

### Reproduction steps

1. Set a dynamic theme
2. Confirm that it does not apply to HACS

### Screenshots

<img width="916" alt="Screen Shot 2021-06-18 at 12 00 49 PM" src="https://user-images.githubusercontent.com/19761269/122516799-d3791b80-d02c-11eb-9bd9-b1daf311f45c.png">

### Javascript logs from your browser console

```text
N/A
```

**Comment by ludeeus** [comment] 2021-06-18 08:16
Duplicate of https://github.com/hacs/integration/issues/2078

**Closed by ludeeus** 2021-06-18 08:16 UTC
Labels: issue:frontend
