### ISSUE TITLE
Periodic exception from queueman: queueman.exceptions.QueueManagerExecutionStillInProgress

### ISSUE THREAD

**Issue by rccoleman** [hacs/integration#1495] opened 2020-08-28 01:52 UTC
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.5.2
| Home Assistant version     | 0.114.3
| Installation method for HA | Home Assistant OS in KVM running on Ubuntu

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I periodically see this in my log and I suspect that it's just happening in the background without any user interaction:

```
2020-08-27 03:20:34 INFO (MainThread) [custom_components.hacs] Loading known repositories
2020-08-27 03:20:35 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 306, in recurring_tasks_all
    await self.async_load_default_repositories()
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 346, in async_load_default_repositories
    await self.queue.execute()
  File "/usr/local/lib/python3.8/site-packages/queueman/manager.py", line 41, in execute
    raise QueueManagerExecutionStillInProgress
queueman.exceptions.QueueManagerExecutionStillInProgress
```

and it happened again later:

```
2020-08-27 16:40:34 INFO (MainThread) [custom_components.hacs] Loading known repositories
2020-08-27 16:40:35 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 306, in recurring_tasks_all
    await self.async_load_default_repositories()
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 346, in async_load_default_repositories
    await self.queue.execute()
  File "/usr/local/lib/python3.8/site-packages/queueman/manager.py", line 41, in execute
    raise QueueManagerExecutionStillInProgress
queueman.exceptions.QueueManagerExecutionStillInProgress
```

I don't see any abnormal behavior in HACS as a result, just reporting it if there's a corner case that needs to be handled.

### Steps to reproduce

I don't think I'm doing anything to cause it (especially at 3am), and I can't get it to happen from anything I do manually.  I have no custom repos and integration, frontend, and automation tabs enabled.  I last restarted HA 31 hours ago with only those two occurrences, so it doesn't happen frequently.

## Debug logs

See above.

**Comment by ludeeus** [comment] 2020-08-28 08:32
Duplicate of https://github.com/hacs/integration/issues/1441

**Closed by ludeeus** 2020-08-28 08:32 UTC
Labels: issue:backend

**Comment by rccoleman** [comment] 2020-08-28 16:40
Sigh, sorry about.  I did search and have no explanation for why it didn't come up.
