### ISSUE TITLE
Show more than the first 100 repositories

### ISSUE THREAD

**Issue by GeorgeSG** [hacs/integration#1223] opened 2020-05-22 17:26 UTC
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

Extracted from #1194 

"Only the first 100 repositories are shown, use the search to filter what you need". This is a hit to discoverability. It wouldn't be that big of a problem if there were filtering and sorting options, but as it is, some repositories will just never be shown.

For example, at least on my install, button-card is the second to last repository. This is one of the most popular and useful repositories IMO. It wouldn't be good if it isn't visible. Maybe users won't think to search for "button" - there already is a button at the end of the day, why would they need that?

## Implementation

Consider adding dynamic loading on scroll or pagination to the list.

**Comment by ludeeus** [comment] 2020-05-22 17:28
The issue with this is that on my test unit it would take >10s to load the popup when I showed all, that is unacceptable

**Comment by GeorgeSG** [comment] 2020-05-22 18:01
What's causing the slow down? API calls or rendering all items?

I'm not familiar with how this is implemented, but if there's a way you can do sorting and pagination on the back-end, maybe we can lazy load per-page / on scroll?

**Comment by royto** [comment] 2020-05-22 18:43
There is a lot to load also because all type of integration are loaded in the pop up. The loading will be less impacting if only a type is loaded depending on the selected tab ...

**Comment by ludeeus** [comment] 2020-05-24 10:40
Duplicate of https://github.com/hacs/integration/issues/1193

**Closed by ludeeus** 2020-05-24 10:40 UTC
Labels: Feature Request
