### ISSUE TITLE
Github authorize pop-up wrong text formatting

### ISSUE THREAD

**Issue by Guyohms** [hacs/integration#1715] opened 2020-12-10 13:24 UTC
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.8
| Home Assistant version     | 0.118.5
| Installation method for HA | Config Flow
| Web browser                | Chrome
| Web browser version        | 87.0.4280.88

## Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

On the onboarding screen authorizing Github, there's some `\n` showing

### Steps to reproduce

1. Install HACS from the Integration page

### Screenshots

![image](https://user-images.githubusercontent.com/44414660/101777749-eb417700-3ac0-11eb-90d3-97714ca07994.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```

No logs

```

</details>

**Comment by ludeeus** [comment] 2020-12-10 13:45
Duplicate of https://github.com/hacs/integration/issues/1701

**Closed by ludeeus** 2020-12-10 13:45 UTC
Labels: issue:frontend
