### ISSUE TITLE
Error with integration alandtse/tesla 

### ISSUE THREAD

**Issue by SteLu1803** [hacs/integration#2430] opened 2022-01-02 19:52 UTC
### System Health details

<html><body>
<h3>Home Assistant Community Store</h3>

GitHub API | ok
-- | --
Github API Calls Remaining | 4600
Installed Version | 1.18.0
Stage | running
Available Repositories | 991
Installed Repositories | 20

</body>
</html>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Every time I restart Home Assistant, I do get a Error stating that an specific hacs integration, that I do not use and have not installed, was not found.
If I search for this integration in hacs, it is displayed, but does not load any information but the name.

### Reproduction steps

1. Open HACS in Home Assistant
2. Jump to integrations tab and search for new integration
3. Search for "testla"
4. Click on tesla (not "Homeassistant Teslacustomcomponent")
5. Nothing but a empty popup is displayed (if not: restart Home assistant and start with step 1 again)
...

### Debug logs

```text
Logger: custom_components.hacs
Source: custom_components/hacs/hacsbase/data.py:181
Integration: HACS (documentation, issues)
First occurred: 20:08:43 (1 occurrences)
Last logged: 20:08:43

Did not find alandtse/tesla (362700564)

2022-01-02 20:48:51 ERROR (MainThread) [custom_components.hacs] Did not find alandtse/tesla (362700564)
```

**Comment by ludeeus** [comment] 2022-01-02 19:55
Duplicate of https://github.com/hacs/integration/issues/2383

**Closed by ludeeus** 2022-01-02 19:55 UTC
Labels: issue:backend
