### ISSUE TITLE
Request for removal of georgezhao2010/midea_ac_lan

### ISSUE THREAD

**Issue by Kenneth-Audenaert** [hacs/integration#4086] opened 2024-09-23 15:20 UTC
### Repository

georgezhao2010/midea_ac_lan

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

no longer maintained and outdated (breaking functionality)

### Link to issue

https://github.com/georgezhao2010/midea_ac_lan/issues/595

**Comment by jszczypk** [comment] 2024-10-03 14:55
That's a duplicate of #3748

**Comment by BEFH** [comment] 2024-10-08 02:44
> That's a duplicate of #3748

that's locked for some reason

**Closed** 2024-10-08 06:11 UTC
Labels: flag
