### ISSUE TITLE
Can't view or load custom repositories

### ISSUE THREAD

**Issue by ssneisius** [hacs/integration#2891] opened 2022-10-12 14:49 UTC
### Web browser

Chrome

### Web browser version

106.0.5249.103 (Official Build) (64-bit)

## System Information

version | core-2022.10.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.72
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4773
Installed Version | 1.28.0
Stage | running
Available Repositories | 1121
Downloaded Repositories | 34

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 8, 2023 at 8:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | us-east-1-4.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.0
agent_version | 1.4.1
docker_version | 20.10.17
disk_total | 56.6 GB
disk_used | 11.1 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.108.4), Studio Code Server (5.4.0), Node-RED (13.4.0), WireGuard (0.7.0), Mosquitto broker (6.1.3), TasmoBackup (1.05.00), ESPHome (2022.9.4), Z-Wave JS UI (1.1.0), Samba share (10.0.0), File editor (5.4.1), TTLock2MQTT (0.7)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 16
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 2, 2022 at 3:36 PM
-- | --
current_recorder_run | October 12, 2022 at 10:02 AM
estimated_db_size | 293.10 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

After latest update of HACS, I can't view custom repositories or add any.

### Reproduction steps

1. Open HACS on new UI
2. Click 3 dots
3. Click Custom Repositories
4. Nothing shows

### Screenshots

No screenshot

### Javascript logs from your browser console

```text
DevTools failed to load source map: Could not load content for http://homeassistant.local:8123/frontend_latest/app.95a5b89b.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

### Diagnostics dump

[config_entry-hacs-0f4f5204e07e5cad87150622e7c55994.json.txt](https://github.com/hacs/integration/files/9766060/config_entry-hacs-0f4f5204e07e5cad87150622e7c55994.json.txt)

**Comment by ludeeus** [comment] 2022-10-12 14:51
Duplicate of #2889

**Closed by ludeeus** 2022-10-12 14:51 UTC
Labels: issue:frontend
