### ISSUE TITLE
Safari 16.6.1 Error while loading page entry.

### ISSUE THREAD

**Issue by popeyesfx** [hacs/integration#3439] opened 2024-01-09 16:22 UTC
### Web browser

safari 

### Web browser version

16.6.1

## System Information

version | core-2024.1.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.2.0-39-generic
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4985
Installed Version | 1.33.0
Stage | running
Available Repositories | 1443
Downloaded Repositories | 1
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 8 January 2024, 19:36
-- | --
current_recorder_run | 9 January 2024, 15:51
estimated_db_size | 1.76 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I have researched this issue and it appears to have come up before. I have followed all the recommended fixes, re-installed,cleared cache, restarted machine etc.

No matter what I do I cannot get hacs to show when using safari. If i use google chrome then hacs displays ok. 

### Reproduction steps

1. clear cache
2. ssh into container and install hacs
3. restart container
4.  click on hacs icon in sidebar
...

### Screenshots

![Screenshot 2024-01-09 at 16 13 53](https://github.com/hacs/integration/assets/18743946/0fa8dea1-09ae-43c6-a021-5eae9d018d4f)

### Javascript logs from your browser console

```text
[Error] Error while parsing the 'sandbox' attribute: 'allow-downloads' is an invalid sandbox flag.
	u (app.-v0k7EF2lQg.js:2:130178)
	g (app.-v0k7EF2lQg.js:2:131810)
	_$AI (app.-v0k7EF2lQg.js:2:131287)
	z (app.-v0k7EF2lQg.js:2:134650)
	update (app.-v0k7EF2lQg.js:2:145119)
	performUpdate (app.-v0k7EF2lQg.js:2:143895)
	(anonymous function) (app.-v0k7EF2lQg.js:2:143458)
[Error] Error loading page
	(anonymous function) (main-85e087f9.js:1630:1708)
[Error] WebSocket network error: The operation couldn’t be completed. Connection refused (x3)
[Error] Unhandled Promise Rejection: [object Object] (x12)
[Error] ResizeObserver loop completed with undelivered notifications.
[Error] Error loading page
	(anonymous function) (main-85e087f9.js:1630:1708)
[Error] Error loading page
	(anonymous function) (main-85e087f9.js:1630:1708)
[Error] Error loading page
	(anonymous function) (main-85e087f9.js:1630:1708)
[Error] Error loading page
	(anonymous function) (main-85e087f9.js:1630:1708)
[Error] WebSocket network error: The operation couldn’t be completed. Connection refused (x3)
[Error] Unhandled Promise Rejection: [object Object] (x16)
[Error] Error loading page
	(anonymous function) (main-85e087f9.js:1630:1708)
[Error] Error loading page
	(anonymous function) (main-85e087f9.js:1630:1708)
[Error] Error loading page
	(anonymous function) (main-85e087f9.js:1630:1708)
[Error] Error loading page – "entry" – TypeError: a.translations is not an Object. (evaluating 'e in a.translations')
TypeError: a.translations is not an Object. (evaluating 'e in a.translations')
	(anonymous function) (main-85e087f9.js:1630:1708)
```

### Diagnostics dump

{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2024.1.2",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "6.2.0-39-generic",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "hacs",
    "name": "HACS",
    "codeowners": [
      "@ludeeus"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "websocket_api",
      "frontend",
      "persistent_notification",
      "lovelace",
      "repairs"
    ],
    "documentation": "https://hacs.xyz/docs/configuration/start",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/hacs/integration/issues",
    "requirements": [
      "aiogithubapi>=22.10.1"
    ],
    "version": "1.33.0",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "7f2b45354817f550193f0f2326a1d8e1",
      "version": 1,
      "minor_version": 1,
      "domain": "hacs",
      "title": "",
      "data": {
        "token": "**REDACTED**"
      },
      "options": {
        "sidepanel_title": "HACS",
        "sidepanel_icon": "hacs:hacs",
        "release_limit": 5,
        "appdaemon": true,
        "netdaemon": false,
        "debug": false,
        "experimental": true,
        "country": "GB"
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "hacs": {
      "stage": "running",
      "version": "1.33.0",
      "disabled_reason": null,
      "new": false,
      "startup": false,
      "categories": [
        "theme",
        "template",
        "appdaemon",
        "plugin",
        "integration"
      ],
      "renamed_repositories": {},
      "archived_repositories": [],
      "ignored_repositories": [],
      "lovelace_mode": "storage",
      "configuration": {
        "appdaemon": true,
        "country": "GB",
        "debug": false,
        "dev": false,
        "experimental": true,
        "netdaemon": false,
        "python_script": false,
        "release_limit": 5,
        "theme": false
      }
    },
    "custom_repositories": [],
    "repositories": [
      {
        "data": {
          "archived": false,
          "authors": [
            "@ludeeus"
          ],
          "category": "integration",
          "config_flow": false,
          "default_branch": null,
          "description": "HACS gives you a powerful UI to handle downloads of all your custom needs.",
          "domain": "hacs",
          "downloads": 400291,
          "etag_repository": "W/\"32c77903946bfbc5d23a8bb283af4700ea0aa3a8f6bb3b9523b2be95a882b42e\"",
          "etag_releases": null,
          "file_name": "",
          "first_install": false,
          "full_name": "hacs/integration",
          "hide": false,
          "has_issues": true,
          "id": "172733314",
          "installed_commit": null,
          "installed_version": "1.33.0",
          "installed": true,
          "last_commit": "94e66ed",
          "last_updated": "2024-01-08T06:12:36Z",
          "last_version": "1.33.0",
          "manifest_name": "HACS",
          "new": false,
          "open_issues": 0,
          "published_tags": [],
          "releases": true,
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 4261,
          "topics": [
            "community",
            "package-manager"
          ]
        },
        "integration_manifest": {},
        "repository_manifest": {
          "content_in_root": false,
          "country": [],
          "filename": "hacs.zip",
          "hacs": "0.19.0",
          "hide_default_branch": true,
          "homeassistant": "2023.6.0",
          "manifest": {
            "name": "HACS",
            "zip_release": true,
            "hide_default_branch": true,
            "homeassistant": "2023.6.0",
            "hacs": "0.19.0",
            "filename": "hacs.zip"
          },
          "name": "HACS",
          "persistent_directory": null,
          "render_readme": false,
          "zip_release": true
        },
        "ref": null,
        "paths": {
          "localpath": "/config/custom_components/hacs",
          "local": "/config/custom_components/hacs",
          "remote": "custom_components"
        }
      }
    ],
    "rate_limit": {
      "resources": {
        "core": {
          "limit": 5000,
          "used": 15,
          "remaining": 4985,
          "reset": 1704818591
        },
        "search": {
          "limit": 30,
          "used": 0,
          "remaining": 30,
          "reset": 1704817227
        },
        "graphql": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1704820767
        },
        "integration_manifest": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1704820767
        },
        "source_import": {
          "limit": 100,
          "used": 0,
          "remaining": 100,
          "reset": 1704817227
        },
        "code_scanning_upload": {
          "limit": 1000,
          "used": 0,
          "remaining": 1000,
          "reset": 1704820767
        },
        "actions_runner_registration": {
          "limit": 10000,
          "used": 0,
          "remaining": 10000,
          "reset": 1704820767
        },
        "scim": {
          "limit": 15000,
          "used": 0,
          "remaining": 15000,
          "reset": 1704820767
        }
      },
      "rate": {
        "limit": 5000,
        "used": 15,
        "remaining": 4985,
        "reset": 1704818591
      }
    }
  }
}

**Comment by ludeeus** [comment] 2024-01-09 16:32
The websocket commands are being refused, check your core logs for more details.

**Comment by codyc1515** [comment] 2024-01-09 21:17
Looks like may be a duplicate of #2910 & #2929.

**Comment by Balooski** [comment] 2024-01-12 14:13
Similar issue but with Brave and Edge browsers. I can open a separate issue, but I feel it would be unnecessary.

**Comment by ludeeus** [comment] 2024-01-12 14:32
It was fixed (removed) here <https://github.com/hacs/frontend/pull/647> i assume it will be released later today or sunday.

**Closed by ludeeus** 2024-01-12 14:32 UTC
Labels: issue:frontend

**Comment by ludeeus** [comment] 2024-01-15 06:52
Due to various bugs, I was not able to complete validation, so the release has been delayed.
Potential workarounds: 
- Use a different browser
- Set language to "English" (not any variations of it, just the regular/default US "English")
