### ISSUE TITLE
"Custom repositories" disabled

### ISSUE THREAD

**Issue by brianhanifin** [hacs/integration#2447] opened 2022-01-16 15:48 UTC
## System Health

version | core-2021.12.9
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.88
arch | x86_64
timezone | America/Los_Angeles

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 3945
Installed Version | 1.19.3
Stage | running
Available Repositories | 1008
Downloaded Repositories | 56

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 37

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 16, 2022, 4:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-west-2-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.1
-- | --
update_channel | beta
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 30.8 GB
disk_used | 8.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Portainer (2.0.0), Samba share (9.5.1), HA Scheduler (0.17), ESPHome (2021.12.3), Home Assistant Google Drive Backup (0.105.2), File editor (5.3.3), SDR to Home Assistant (0.1.6b), Terminal & SSH (9.3.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 7
-- | --
resources | 31
views | 52
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

- HACS is mostly functional (I can downgrade HACS from the UI for example).
- "Custom repositories" menu item is currently disabled.
- Possibly related: `sensor.hacs` is reporting `unknown`?

### Reproduction steps

1. Open HACS
2. Click on either Integrations or Frontend.
3. Click the three dots menu.
4. "Custom repositories" is disabled.

### Debug logs

```text
2022-01-16 07:42:58 ERROR (MainThread) [custom_components.hacs] <Integration stokkie90/UI> GitHub returned 404 for https://api.github.com/repos/stokkie90/UI/git/trees/0.1.0-beta
2022-01-16 07:42:58 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 580, in startup_tasks
    await self.recurring_tasks_installed()
  File "/config/custom_components/hacs/base.py", line 678, in recurring_tasks_installed
    await self.handle_critical_repositories()
  File "/config/custom_components/hacs/base.py", line 656, in handle_critical_repositories
    await critical_queue.execute()
  File "/config/custom_components/hacs/utils/queue_manager.py", line 69, in execute
    await asyncio.gather(*local_queue)
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    await function(*args, **kwargs)
  File "/config/custom_components/hacs/repositories/integration.py", line 104, in update_repository
    if not await self.common_update(ignore_issues, force) and not force:
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    await function(*args, **kwargs)
  File "/config/custom_components/hacs/repositories/base.py", line 516, in common_update
    await self.common_update_data(ignore_issues=ignore_issues, force=force)
  File "/config/custom_components/hacs/repositories/base.py", line 991, in common_update_data
    raise HacsException(exception) from None
custom_components.hacs.exceptions.HacsException: GitHub returned 404 for https://api.github.com/repos/stokkie90/UI/git/trees/0.1.0-beta
```

**Comment by brianhanifin** [comment] 2022-01-16 15:50
I looks like the offending item is a theme I added to the custom repositories list.

https://github.com/stokkie90/UI

**Comment by ludeeus** [comment] 2022-01-16 15:51
Duplicate of <https://github.com/hacs/integration/issues/2440>

**Closed by ludeeus** 2022-01-16 15:51 UTC
Labels: issue:backend

**Comment by brianhanifin** [comment] 2022-01-16 16:12
I should have added to Reproduction steps:

5. Downgrade HACS to 1.18.0.
6. Restart Home Assistant.

Custom repositories is still disabled after this.

I have also tried to manually remove that entry from /config/.storage/hacs.repositories but it returns after restart. What else can I do to troubleshoot?

```

        "446496468": {
            "authors": [
                "@stokkie90"
            ],
            "category": "integration",
            "description": "UI-Lovelace-Minimalist is a \"theme\" for HomeAssistant",
            "domain": "ui_lovelace_minimalist",
            "downloads": 0,
            "etag_repository": "W/\"ca0a501db49245893828459d62587bcf1eae63fb3efbb48d360bf7c2484129b3\"",
            "full_name": "stokkie90/UI",
            "first_install": false,
            "installed_commit": "01f29c2",
            "installed": true,
            "last_commit": "3b28575",
            "last_release_tag": "0.1.0-beta",
            "last_updated": "2022-01-12T14:13:16Z",
            "name": "ui_lovelace_minimalist",
            "new": false,
            "repository_manifest": {
                "name": "UI Lovelace Minimalist",
                "render_readme": false,
                "homeassistant": "2021.5.0"
            },
            "selected_tag": null,
            "show_beta": false,
            "stars": 0,
            "topics": [],
            "version_installed": "0.1.0-beta",
            "last_fetched": 1642096732.926289
        },
```

**Comment by brianhanifin** [comment] 2022-01-16 19:24
The solution on #2440 appears to be "downgrade to 1.19.2" then restarting Home Assistant. However this does not fix the problem for me.

How can I troubleshoot this further?

**Comment by ludeeus** [comment] 2022-01-16 22:47
The solution on 2440 was a code change that will be included in the next release.

**Comment by brianhanifin** [comment] 2022-01-16 22:52
OK, that's great!
