### ISSUE TITLE
Custom repository menu don't work

### ISSUE THREAD

**Issue by RadekLorenc** [hacs/integration#2892] opened 2022-10-12 15:21 UTC
## System Information

version | core-2022.10.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.72
arch | x86_64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4754
Installed Version | 1.28.0
Stage | running
Available Repositories | 1187
Downloaded Repositories | 39

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.0
agent_version | 1.4.1
docker_version | 20.10.17
disk_total | 30.8 GB
disk_used | 16.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2022.3.1), Samba share (10.0.0), File editor (5.4.1), Node-RED (13.4.0), Mosquitto broker (6.1.3), Zigbee2MQTT (1.28.0-1), Home Assistant Google Drive Backup (0.108.4), SSH & Web Terminal (12.0.2), ZeroTier One (0.15.1), Network UPS Tools (0.11.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 26
views | 16
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 2 października 2022 15:56
-- | --
current_recorder_run | 11 października 2022 20:49
estimated_db_size | 1102.89 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Żadnego Ale</summary>

can_reach_server | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When trying to add custom repository - pushing the custom repository menu in upper right corner nothing is showing/hapening. 
![obraz_2022-10-12_170402554](https://user-images.githubusercontent.com/85805905/195378875-bfe212c2-6b83-49e2-ab81-64ee3a860fcf.png)

### Reproduction steps

1. Entering HACS
2. Pushing upper right corner three dots
3. Pushing Custom Repository menu button
4. Zero reaction

### Debug logs

```text
2022-10-12 17:06:46.968 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration burze_dzis_net which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-12 17:06:46.971 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-12 17:06:46.972 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-12 17:06:46.974 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-12 17:06:46.976 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tuya_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-12 17:06:46.977 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration zadnego_ale which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-12 17:06:46.978 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hpprinter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-12 17:06:46.980 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pyscript which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-12 17:06:46.982 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration aimp which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-12 17:06:46.984 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration midea_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-12 17:06:46.986 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-12 17:06:46.994 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration miio2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-12 17:06:46.996 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tauron_amiplus which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-12 17:06:47.305 INFO (MainThread) [homeassistant.setup] Setup of domain logger took 0.0 seconds
2022-10-12 17:06:47.311 INFO (MainThread) [homeassistant.setup] Setting up system_log
2022-10-12 17:06:47.313 INFO (MainThread) [homeassistant.setup] Setup of domain system_log took 0.0 seconds
2022-10-12 17:06:47.314 INFO (MainThread) [homeassistant.bootstrap] Setting up frontend: {'frontend'}
2022-10-12 17:06:47.331 INFO (MainThread) [homeassistant.setup] Setting up device_automation
2022-10-12 17:06:47.332 INFO (MainThread) [homeassistant.setup] Setup of domain device_automation took 0.0 seconds
2022-10-12 17:06:47.458 INFO (MainThread) [homeassistant.setup] Setting up lovelace
2022-10-12 17:06:47.465 INFO (MainThread) [homeassistant.setup] Setting up http
2022-10-12 17:06:47.469 INFO (MainThread) [homeassistant.setup] Setup of domain lovelace took 0.0 seconds
2022-10-12 17:06:47.515 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.1 seconds
2022-10-12 17:06:47.527 INFO (MainThread) [homeassistant.setup] Setting up api
2022-10-12 17:06:47.534 INFO (MainThread) [homeassistant.setup] Setup of domain api took 0.0 seconds
2022-10-12 17:06:47.535 INFO (MainThread) [homeassistant.setup] Setting up auth
2022-10-12 17:06:47.539 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.0 seconds
```

### Diagnostics dump

[config_entry-bluetooth-3ee11bf6ec6a31973b4bc5d938515b02.json.txt](https://github.com/hacs/integration/files/9766358/config_entry-bluetooth-3ee11bf6ec6a31973b4bc5d938515b02.json.txt)

**Comment by ludeeus** [comment] 2022-10-12 15:23
Duplicate of #2891

**Closed by ludeeus** 2022-10-12 15:23 UTC
Labels: issue:backend
