### ISSUE TITLE
ljmerza/light-entity-card

### ISSUE THREAD

**Issue by spelech** [hacs/integration#1544] opened 2020-09-22 03:30 UTC
This repo is no longer being maintained. Per the repo's readme
"As of Home Assistant v0.115 all custom elements lazy load which means in order for custom cards to continue to work, they will need to create their own custom elements instead of relying on Home Assistant's built in ones. This has put a lot of burden on maintaining custom cards so I will no longer be maintaining this project."

**Comment by ludeeus** [comment] 2020-09-22 06:48
duplicate of #1536

**Closed by ludeeus** 2020-09-22 06:48 UTC
Labels: flag
