### ISSUE TITLE
Custom repositories is greyed out

### ISSUE THREAD

**Issue by nmsousa76** [hacs/integration#2451] opened 2022-01-18 03:44 UTC
### Web browser

Chrome/Edge

### Web browser version

Version 97.0.4692.71 (Official Build) (64-bit)/ Version 97.0.1072.62 (Official build) (64-bit)

## System Health

version | core-2021.12.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.88
arch | x86_64
timezone | America/New_York

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 3993
Installed Version | 1.19.3
Stage | running
Available Repositories | 1008
Downloaded Repositories | 82

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 109.3 GB
disk_used | 74.6 GB
healthy | true
supported | failed to load: Unsupported
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), CEC Scanner (3.0), File editor (5.3.3), Check Home Assistant configuration (3.9.0), SSH & Web Terminal (9.1.1), Portainer (2.0.0), Terminal & SSH (9.3.0), Mosquitto broker (6.0.1), Node-RED (10.3.3), motionEye (0.16.0), TasmoAdmin (0.16.0), Studio Code Server (3.7.0), AirCast (3.2.1), Home Assistant Google Drive Backup (0.105.2), Frigate NVR (2.3), Zigbee2mqtt (1.22.2-1), Double Take (1.6.0), SQLite Web (3.2.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 8
-- | --
resources | 25
views | 120
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Custom Repositories option is greyed out.   Not sure exactly when this issue started to occur, but I was able to use it a few weeks ago to add custom repos.

[home-assistant.log](https://github.com/hacs/integration/files/7886018/home-assistant.log)

### Reproduction steps

1-  Go to Hacs integration
2- Click on 3 little dots on the upper right hand corner
3- Option for Custom repositories is greyed out

### Screenshots

![image](https://user-images.githubusercontent.com/65356035/149865215-08654e0a-fde2-4590-820c-8b36a27f25a0.png)

### Javascript logs from your browser console

```text
Not sure how to produce these.

I am including the Home assistant logs with debugging for hacs enabled
```

**Comment by ludeeus** [comment] 2022-01-18 07:41
Duplicate of #2440

**Closed by ludeeus** 2022-01-18 07:41 UTC
Labels: issue:frontend

**Comment by pilot1981** [comment] 2022-01-25 10:11
I have the same issue here on 2021.12.10!

**Comment by ludeeus** [comment] 2022-01-25 10:12
The fix for it has not been released yet!
