### ISSUE TITLE
Links within HACS information pages are not clickable

### ISSUE THREAD

**Issue by alandtse** [hacs/integration#1682] opened 2020-11-25 07:43 UTC
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.6.2
| Home Assistant version     | 0.118.3
| Installation method for HA | hassio
| Web browser                | Chrome
| Web browser version        | 86.0.4240.198

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Links within any HACS integration -> Information page are not clickable. Initially reported as to alexa_media. https://github.com/custom-components/alexa_media_player/issues/1012. Looking at the logs it may be related to the HA frontend but I thought I'd at least raise it here.

### Steps to reproduce

1. Open HACS
2. Open Integrations
3. Click on HACS ... menu.
4. Select Information
5. Try to click on any links (e.g., General Documentation)
6. Link is not taken

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

Logs are trying to click on any link.

```
23:38:29.600 frontend-202009091732.js:2027 Uncaught TypeError: Cannot read property 'startsWith' of undefined
    at HTMLElement.value (frontend-202009091732.js:2027)
    at U.handleEvent (frontend-202009091732.js:1)
    at HTMLSpanElement.U.__boundHandleEvent (frontend-202009091732.js:1)
```

</details>

**Comment by ludeeus** [comment] 2020-11-25 09:14
Duplicate of <https://github.com/hacs/integration/issues/1618> fixed in 1.8.0b0

**Closed by ludeeus** 2020-11-25 09:14 UTC
Labels: issue:frontend
