### ISSUE TITLE
None type error attempting updates

### ISSUE THREAD

**Issue by richard-scott** [hacs/integration#2704] opened 2022-05-27 07:16 UTC
### Web browser

Chrome & Safari 

### Web browser version

Unknown

## System Health

version | core-2022.5.5
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.16.0-0.bpo.4-amd64
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4772
Installed Version | 1.25.1
Stage | running
Available Repositories | 1069
Downloaded Repositories | 36

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.3
docker_version | 20.10.14
disk_total | 3647.9 GB
disk_used | 941.4 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | MariaDB (2.4.0), Node-RED (11.1.2), Zigbee2mqtt (1.25.1-1), Nginx Proxy Manager (0.11.0), ESPHome (2022.5.1), Studio Code Server (5.0.4), AppDaemon (0.8.2), Check Home Assistant configuration (3.10.0), Grafana (7.5.2), chrony (2.3.0), motionEye (0.18.0), InfluxDB (4.4.1), Duck DNS (1.14.0), Mosquitto broker (6.1.2), Scrutiny (2ab714f5-ls35), Photoprism (220524-bookworm), phpMyAdmin (0.7.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 20
views | 8
mode | storage

</details>

<details><summary>Sonoff</summary>

version | 3.0.5 (200f243)
-- | --
cloud_online | 1 / 2
local_online | 1 / 1
debug | failed to load: 

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

When attempting to apply updates I get a None Type error and the update fails.

### Reproduction steps

1. Go into HACS
2. Click update any available update

### Screenshots

![AA7D347F-FD4A-48F2-9D4B-9475789AA4DD](https://user-images.githubusercontent.com/5149834/170649962-7bf6be25-2369-45bf-8cc4-c6e09c713c02.png)

### Javascript logs from your browser console

```text
N/a
```

### Diagnostics dump

Doesn’t work on IOS companion app. I will try on a computer later.

**Comment by ludeeus** [comment] 2022-05-27 07:33
Duplicate of https://github.com/hacs/integration/issues/2703

**Closed by ludeeus** 2022-05-27 07:33 UTC
Labels: issue:frontend
