### ISSUE TITLE
White labels in toolbar

### ISSUE THREAD

**Issue by lcavalli** [hacs/integration#2322] opened 2021-12-01 18:07 UTC
### Web browser

Chrome

### Web browser version

96.0.4664.45

## System Health

version | core-2021.11.5
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.63-v7+
arch | armv7l
timezone | Europe/Rome

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.18.0
Stage | running
Available Repositories | 910
Installed Repositories | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 14
views | 7
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

The HACS Integrations and Fronted panel  top toolbar only show the label of selected tab. Labels of unselected tabs are white.
![image](https://user-images.githubusercontent.com/6123641/144288580-8f3717ab-8ca5-4d19-bafd-01458fb44064.png)

The same toolbar in Home Assistant panels shows unselected tabs labels with proper color.

This is the style of HACS unselected tabs labels:
![image](https://user-images.githubusercontent.com/6123641/144288818-fac3b331-0719-4ab0-bb01-ba1cea1ea822.png)

This is the style of Home Assistant unselected tabs labels:
![image](https://user-images.githubusercontent.com/6123641/144288931-ead5ab89-f6e6-4a8a-95d7-a19b0c59ed71.png)

Can it be related to this commit? https://github.com/home-assistant/frontend/commit/6177d2b4163843ec25f5652282db80204f5ee574

### Reproduction steps

1. Navigate to http://<ha-ip>/hacs/integrations

### Screenshots

![image](https://user-images.githubusercontent.com/6123641/144289323-598a02ae-5595-42ba-9660-8b8c30a9c732.png)

### Javascript logs from your browser console

```text
None.
```

**Comment by ludeeus** [comment] 2021-12-01 20:13
Duplicate of https://github.com/hacs/integration/issues/2316

**Closed by ludeeus** 2021-12-01 20:13 UTC
Labels: issue:frontend
