### ISSUE TITLE
Cannot add custom repository in HA 0.110 beta (Cannot read property 'selectedItem' of undefined)

### ISSUE THREAD

**Issue by gadgetchnnel** [hacs/integration#1163] opened 2020-05-17 13:00 UTC
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         | 0.24.5
Home Assistant version         | 0.110.0b3
Installation method for HA    | Python venv
Web browser                         | Google Chrome
Web browser version            | 81.0.4044.138

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.

## Describe the issue

A clear and concise description of what the issue is.

Adding a custom repository is failing with the error "Cannot read property 'selectedItem' of undefined" in the Home Assistant 0.110 beta.

### Steps to reproduce

1. Go to Settings tab in HACS
2. Enter details of custom repository (URL and type)
3. Click Save button

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text
frontend-20200426112021.js:2437 Uncaught TypeError: Cannot read property 'selectedItem' of undefined
    at HTMLElement.Save (frontend-20200426112021.js:2437)
    at T.handleEvent (frontend-20200426112021.js:1)
    at HTMLElement.T.__boundHandleEvent (frontend-20200426112021.js:1)
```

</details>

**Comment by ludeeus** [comment] 2020-05-17 13:02
duplicate of https://github.com/hacs/integration/issues/1143

**Closed by ludeeus** 2020-05-17 13:02 UTC
Labels: issue:frontend
