### ISSUE TITLE
HACS is not updating the "lovelace_resources" file

### ISSUE THREAD

**Issue by denilsonsa** [hacs/integration#1659] opened 2020-11-17 18:34 UTC
Note: After some investigation, I've rewritten this initial post with the latest findings. You can find the original text further below.

## Steps to reproduce

1. Make sure you don't have any `lovelace` entry in your `configuration.yaml`.
    * In other words, that means the default configuration for Lovelace.
    * This also means Lovelace dashboards are configured from the web UI.
    * If you check System Health (at `/config/info`), it will show the *Lovelace mode* as `auto-gen`.
2. Go to `/hacs/frontend`.
3. Click on `+`, search for any card.
4. Install it.
5. Observe it doesn't work. No error message, no warning.
6. Try to reinstall it. Still doesn't work.
7. Alternatively, find an already installed frontend card and uninstall it. Observe Lovelace will still try to load the removed JavaScript file.

No matter what combination of reboots or clearing cache, lovelace resources aren't updated by HACS.

## Reason

[When there is no explicit `lovelace` configuration, Home Assistant will return lovelace mode as `auto-gen`](https://github.com/hacs/integration/issues/1659#issuecomment-729235484), [while behaving like `storage`](https://github.com/home-assistant/core/commit/e2cc1564a0d1427ac10547099a637a8e9b32ddf7).

Before May 2020, HACS would auto-update lovelace resources if the mode was `!== "yaml"`. After May 2020, [HACS behavior was changed to only update lovelace resources if mode was `=== "storage"`](https://github.com/hacs/integration/issues/259e47f0008a78ebe1c84f2bd3543bb67ddde8a6). This was done [to fix some other issues](https://github.com/hacs/integration/issues/1659#issuecomment-729240583).

So, you can consider this issue a REGRESSION.

## Impact

Out-of-the-box, installing front-end modules through HACS is broken/incomplete: After clicking (re)install, a user would expect to have it fully installed and ready to use. However, that's not the case anymore.

On a basic/default/empty lovelace configuration (I believe most users start out like that), HACS will no longer update lovelace resources, leading to frustration, confusion, extra manual work (which kind of defeats the purpose of HACS). This is specially confusing for users updating from an earlier version (when things "just worked") to a later version.

Potentially related issues:

* #1234
* #1508
* #1529
* [*Starting with 1.0.0 it will handle the resources atomagically if you manage those in the UI*](https://community.home-assistant.io/t/moving-from-manual-install-to-hacs-lovelace-custom-cards/198392/8)

## Suggestions

* HACS could update lovelace resources even on `auto-gen` mode.
    * This restores the older HACS behavior, and solves this issue for me.
    * However, this may cause some other issues. I'm curious to know which other issues, and I wonder if they can be solved in a different way.
* HACS could have a [configuration option](https://hacs.xyz/docs/configuration/options#options) to "Update lovelace resources even on auto-gen mode".
* HACS could have a warning message in `/hacs/frontend` whenever lovelace resources and installed repositories get out-of-sync.
    * Similar to <https://hacs.xyz/docs/faq/status_not_loaded>.
    * Such message should have action points:
        * Either a button to fix the issue automatically (i.e. HACS would add/remove items from lovelace resources).
        * Or clear instructions on how to fix it manually. (Either by manually editing the lovelace resources, or by adding a trivial lovelace entry to `configuration.yaml`.)

---

This is the original text from this issue:

## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.6.2 |
| Home Assistant version     | 0.117.6 |
| Installation method for HA | HassOS 4.15 |

Running on a Raspberry Pi. The installation is already several months old, and was "gradually" updated over time. (Well, I skipped a few versions because I forgot to update it for a couple of months; but right now it is up-to-date.)

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Upon (re)installing a frontend component, HACS is not updating the `lovelace_resources` files, and thus the component is never available in the browser.

### Steps to reproduce

1. Go to `/hacs/frontend`.
2. Click on `+`, search for a vacuum card.
3. Install it.
4. Observe it doesn't work, try to reinstall it.

No matter how many times I do it, or if I restart Home Assistant, or if I restart the whole HassOS… The javascript file never gets added to `/config/.storage/lovelace_resources`.

Yes, my lovelace dashboard is custom-built. `fgrep mode /config/.storage/lovelace_dashboards` shows `"mode": "storage"` (twice, because I built two dashboards).

### Some more background info

Weeks ago, I noticed that [`custom-header` component was not available anymore](https://github.com/maykar/custom-header), so I removed it in HACS.

However, upon restarting and observing logs, I noticed messages that Home Assistant was trying to load `custom-header.js`, even though it had been removed through HACS. This was likely the first sign something is wrong. I solved this by manually editing `/config/.storage/lovelace_resources` to remove that item. (Or maybe I asked HACS to reinstall some component, in the belief HACS would regenerate that file from scratch; I don't remember well, it was a while ago.)

Fast-forward to today, and I try to install some vacuum cards through HACS. By looking at the files, I can see those were installed:

```
$ find /config -name '*vacuum*'
/config/www/community/vacuum-card
/config/www/community/vacuum-card/vacuum-card.js.gz
/config/www/community/vacuum-card/vacuum-card.js
/config/www/community/lovelace-xiaomi-vacuum-card
/config/www/community/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
/config/www/community/lovelace-xiaomi-vacuum-card/vacuum.png
/config/www/community/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js.gz
```

However, they are not referenced in `lovelace_resources`, so the frontend doesn't load them, so I can't use them.

<details>
  <summary>Installed frontend components and `lovelace_resources` contents</summary>

```
$ ls -1 /config/www/community/
light-entity-card
lovelace-auto-entities
lovelace-more-info-card
lovelace-multiple-entity-row
lovelace-paper-buttons-row
lovelace-slider-entity-row
lovelace-xiaomi-vacuum-card
mini-graph-card
mini-media-player
rgb-light-card
select-list-card
tv-card
vacuum-card

$ fgrep url /config/.storage/lovelace_resources | sed 's/^\s*//' | sort
"url": "/hacsfiles/custom-header/custom-header.js"
"url": "/hacsfiles/light-entity-card/light-entity-card.js"
"url": "/hacsfiles/lovelace-auto-entities/auto-entities.js"
"url": "/hacsfiles/lovelace-more-info-card/more-info-card.js"
"url": "/hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js"
"url": "/hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js"
"url": "/hacsfiles/lovelace-paper-buttons-row/paper-buttons-row.js"
"url": "/hacsfiles/lovelace-slider-entity-row/slider-entity-row.js"
"url": "/hacsfiles/mini-graph-card/mini-graph-card-bundle.js"
"url": "/hacsfiles/mini-media-player/mini-media-player-bundle.js"
"url": "/hacsfiles/select-list-card/select-list-card.js"

$ cat /config/.storage/lovelace_resources
{
    "version": 1,
    "key": "lovelace_resources",
    "data": {
        "items": [
            {
                "id": "928a1d5600534b639e96a039d6fa4612",
                "type": "module",
                "url": "/hacsfiles/lovelace-slider-entity-row/slider-entity-row.js"
            },
            {
                "id": "37fa1eb9f1e8430091d262f6c668b8c0",
                "type": "module",
                "url": "/hacsfiles/lovelace-paper-buttons-row/paper-buttons-row.js"
            },
            {
                "id": "95d36cf3de4749d88ecb8b9d267e25e7",
                "type": "module",
                "url": "/hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js"
            },
            {
                "id": "b40615860046426b994eaa46db3fcf46",
                "type": "module",
                "url": "/hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js"
            },
            {
                "id": "1cfc152bd7d945b88ee083dd3de17a3c",
                "type": "module",
                "url": "/hacsfiles/light-entity-card/light-entity-card.js"
            },
            {
                "id": "d4b90110dea749daa02ced43f1984796",
                "type": "module",
                "url": "/hacsfiles/mini-media-player/mini-media-player-bundle.js"
            },
            {
                "id": "4e110c7cf0824d67aeff8e389d445372",
                "type": "module",
                "url": "/hacsfiles/lovelace-auto-entities/auto-entities.js"
            },
            {
                "id": "2b5f9caea6774e62ba58b1ab8a988ddf",
                "type": "module",
                "url": "/hacsfiles/mini-graph-card/mini-graph-card-bundle.js"
            },
            {
                "id": "3359b5f383cd4398b07aa7376f3b9cff",
                "type": "module",
                "url": "/hacsfiles/lovelace-more-info-card/more-info-card.js"
            },
            {
                "id": "8bfe539e305f4123a64fced5e4713f79",
                "type": "module",
                "url": "/hacsfiles/select-list-card/select-list-card.js"
            },
            {
                "id": "3102bdc061c047a493efe6698ec8d223",
                "type": "module",
                "url": "/hacsfiles/custom-header/custom-header.js"
            }
        ]
    }
}
```

</details>

Now that I pay enough attention, I can see `lovelace_resources` is still referencing the outdated (and removed) `custom-header.js`, is referencing `multiple-entity-row.js` twice, and is not referencing a few other components. So, **somehow it got completely out-of-sync with the installed components**. And I don't know why.

I've also read <https://hacs.xyz/docs/faq/status_not_loaded>, but I don't see any "Not Loaded" message, and I've already tried the *Reinstall* trick. Also, I don't know which YAML configuration file that page is talking about. Also also, I don't think my lovelace is using any yaml file (`fgrep lovelace /config/*.yaml` returns empty).

## Debug logs

JavaScript console is mostly empty (except for warning messages about animations, those are unrelated to this issue).

Backend logs were captured using:

    ha core logs | fgrep hacs > logs.txt

<details>
  <summary>Logs</summary>

```

2020-11-17 19:00:15 DEBUG (MainThread) [custom_components.hacs.data] Saving data
2020-11-17 19:00:33 DEBUG (MainThread) [custom_components.hacs.api.repository_data] Running install for denysdovhan/vacuum-card
2020-11-17 19:00:33 DEBUG (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Getting repository information
2020-11-17 19:00:33 DEBUG (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Running checks against v1.12.0
2020-11-17 19:00:34 INFO (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Running pre installation steps
2020-11-17 19:00:34 INFO (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Pre installation steps completed
2020-11-17 19:00:34 INFO (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Running installation steps
2020-11-17 19:00:34 DEBUG (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Getting repository information
2020-11-17 19:00:35 DEBUG (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Running checks against v1.12.0
2020-11-17 19:00:36 DEBUG (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] vacuum-card.js
2020-11-17 19:00:36 DEBUG (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Downloading vacuum-card.js
2020-11-17 19:00:36 DEBUG (MainThread) [custom_components.hacs.async_download_file] Downloading https://github.com/denysdovhan/vacuum-card/releases/download/v1.12.0/vacuum-card.js
2020-11-17 19:00:37 DEBUG (MainThread) [custom_components.hacs.download.save] Saving /config/www/community/vacuum-card/vacuum-card.js
2020-11-17 19:00:37 INFO (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Download of vacuum-card.js completed
2020-11-17 19:00:37 INFO (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Installation steps completed
2020-11-17 19:00:37 INFO (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Running post installation steps
2020-11-17 19:00:37 INFO (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Post installation steps completed
2020-11-17 19:00:37 DEBUG (MainThread) [custom_components.hacs.data] Saving data
2020-11-17 19:02:28 DEBUG (MainThread) [custom_components.hacs.web.category] Serving lovelace-slider-entity-row/slider-entity-row.js from /config/www/community/lovelace-slider-entity-row/slider-entity-row.js.gz
2020-11-17 19:02:28 DEBUG (MainThread) [custom_components.hacs.web.category] Serving lovelace-paper-buttons-row/paper-buttons-row.js from /config/www/community/lovelace-paper-buttons-row/paper-buttons-row.js.gz
2020-11-17 19:02:28 DEBUG (MainThread) [custom_components.hacs.web.category] Serving lovelace-multiple-entity-row/multiple-entity-row.js from /config/www/community/lovelace-multiple-entity-row/multiple-entity-row.js.gz
2020-11-17 19:02:28 DEBUG (MainThread) [custom_components.hacs.web.category] Serving lovelace-auto-entities/auto-entities.js from /config/www/community/lovelace-auto-entities/auto-entities.js.gz
2020-11-17 19:02:28 DEBUG (MainThread) [custom_components.hacs.web.category] Serving mini-media-player/mini-media-player-bundle.js from /config/www/community/mini-media-player/mini-media-player-bundle.js.gz
2020-11-17 19:02:28 DEBUG (MainThread) [custom_components.hacs.web.category] Serving light-entity-card/light-entity-card.js from /config/www/community/light-entity-card/light-entity-card.js.gz
2020-11-17 19:02:28 DEBUG (MainThread) [custom_components.hacs.web.category] Serving mini-graph-card/mini-graph-card-bundle.js from /config/www/community/mini-graph-card/mini-graph-card-bundle.js.gz
2020-11-17 19:02:28 DEBUG (MainThread) [custom_components.hacs.web.category] Serving lovelace-more-info-card/more-info-card.js from /config/www/community/lovelace-more-info-card/more-info-card.js.gz
2020-11-17 19:02:28 DEBUG (MainThread) [custom_components.hacs.web.category] Serving select-list-card/select-list-card.js from /config/www/community/select-list-card/select-list-card.js.gz
2020-11-17 19:02:28 ERROR (MainThread) [custom_components.hacs.web.category] Tried to serve up '/config/www/community/custom-header/custom-header.js' but it does not exist
2020-11-17 19:09:15 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2020-11-17 19:09:23 DEBUG (MainThread) [custom_components.hacs.api.repository] Running uninstall for denysdovhan/vacuum-card
2020-11-17 19:09:23 DEBUG (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Getting repository information
2020-11-17 19:09:23 DEBUG (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Running checks against v1.12.0
2020-11-17 19:09:24 INFO (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Uninstalling
2020-11-17 19:09:24 DEBUG (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Removing /config/www/community/vacuum-card
2020-11-17 19:09:24 DEBUG (MainThread) [custom_components.hacs.data] Saving data
2020-11-17 19:09:45 DEBUG (MainThread) [custom_components.hacs.api.repository_data] Running install for denysdovhan/vacuum-card
2020-11-17 19:09:45 DEBUG (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Getting repository information
2020-11-17 19:09:45 DEBUG (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Running checks against v1.12.0
2020-11-17 19:09:46 INFO (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Running pre installation steps
2020-11-17 19:09:46 INFO (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Pre installation steps completed
2020-11-17 19:09:46 INFO (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Running installation steps
2020-11-17 19:09:46 DEBUG (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Getting repository information
2020-11-17 19:09:47 DEBUG (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Running checks against v1.12.0
2020-11-17 19:09:47 DEBUG (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] vacuum-card.js
2020-11-17 19:09:47 DEBUG (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Downloading vacuum-card.js
2020-11-17 19:09:47 DEBUG (MainThread) [custom_components.hacs.async_download_file] Downloading https://github.com/denysdovhan/vacuum-card/releases/download/v1.12.0/vacuum-card.js
2020-11-17 19:09:48 DEBUG (MainThread) [custom_components.hacs.download.save] Saving /config/www/community/vacuum-card/vacuum-card.js
2020-11-17 19:09:48 INFO (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Download of vacuum-card.js completed
2020-11-17 19:09:48 INFO (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Installation steps completed
2020-11-17 19:09:48 INFO (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Running post installation steps
2020-11-17 19:09:48 INFO (MainThread) [custom_components.hacs.repository.plugin.denysdovhan.vacuum-card] Post installation steps completed
2020-11-17 19:09:48 DEBUG (MainThread) [custom_components.hacs.data] Saving data

```

</details>

**Comment by ludeeus** [comment] 2020-11-17 19:18
It's the frontend that does this, can you add the javascript logs from browser console when you r install/reinstall?

**Comment by denilsonsa** [comment] 2020-11-17 19:32
As I mentioned… *JavaScript console is mostly empty (except for warning messages about animations, those are unrelated to this issue).* Here's the full browser console when I click on "Reinstall" on the `/hacs/frontend` page:

<details>
<summary>JavaScript console</summary>

![JavaScript console](https://user-images.githubusercontent.com/121676/99438074-98d2c780-2913-11eb-9531-2419a9c9a0bd.png)

</details>

Yes, that's all.

**Comment by ludeeus** [comment] 2020-11-17 19:34
ah. they are not printed unless you enable debug mode in HACS.
https://hacs.xyz/docs/configuration/options#options

**Comment by denilsonsa** [comment] 2020-11-17 19:40
I've checked *Enable debug.*, as per [this image](https://hacs.xyz/assets/images/option3-8c6b99d6fd6c83ad9edf4164b0114d6b.png), clicked *Submit* and waited for the confirmation. Then I hard-refreshed the `/hacs/frontend` page and tried to reinstall the vacuum card again. Exactly the same behavior, nothing relevant in the browser logs.

Are you sure this isn't related to HACS backend? After all, HACS has to update some lovelace file somewhere in the backend.

**Comment by ludeeus** [comment] 2020-11-17 19:59
What bowrser do you use?

Yes I'm sure, the backend does not know how to do it, the frontend uses HA's websocket API to make HA update the entries.

**Comment by denilsonsa** [comment] 2020-11-17 20:03
Google Chrome ~~86.0.4240.198 (the latest stable)~~ 87.0.4280.66 (the latest stable as of today)

**Comment by denilsonsa** [comment] 2020-11-17 20:52
I've restarted Home Assistant (but haven't rebooted the host). Same behavior.
Trying the same on Firefox 83.0, I get plenty of animation warnings, and finally I got these two lines:

```
21:45:15.839 [HACS:_installRepository] plugin frontend-202009091732.js:30554:15
21:45:15.843 [HACS:_installRepository] auto-gen frontend-202009091732.js:30554:15
```

Still, same behavior. I'm starting to wonder if `hacs.status.lovelace_mode` is actually `storage`. Any easy way to check for that?

**Comment by ludeeus** [comment] 2020-11-17 20:54
Those logs tell that it's not `storage` ;) 
`auto-gen` is one of 3 modes (auto-gen, yaml, storage)

**Comment by denilsonsa** [comment] 2020-11-17 21:04
I've figured out why the logs were hidden in Chrome!
![Log levels](https://user-images.githubusercontent.com/121676/99449200-fff67900-291f-11eb-8a69-8efaee446565.png)

Well, if lovelace has 3 modes, I assume this "bug" was introduced 4 months ago: https://github.com/hacs/frontend/commit/259e47f0008a78ebe1c84f2bd3543bb67ddde8a6#diff-bfc18155eafa36be1fb8084301678a56684e3a051294470ce871ecbfe17f9255R118

I still don't understand those modes, and I understand less because I know HACS used to work fine (maybe 6 months ago), and now the lovelace resources are not updated anymore.

**Comment by ludeeus** [comment] 2020-11-17 21:24
Huh! I thought all levels was active by default, I must have changed that sometime in the past on my clients.

Yeah, there is your issue, why I'm not sure of, but HACS trust the info given by HA, and will not try to change resources if you are not in `storage` mode, how you are able to have 11 resources and 3 dashboards with "auto-mode" I'm not sure about, but that is your issue, as long as HA says it's "auto-gen" HACS will not try to change anything.

**Comment by denilsonsa** [comment] 2020-11-17 21:51
Probably because I started using Home Assistant in May 2020, probably version 0.109; and back then HACS only had two lovelace modes. So, since the mode was `!== "yaml"`, HACS helpfully edited the resources for me. Then [in July there was a commit that changed the HACS behavior](259e47f0008a78ebe1c84f2bd3543bb67ddde8a6). Once I finally updated both Home Assistant and HACS, I started having trouble with lovelace resources.

After searching the codebase, I found something interesting… [The `auto-gen` mode is actually the "storage mode but without any config"](https://github.com/home-assistant/core/blob/1477087c71a027e59b6bd9dcc0ba51cd3a314eda/homeassistant/components/lovelace/dashboard.py#L109):

        if self._data["config"] is None:
            return {"mode": "auto-gen"}

I still don't understand what `"config"` is in that context, or even if there is any real difference between `auto-gen` and `storage` (after all, both come from the same class). I'm assuming the empty `config` is due to no `lovelace` entry in `configuration.yaml`; and then it defaults to `storage`. (One can also [explicitly set lovelace to `storage`](https://www.home-assistant.io/lovelace/dashboards-and-views#mode) in the configuration; observe there is no `auto-gen` value in the configuration documentation.)

My short-sighted suggestion is to update HACS to update resources on both `auto-gen` and `storage` modes. My better suggestion is to ask HA Lovelace developers to understand those modes, and then update HACS as needed. :)

**Comment by ludeeus** [comment] 2020-11-17 22:02
`storage` is needed for HACS, that's why it was changed ;)
There were reports both in this repo, and in HA repos that were caused by HACS changing resources when in auto-gen.

So that can not change back, the long-term (and proper) solution here will be for you to have your HA not report `auto-gen`, but `storage` as you clearly are using that.

**Comment by denilsonsa** [comment] 2020-11-18 10:00
FTR, I've just updated the text from the issue description, based on the latest findings and comments. This will reduce the noise and make it easier for other people to understand this issue. Feel free to mark the middle comments as "off-topic" or something, just to hide them by default.

**Comment by topfs2** [comment] 2020-11-30 21:41
Did you get this one working? Should it be enough to change storage mode in the configuration.yaml?

I've changed the configuration.yaml to contain

    lovelace
      mode: storage

but my old (ui generated) ones does not get resources added to them, I even tried wiping my .storage folder from all the lovelace stuff but new resources are still not added by HACS?

In the attached log I'm reinstalling simple weather card after I've changed to storage mode and all lovelace stuff removed from .storage (as much of a clean slate I can muster on a long running setup I reckon?)

The log is greped home-assistant.log for hacs (is that correct?)

**Comment by denilsonsa** [comment] 2020-12-01 16:53
My current workaround is to manually add resources using Lovelace configuration UI.

Also, regarding logs, you should try getting logs from the developer tools inside your browser. First [enable debug in HACS](https://hacs.xyz/assets/images/option3-8c6b99d6fd6c83ad9edf4164b0114d6b.png), then open the browser JavaScript console, and [make sure all log messages are visible](https://github.com/hacs/integration/issues/1659#issuecomment-729212740). You can also double-check [the lovelace mode in `/config/info`](https://user-images.githubusercontent.com/121676/99451376-67152d00-2922-11eb-8570-d7cf2464b55f.png).

**Comment by dkebler** [comment] 2020-12-06 22:28
My HACS install started doing the same with upgrade to 118.4.  So for grins I scrubbed and reinstalled HACS from scratch, then removed and installed a frontend repo and still there are no automated import of resources in lovelace.  I have three HAs running on three boxes and it's all the same deal.  I am running the very latest HA (118.4) and HACS.  

I have tried with no lovelace: entry in my config and 
```
lovelace:
  mode: storage
  dashboards: !include lovelace/dashboards.yaml
```
with no love.  Mode always says "auto-gen" and no resources are added.

Not quite grokking why this is marked "Issue not in HACS".  if HA changed to this auto-gen mode then HACS has to abide to this apparently breaking change to function.  Maybe this will all be resolved when HA 1.0 is out (and corresponding HACS)? In the meantime I am stuck with @denilsonsa workaround.

**Comment by dkebler** [comment] 2020-12-07 01:49
hmm... even the workaround is not working.  I add the url manually to resources and still the card is not available in the dashboard editor add card modal. :(

**Comment by ludeeus** [comment] 2021-01-31 11:42
Fixed in HA 2020.2.0 which is currently in beta

**Closed by ludeeus** 2021-01-31 11:42 UTC
Labels: Issue not in HACS

**Comment by ranrinc** [comment] 2021-07-05 10:42
This problem seems to be back on the latest HA + HACS

**Comment by bmcgonag** [comment] 2021-07-12 15:31
I am also seeing this issue (I believe) in Home Assistant 20.21.7.   I try to install a HACS frontend car, it acts like ti installs, tells me to reload, I even reboot HA (host and all), and still no access to this card.
