### ISSUE TITLE
Performance of CPU is still growing up because of updating github repositories 

### ISSUE THREAD

**Issue by romd87** [hacs/integration#1902] opened 2021-02-13 01:27 UTC
## System Health details
version | core-2021.2.3
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 4.19.0-14-amd64
arch | x86_64
timezone | Europe/Bratislava

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4914
Installed Version | 1.11.2
Stage | running
Available Repositories | 758
Installed Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 1, 2018, 1:00 AM
relayer_connected | false
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.02.9
docker_version | 20.10.3
disk_total | 227.3 GB
disk_used | 9.8 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0), Terminal & SSH (9.0.1), AdGuard Home (3.0.0), Node-RED (8.1.1), Samba share (9.3.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 9
views | 10
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

## Checklist
- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

my HomeAssistant is installed on laptop Lenovo G550 (Intel® Core™2 Duo Processor T9300, 5GB RAM, 250GB SSD).

I have installed Cockpit for monitoring system. And I see, CPU is constantly growing up. I tried to restart HA Core and then everything is OK, but after many hours, performance of CPU is again growing up, see attachments. Also on second printscreen is visible, that HA Core eating around 50% of CPU. All the time I have only started HA and I do nothing.

**HA Core usage before restart**
<img width="1014" alt="106358402-2b2c1a00-630c-11eb-95e4-d54cf694ac5e" src="https://user-images.githubusercontent.com/75281334/107837609-0753e400-6da2-11eb-99aa-31e64b3be05d.png">

**HA Core usage after restart**
<img width="1018" alt="106358458-a4c40800-630c-11eb-8bba-3214d4d82237" src="https://user-images.githubusercontent.com/75281334/107837615-0fac1f00-6da2-11eb-9de6-05f043fac237.png">

**Cockpit monitoring system**
<img width="1020" alt="106358413-33845500-630c-11eb-8530-7224150df63d" src="https://user-images.githubusercontent.com/75281334/107837623-176bc380-6da2-11eb-8c48-db8189b069bd.png">

**There is callgrind file from Profiler**
[callgrind.out.1613168986920807.zip](https://github.com/hacs/integration/files/5974919/callgrind.out.1613168986920807.zip)

**HACS version (the newest version):**

Integration version: | 1.11.3
-- | --
Frontend version: | 20210214110032
Repositories: | 758
Installed repositories: | 9

**Issue was first resported on HomeAssistant core:**
https://github.com/home-assistant/core/issues/45742 

### Steps to reproduce

1. Run HA
2. Wait for 5-6 hours
3. Check CPU usage

## Debug logs

<details>
  <summary>Logs</summary>

```
[home-assistant.log.zip](https://github.com/hacs/integration/files/5995330/home-assistant.log.zip)
```

</details>

**Comment by ludeeus** [comment] 2021-02-13 12:05
This issue does not follow any issue template, please adjust that.
And this is from my installation (ODROID-N2+) which for the most part only have HACS and nothing else
![image](https://user-images.githubusercontent.com/15093472/107849519-0780cd80-6dfc-11eb-8f49-589a8c70cdd2.png)
over 24h since last restart, which makes me wonder if those numbers only are a symptom and not the issue.

**Comment by romd87** [comment] 2021-02-17 11:40
Ok, sorry for this, I edited it according template.

**Comment by ludeeus** [comment] 2021-02-18 10:05
Your database is broken, which could certainly cause a spike in usage everywhere else.
As I'm not able to reproduce this, and the fact that you have other issues, I'm closing this issue.

This is what we tell users on Discord to do, should help you as well:
![image](https://user-images.githubusercontent.com/15093472/108340611-12ab7300-71d9-11eb-865a-e8833e3f75c1.png)

**Closed by ludeeus** 2021-02-18 10:05 UTC
Labels: Missing required issue information

**Comment by romd87** [comment] 2021-02-19 09:15
So I deleted database file and after restart HA everything is withou problem, CPU has constant performance. Thanks.
