### ISSUE TITLE
HACS will not start on fresh install of HA 1.0.0b2

### ISSUE THREAD

**Issue by tehbra1n** [hacs/integration#1711] opened 2020-12-08 14:07 UTC
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.8.0
| Home Assistant version     | 1.0.0b2
| Installation method for HA | python venv

## Checklist

- [ X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X ] I have enabled debug logging for my installation.
- [ X] I have filled out the issue template to the best of my ability.
- [X ] I have read <https://hacs.xyz/docs/issues>
- [X ] This issue is related to the backend of HACS.
- [ X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

HACS will not start on a fresh install of 1.0.0b2.  This is a completely new instance of HA.  The HACS menu appears in the sidebar, and the for the last 12 hours the "Information" section in HACS says "HACS is setting up  HACS is setting up, during this time some information might be missing or incorrect"  hacs.zip was unzipped in ~/.homeassistant/custom_components/hacs as the homeassistant user so all files are owned by that user/group.
### Steps to reproduce

1.  Install HA 1.0.0b2
2.  Install HACS following instructions for python venv
3.  Restart HA

## Debug logs

<details>
  <summary>Logs</summary>

```

Dec 08 13:57:41 bolt hass[15788]: 2020-12-08 13:57:41 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
Dec 08 13:57:42 bolt hass[15788]: 2020-12-08 13:57:42 DEBUG (MainThread) [custom_components.hacs] Configuration type: flow
Dec 08 13:57:42 bolt hass[15788]: 2020-12-08 13:57:42 INFO (MainThread) [custom_components.hacs]
Dec 08 13:57:42 bolt hass[15788]: -------------------------------------------------------------------
Dec 08 13:57:42 bolt hass[15788]: HACS (Home Assistant Community Store)
Dec 08 13:57:42 bolt hass[15788]: Version: 1.8.0
Dec 08 13:57:42 bolt hass[15788]: This is a custom integration
Dec 08 13:57:42 bolt hass[15788]: If you have any issues with this you need to open an issue here:
Dec 08 13:57:42 bolt hass[15788]: https://github.com/hacs/integration/issues
Dec 08 13:57:42 bolt hass[15788]: -------------------------------------------------------------------
Dec 08 13:57:42 bolt hass[15788]: 2020-12-08 13:57:42 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.WEBSOCKET
Dec 08 13:57:42 bolt hass[15788]: 2020-12-08 13:57:42 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.FRONTEND
Dec 08 13:57:42 bolt hass[15788]: 2020-12-08 13:57:42 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.CATEGORIES
Dec 08 13:57:43 bolt hass[15788]: 2020-12-08 13:57:43 DEBUG (MainThread) [custom_components.hacs] Can update 262 repositories
Dec 08 13:57:43 bolt hass[15788]: 2020-12-08 13:57:43 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.HACS_REPO
Dec 08 13:57:43 bolt hass[15788]: 2020-12-08 13:57:43 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Checking repository.
Dec 08 13:57:43 bolt hass[15788]: 2020-12-08 13:57:43 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Running checks against 1.8.0
Dec 08 13:57:43 bolt hass[15788]: 2020-12-08 13:57:43 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> All (0) checks passed
Dec 08 13:57:43 bolt hass[15788]: 2020-12-08 13:57:43 INFO (MainThread) [custom_components.hacs] <Integration hacs/integration> Registration completed
Dec 08 13:57:44 bolt hass[15788]: 2020-12-08 13:57:44 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for hacs
Dec 08 13:57:44 bolt hass[15788]: Traceback (most recent call last):
Dec 08 13:57:44 bolt hass[15788]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/config_entries.py", line 236, in async_setup
Dec 08 13:57:44 bolt hass[15788]:     result = await component.async_setup_entry(hass, self)  # type: ignore
Dec 08 13:57:44 bolt hass[15788]:   File "/home/homeassistant/.homeassistant/custom_components/hacs/__init__.py", line 30, in async_setup_entry
Dec 08 13:57:44 bolt hass[15788]:     return await hacs_ui_setup(hass, config_entry)
Dec 08 13:57:44 bolt hass[15788]:   File "/home/homeassistant/.homeassistant/custom_components/hacs/operational/setup.py", line 67, in async_setup_entry
Dec 08 13:57:44 bolt hass[15788]:     return await async_startup_wrapper_for_config_entry()
Dec 08 13:57:44 bolt hass[15788]:   File "/home/homeassistant/.homeassistant/custom_components/hacs/operational/setup.py", line 92, in async_startup_wrapper_for_config_entry
Dec 08 13:57:44 bolt hass[15788]:     startup_result = await async_hacs_startup()
Dec 08 13:57:44 bolt hass[15788]:   File "/home/homeassistant/.homeassistant/custom_components/hacs/operational/setup.py", line 197, in async_hacs_startup
Dec 08 13:57:44 bolt hass[15788]:     async_call_later(hacs.hass, 5, hacs.startup_tasks())
Dec 08 13:57:44 bolt hass[15788]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/event.py", line 1179, in async_call_later
Dec 08 13:57:44 bolt hass[15788]:     return async_track_point_in_utc_time(
Dec 08 13:57:44 bolt hass[15788]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/event.py", line 1133, in async_track_point_in_utc_time
Dec 08 13:57:44 bolt hass[15788]:     job = action if isinstance(action, HassJob) else HassJob(action)
Dec 08 13:57:44 bolt hass[15788]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 174, in __init__
Dec 08 13:57:44 bolt hass[15788]:     raise ValueError("Coroutine not allowed to be passed to HassJob")
Dec 08 13:57:44 bolt hass[15788]: ValueError: Coroutine not allowed to be passed to HassJob

```

</details>

**Comment by ludeeus** [comment] 2020-12-08 14:14
Duplicate of https://github.com/hacs/integration/issues/1693

**Closed by ludeeus** 2020-12-08 14:14 UTC
Labels: issue:backend
