### ISSUE TITLE
Can't add 3rd party repo in settings

### ISSUE THREAD

**Issue by stphndrnd** [hacs/integration#905] opened 2019-12-30 15:58 UTC
Using the latest release and it seems like there is an issue. In the settings part when one click on the add repository the cursor shift focus all the time and reset the value erasing the repo address and category making it impossible to add any additional repos. Is this a know issue?

I tried on Chrome, Safari and mobile Chrome. All the same issue. Incognito mode or not (to eliminate the possible cache or cookies issues).

**Comment by ludeeus** [comment] 2019-12-30 16:38
Duplicate of  https://github.com/hacs/frontend/issues/58

**Closed by ludeeus** 2019-12-30 16:38 UTC
