### ISSUE TITLE
In the Pending restart popup the Navigate link does not work

### ISSUE THREAD

**Issue by Zylazy** [hacs/integration#2659] opened 2022-05-06 08:59 UTC
### Describe the issue

After running updates in HACS and you get the Pending restart popup, the Navigate link is pointed to /config/server_control page, however it has changed in 2022.5.
It should be /developer-tools/yaml

### Link to action run

-

### Link to action configuration

-

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment] 2022-05-06 09:00
hit F5
duplicate of #2657

**Closed by ludeeus** 2022-05-06 09:00 UTC
