### ISSUE TITLE
integration not possible

### ISSUE THREAD

**Issue by dzsioin** [hacs/integration#1111] opened 2020-05-01 14:26 UTC
Hello everyone, I have configured HACS according to the instructions from HACS.xyz, but if I want to integrate it, the message "Please wait while the integration is being installed" appears permanently
Home assistant has been completely redesigned with the image from the official website.

  | aarch64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.19.114-v8
python_version | 3.7.7
timezone | Europe/Berlin
version | 0.109.2
virtualenv | false

nothing in the log with HACS
![Unbenannt](https://user-images.githubusercontent.com/64641502/80812881-25f93d80-8bc9-11ea-8bd0-2470032101ed.jpg)

**Comment by ludeeus** [comment] 2020-05-01 15:04
It's trying to install stuff.
This is not an issue with HACS, since HACS has not started yet.
Let it sit for a while, if it stops, check your logs.
Since this is not a bug, I close it.
You can join discord if you need help with your logs.

**Closed by ludeeus** 2020-05-01 15:04 UTC

**Comment by dzsioin** [comment] 2020-05-01 15:09
what is discord???

**Comment by ludeeus** [comment] 2020-05-01 15:12
https://hacs.xyz/help
