### ISSUE TITLE
Request for removal of ardevd/ha-bobcatminer

### ISSUE THREAD

**Issue by HillBullishBoy** [hacs/integration#3308] opened 2023-10-18 12:43 UTC
### Repository

ardevd/ha-bobcatminer

### Checklist

- [X] I understand that this form should only be used for repositories that needs to be removed from HACS
- [X] I understand that a bug is not reason enough to have a repository removed
- [X] The repository is currently shipped as a default repository in HACS
- [X] I have tried to get the authors attention to the reason for removal

### Why should this be removed?

The addon does not work anymore. There is no response to bug reports. The project seems to be abandoned.

### Link to issue

https://github.com/ardevd/ha-bobcatminer/issues

**Comment by ctec76** [comment] 2023-10-19 19:16
Hi, I can confirm that Ecoflow changed their API (quite annoying), and I would support removing this HACS addon because it is no longer working.
Supposedly, there are still ways to read out information from the Ecoflow devices, which involve getting individual API keys by contacting Ecoflow support.
I cannot confirm this works; I just read in certain forums that some people had success with this.
All in all, the possibilities to communicate with the Ecoflow devices within the local network are extremely disappointing.
Not to mention Wi-Fi connection issues in general with Ecoflow devices.

**Comment by ludeeus** [comment] 2023-10-22 08:21
Looking at your issue (<https://github.com/ardevd/ha-bobcatminer/issues/27>), it contains _nothing_ to go on.
Try resolving this with the author by providing more context before having it removed.

**Closed by ludeeus** 2023-10-22 08:21 UTC
Labels: flag
