### ISSUE TITLE
Uncaught exceptions on connection attempt

### ISSUE THREAD

**Issue by kevinkk525** [hacs/integration#941] opened 2020-01-24 19:30 UTC
## Version of HACS

0.20.8

## Describe the bug
Somehow my whole Home-Assistant instance had no internet connection anymore (although everything else did and even the bash from within the home-assistant docker did) and this is what showed up in my log. Not sure if it's a bug, if that exception should be caught or can just be ignored.

## Debug log

```text
2020-01-24 18:59:27 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiogithubapi/aiogithub.py", line 144, in get_ratelimit
    response = await self.session.get(url, headers=headers)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 985, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1013, in _create_connection_transport
    await waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 304, in recuring_tasks_installed
    await self.factory.execute()
  File "/config/custom_components/hacs/hacsbase/task_factory.py", line 24, in execute
    await asyncio.gather(*self.tasks)
  File "/config/custom_components/hacs/hacsbase/task_factory.py", line 45, in safe_update
    await repository.update_repository()
  File "/config/custom_components/hacs/repositories/integration.py", line 96, in update_repository
    await self.common_update()
  File "/config/custom_components/hacs/repositories/repository.py", line 347, in common_update
    self.repository_object = await self.github.get_repo(self.information.full_name)
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/aiogithubapi/aiogithub.py", line 51, in get_repo
    await self.get_ratelimit()
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/aiogithubapi/aiogithub.py", line 159, in get_ratelimit
    self.ratelimits.core.reset = int(response.headers["X-RateLimit-Reset"])
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
2020-01-24 18:59:35 ERROR (MainThread) [backoff] Giving up get_ratelimit(...) after 5 tries (concurrent.futures._base.TimeoutError)
2020-01-24 18:59:35 ERROR (MainThread) [backoff] Giving up get_repo(...) after 5 tries (concurrent.futures._base.TimeoutError)


A bit later (might be unrelated?):

2020-01-24 19:26:44 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 304, in recuring_tasks_installed
    await self.factory.execute()
  File "/config/custom_components/hacs/hacsbase/task_factory.py", line 24, in execute
    await asyncio.gather(*self.tasks)
RuntimeError: cannot reuse already awaited coroutine

```

**Comment by ludeeus** [comment] 2020-01-26 10:16
Duplicate of #927

**Closed** 2020-01-26 10:17 UTC

**Comment by kevinkk525** [comment] 2020-01-26 11:28
Ah yes the 2nd error message is a duplicate but what about the ones before? They don't seem connected.
