### ISSUE TITLE
buttons for frontend/integrations don't appear on the UI

### ISSUE THREAD

**Issue by gizbod** [hacs/integration#2130] opened 2021-08-07 20:34 UTC
### Web browser

Safari

### Web browser version

14.0.3

## System Health

version | core-2021.8.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.53
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4854
Installed Version | 1.13.2
Stage | running
Available Repositories | 839
Installed Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 22 August 2021, 1:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.2
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 30.8 GB
disk_used | 12.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Hass.io Google Drive Backup (0.100.0), Check Home Assistant configuration (3.8.0), File editor (5.3.3), Terminal & SSH (9.1.3), deCONZ (6.9.0), Node-RED (9.2.1), Z-Wave JS (0.1.21)

</details>

<details><summary>Lovelace</summary>

dashboards | 5
-- | --
resources | 10
views | 28
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

HACS no longer shows a button for integrations or frontend etc. 
All i now see is button for add ons and about.

this happened after updating to 2021.6, nothing has changed with any subsequent updates.

I have remove HACS as per the instructions and reinstalled it.
The buttons then reappear for a short time. In this time I can install custom components, so I installed a few (so they show in HACS) Then I get the rate limit issue stopping HACS from working temporarily. This rate limit issue doesn't seem to clear for several hours and will only do so once HA is restarted. Following the restart, the buttons no longer appear

worth saying, this happens on all browsers and mobile apps.

### Reproduction steps

1. Remove HACS as per published guide
2. Reinstall HACS as per instructions 
3. Wait a couple hours for rate limit to disappear
4. Restart HA as rate limit doesn't disappear
5. No buttons
...

### Screenshots

![HACSscreenshot](https://user-images.githubusercontent.com/18351060/128613190-671ad7d8-f052-4a8a-97b1-28855a34daec.PNG)
<img width="1920" alt="Screenshot 2021-08-08 at 18 58 55" src="https://user-images.githubusercontent.com/18351060/128641244-c447066b-0978-4e81-a6b3-c08fca37826c.png">

### Javascript logs from your browser console

```text

**Safari**

[Warning] The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. (app.a1195d53.js, line 849)
[Warning] The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'. (main-22e9dfb2.js, line 1217)
[Warning] [HACS.localize] – "Language 'en-GB' is not added to HACS. https://hacs.xyz/docs/developer/translation" (main-22e9dfb2.js, line 1217)
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'e.url.includes')
	performUpdate (main-22e9dfb2.js:1:14207)
	(anonymous function) (main-22e9dfb2.js:1:13784)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise

**Chrome**

main-22e9dfb2.js:1217 Uncaught (in promise) TypeError: Cannot read property 'includes' of undefined
    at main-22e9dfb2.js:1217
    at Array.some (<anonymous>)
    at Sr (main-22e9dfb2.js:1217)
    at c.c097cf2e.js:325
    at Array.forEach (<anonymous>)
    at c.c097cf2e.js:325
    at main-22e9dfb2.js:1217
    at HTMLElement.value (c.c097cf2e.js:325)
    at HTMLElement.update (main-22e9dfb2.js:1)
    at HTMLElement.performUpdate (main-22e9dfb2.js:1)

```

**Comment by gizbod** [comment] 2021-08-08 18:01
updated, hopefully with required information

**Comment by ludeeus** [comment] 2021-08-08 20:11
Duplicate of #2112

**Closed by ludeeus** 2021-08-08 20:11 UTC
Labels: Missing required issue information
