### ISSUE TITLE
HA install problems

### ISSUE THREAD

**Issue by sanitariu** [hacs/integration#3668] opened 2024-05-02 19:09 UTC
### Web browser

Safari

### Web browser version

latest

### System Health details

Perfect health !

Error is:

2024-05-02 22:06:03.754 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration hacs: cannot import na)

na module is installed.

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

2024-05-02 22:06:03.754 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration hacs: cannot import na)

na module is installed.

### Reproduction steps

1. Latest core HA
2.wget -O - https://get.hacs.xyz | bash -
3. integrations add hacs
4.  error is above
...

### Screenshots

no need for screenshots

### Javascript logs from your browser console

```text
none
```

**Comment by jcasarini** [comment] 2024-05-03 01:01
See if either #3666 or #3555 are related.
If the problem you are having is with activation part of the install, I've posted a working workaround in #3666: https://github.com/hacs/integration/issues/3666#issuecomment-2091464669

**Comment by ludeeus** [comment] 2024-05-03 07:55
Duplicate of #3666

**Closed by ludeeus** 2024-05-03 07:55 UTC
Labels: issue:frontend
