### ISSUE TITLE
Save button unresponsive when saving new integration in custom repository

### ISSUE THREAD

**Issue by francodutch** [hacs/integration#1178] opened 2020-05-21 10:11 UTC
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         | 0.24.5
Home Assistant version         | 0.110.0
Installation method for HA    | Hassbian
Web browser                         | Chrome
Web browser version            | 81.0.4044.124

## Checklist

- [ x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [ x] I have filled out the issue template to the best of my ability.
- [ x] I have read https://hacs.xyz/docs/issues
- [ x] This issue is related to the frontend of HACS.

## Describe the issue

I am trying to create a nbew integration (AlexxIT/sonoffLAN), type integration, and when I click the save button, nothing happens. INtegration is not created.

### Steps to reproduce

1. Go to HACS
1. Go to settings
1. Add customer repository AlexxIT/SonoffLAN
Click SAVE button

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

`Log Details (ERROR)
Logger: frontend.js.latest.202005190
Source: components/system_log/__init__.py:209 
First occurred: 10:48:06 (2 occurrences) 
Last logged: 11:55:36

https://chauge.duckdns.org/hacsfiles/frontend-20200426112021.js:2437:382612 TypeError: undefined is not an object (evaluating 'e.composedPath()[2].children[1].selectedItem')

</details>

<!-- IssueTemplateID: issue_frontend -->

**Comment by ludeeus** [comment] 2020-05-21 10:14
duplicate of https://github.com/hacs/integration/issues/1143

**Closed by ludeeus** 2020-05-21 10:14 UTC
Labels: issue:frontend
