### ISSUE TITLE
Detected that custom integration 'hacs' accesses hass.components.frontend. 

### ISSUE THREAD

**Issue by comet424** [hacs/integration#3557] opened 2024-03-22 20:19 UTC
### System Health details

Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues

### Reproduction steps

just goto the logs  and it tells you this

### Debug logs

```text
Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
```

**Comment by deu-sudo** [comment] 2024-03-23 06:39
same here

**Comment by Nardol** [comment] 2024-03-23 08:24
Looks duplicate, see #3534

**Comment by UK-JustinSmall** [comment] 2024-03-23 09:05
Same issue, now upgraded to 2024.3.3 but still have this error. When will this be fixed or do I need to do something to fix it, if so what?

**Comment by Stepsilein** [comment] 2024-03-25 10:37
Bump...
Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues

**Comment by fft1010** [comment] 2024-04-07 11:33
Hi,
same here with 2024.4.1

thanks
Juergen

**Comment by ludeeus** [comment] 2024-04-09 15:58
Duplicate of #3534

**Closed by ludeeus** 2024-04-09 15:58 UTC
Labels: issue:backend
