### ISSUE TITLE
Inconsistent downloaded filter checkbox

### ISSUE THREAD

**Issue by stiltjack** [hacs/integration#3347] opened 2023-11-16 15:52 UTC
### Web browser

HA companion app

### Web browser version

2023.11.2

## System Information

version | core-2023.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1337
Downloaded Repositories | 24
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 11 August 2024 at 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | eu-central-1-7.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.3
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 219.4 GB
disk_used | 6.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.1.0), Terminal & SSH (9.8.1), RPC Shutdown (2.4), File editor (5.7.0), Samba Backup (5.2.0), ArgonOne Active Cooling (30a), Mosquitto broker (6.3.1), Silicon Labs Flasher (0.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 10
-- | --
resources | 12
views | 25
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 6 November 2023 at 05:15
-- | --
current_recorder_run | 16 November 2023 at 05:15
estimated_db_size | 326.40 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

A trivial point (sorry!). In the experimental features version of HACS, if you clear the filters then click on the "filter by downloaded" checkbox, when you open the filter dropdown again the tick appears very briefly, then disappears. This means that the dropdown no longer corresponds to what is showing in the main window - I would expect the dropdown box to remain ticked. I think a couple of people on the forum have found this confusing (particularly if they've installed the experimental features version by accident). Same behaviour appears in Chrome 118.0.5993.124 (Official Build) (64-bit).

### Reproduction steps

1. With experimental features enabled, clear filters by clicking on CLEAR (top right).
2. Open the filter dropdown and click on Downloaded
3. The dropdown will close and only downloaded integrations will be shown
4. Open the filter dropdown again
5. The tick appears briefly in the Downloaded box, then disappears. The main screen continues to show downloaded integrations only.
...

### Screenshots

![image](https://github.com/hacs/integration/assets/67193733/1be9dfe8-2a9b-4d0f-9f80-d77cc2b0b7d8)

### Javascript logs from your browser console

```text
If there are any in the companion app, don't know where to find them!
```

**Comment by ludeeus** [comment] 2023-11-16 15:59
I'm not able to reproduce this.
What OS is this on?

And when you get the same in Chrome, is there nothing in the console there?

**Comment by stiltjack** [comment] 2023-11-16 18:38
Using a Chromebook initially, but I get the same result on Windows 10 (also Chrome). Both give this error:

load_resource.ts:13 Uncaught (in promise) http://homeassistant.local:8123/hacsfiles/text-element/text-element.js

**Comment by ludeeus** [comment] 2023-11-16 18:44
That is not related, can you try with incognito as well?

**Comment by stiltjack** [comment] 2023-11-16 19:46
The same result.

**Comment by bkbartk** [comment] 2024-01-11 07:42
I found the same in firefox,
maybe one addition,
if you click clear, and then hit the filter dropdown also the checkbox next the downloaded is checked for 0.1 sec or something.
this is probabaly related to the behaviar.

**Comment by ludeeus** [comment] 2024-01-12 15:48
That's not related @bkbartk, that is just the animation of the element.

@stiltjack  Did not figure out what was causing it here.
It happens if you click the checkbox (and not the text right of it) It does not seem to be limited to HACS.
If you go to <https://my.home-assistant.io/redirect/entities/> you should be able to trigger the same thing there.

**Comment by ludeeus** [comment] 2024-01-12 16:46
Turns out this was already reported, closing here for now.

**Closed by ludeeus** 2024-01-12 16:46 UTC
Labels: issue:frontend
