### ISSUE TITLE
Can't uninstall plugin from archived repository

### ISSUE THREAD

**Issue by SteveDinn** [hacs/integration#1017] opened 2020-03-21 01:37 UTC
## Version of HACS

0.23.2

## Describe the bug
I had some old plugins installed that belong to repositories that have been archived. HACS logs this issue on startup, and makes the icons of those plugins red so that they are visible. I tried to uninstall these plugins, but when I navigte to their pages, I get the following (spelling in context):
```
An error ocoured while processing
Repository is archived.
[Acknowledge]
```
The spinny animation never stops.

Upon clicking  'uninstall', and clicking 'yes' after the prompt, I get a different spinny animation that also never stops. The plugin is not removed.

## Debug log

<details>
  <summary>Logs</summary>

```text
2020-03-20 22:06:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-03-20 22:06:17 INFO (MainThread) [homeassistant.setup] Setting up hacs
2020-03-20 22:06:17 INFO (MainThread) [hacs] 
HACS (Home Assistant Community Store)
https://github.com/hacs/integration/issues
2020-03-20 22:06:18 INFO (MainThread) [hacs.repository.integration.hacs.integration] Registration complete
2020-03-20 22:06:19 INFO (MainThread) [hacs.data] Restore started
2020-03-20 22:06:19 INFO (MainThread) [hacs.data] Restore done
2020-03-20 22:06:19 INFO (MainThread) [homeassistant.setup] Setup of domain hacs took 2.2 seconds.
2020-03-20 22:06:19 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.hacs
2020-03-20 22:06:25 INFO (MainThread) [hacs] Loading known repositories
2020-03-20 22:06:29 INFO (MainThread) [hacs] Loading known repositories finished
2020-03-20 22:06:29 INFO (MainThread) [hacs.factory] Processing 21 tasks
2020-03-20 22:06:30 ERROR (MainThread) [hacs.factory] thomasloven/lovelace-card-modder - Repository is archived.
2020-03-20 22:06:35 ERROR (MainThread) [hacs.factory] thomasloven/lovelace-markdown-mod - Repository is archived.
2020-03-20 22:06:43 INFO (MainThread) [hacs.factory] Task processing of 21 tasks completed in 13 seconds
2020-03-20 22:27:46 DEBUG (MainThread) [hacs] Running set_state for thomasloven/lovelace-card-modder
2020-03-20 22:27:46 DEBUG (MainThread) [hacs.data] Saving data
2020-03-20 22:27:46 DEBUG (MainThread) [hacs] Running update for thomasloven/lovelace-card-modder
2020-03-20 22:27:46 DEBUG (MainThread) [hacs.repository.plugin.thomasloven.lovelace-card-modder] Getting repository information
2020-03-20 22:28:11 DEBUG (MainThread) [hacs] Running set_state for thomasloven/lovelace-card-modder
2020-03-20 22:28:11 DEBUG (MainThread) [hacs.data] Saving data
2020-03-20 22:28:33 DEBUG (MainThread) [hacs] Running set_state for thomasloven/lovelace-markdown-mod
2020-03-20 22:28:33 DEBUG (MainThread) [hacs.data] Saving data
2020-03-20 22:28:33 DEBUG (MainThread) [hacs] Running update for thomasloven/lovelace-markdown-mod
2020-03-20 22:28:33 DEBUG (MainThread) [hacs.repository.plugin.thomasloven.lovelace-markdown-mod] Getting repository information
2020-03-20 22:28:56 DEBUG (MainThread) [hacs] Running set_state for thomasloven/lovelace-markdown-mod
2020-03-20 22:28:56 DEBUG (MainThread) [hacs.data] Saving data
```

</details>

**Comment by ludeeus** [comment] 2020-03-21 09:19
duplicate of #1015

**Closed by ludeeus** 2020-03-21 09:19 UTC
