### ISSUE TITLE
Uncaught SyntaxError: Identifier 's' has already been declared

### ISSUE THREAD

**Issue by friendodevil** [hacs/integration#830] opened 2019-11-28 20:18 UTC
I've upgraded to 17.4. Integration: Did a fresh remove-install (remove all, double/triple reboot). Installed via Configuration>Integrations successfully. hacs.sensor is functioning however when I click on the Community icon I get a blank white screen

Logs shows: https:/xyz.duckdns.org/hacs_frontend/main.js?v=0.17.4:1:1 Uncaught SyntaxError: Identifier 's' has already been declared

**Comment by ludeeus** [comment] 2019-11-28 21:06
Duplicate of https://github.com/hacs/frontend/issues/26

**Closed** 2019-11-28 21:06 UTC
