### ISSUE TITLE
Mini Graph Card fails to update to the latest version

### ISSUE THREAD

**Issue by shreram** [hacs/integration#992] opened 2020-03-05 18:50 UTC
## Version of HACS

Installed: 0.22.2

## Describe the bug

Mini Graph Card fails to update to the latest version. I cleared the cache but the same issue. From the logs, it looks like the repository is archived but it's not. 

![Screen Shot 2020-03-05 at 11 53 05 AM](https://user-images.githubusercontent.com/16169720/76010189-1ebef780-5ed8-11ea-87c1-ce238f541b72.png)

## Debug log

```
2020-03-05 11:10:35 ERROR (MainThread) [frontend.js.latest.202002205] http://192.168.86.226:8123/hacsfiles/frontend-20200229193422.js:1:17049 Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "hacs-frontendbase" has already been used with this registry
```

<details>
  <summary>Logs</summary>

```text
Paste your logs here.
2020-03-05 11:37:31 INFO (MainThread) [hacs.repository.plugin.kalkih.mini-graph-card] download of mini-graph-card-bundle.js complete
2020-03-05 11:37:31 ERROR (MainThread) [hacs.repository.plugin.kalkih.mini-graph-card] Repository is archived.
2020-03-05 11:37:31 ERROR (MainThread) [hacs.repository.plugin.kalkih.mini-graph-card] Repository is archived.
2020-03-05 11:40:38 INFO (MainThread) [hacs.factory] Processing 37 tasks

```

</details>

**Comment by ludeeus** [comment] 2020-03-05 18:54
It does update, it's just HACS that don't think it did.
Duplicate of #990

**Closed** 2020-03-05 18:54 UTC
