### ISSUE TITLE
Error trying to update to 0.24.3

### ISSUE THREAD

**Issue by Coolie1101** [hacs/integration#1124] opened 2020-05-05 20:56 UTC
## Version of HACS
0.24.2

## Describe the bug
While trying to update HACS from the UI, I receive the following error.

"An error occurred while processing
Could not use repository with ID 172733314"

Screenshot:
![image](https://user-images.githubusercontent.com/28989417/81115432-b39e9b00-8ef1-11ea-8ce0-abc85a72da9f.png)

## Debug log

<details>
  <summary>Logs</summary>

```
2020-05-05 16:44:55 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-05 16:44:55 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for anniversaries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-05 16:45:07 DEBUG (MainThread) [hacs] Configuration type: flow
2020-05-05 16:45:07 INFO (MainThread) [hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 0.24.2
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2020-05-05 16:45:09 DEBUG (MainThread) [hacs] Can update 457 repositories
2020-05-05 16:45:09 DEBUG (MainThread) [hacs.repository.integration.hacs.integration] Checking repository.
2020-05-05 16:45:10 DEBUG (MainThread) [hacs.repository.integration.hacs.integration] Running checks against 0.24.3
2020-05-05 16:45:11 INFO (MainThread) [hacs.repository.integration.hacs.integration] Registration complete
2020-05-05 16:45:11 INFO (MainThread) [hacs.data] Restore started
2020-05-05 16:45:20 INFO (MainThread) [hacs.data] Restore done
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] appdaemon_path: appdaemon/apps/
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] appdaemon: True
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] netdaemon_path: netdaemon/apps/
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] netdaemon: True
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] config_type: flow
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] debug: False
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] dev: False
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] frontend_mode: Grid
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] frontend_compact: False
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] onboarding_done: True
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] plugin_path: www/community/
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] python_script_path: python_scripts/
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] python_script: False
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] sidepanel_icon: mdi:alpha-c-box
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] sidepanel_title: HACS
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] theme_path: themes/
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] theme: False
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] country: US
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] experimental: False
2020-05-05 16:45:20 DEBUG (MainThread) [hacs.configuration] release_limit: 5
2020-05-05 16:45:32 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.average_house_temp fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/template/sensor.py", line 224, in async_update
    self._state = self._template.async_render()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/template.py", line 222, in async_render
    return compiled.render(kwargs).strip()
  File "/srv/homeassistant/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/srv/homeassistant/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/srv/homeassistant/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 2, in top-level template code
TypeError: unsupported operand type(s) for +: 'float' and 'str'
2020-05-05 16:45:42 DEBUG (MainThread) [hacs] 4672
2020-05-05 16:45:42 DEBUG (MainThread) [hacs] 2020-05-05 21:05:09
2020-05-05 16:46:01 DEBUG (MainThread) [hacs] Running set_state for hacs/integration
2020-05-05 16:46:01 DEBUG (MainThread) [hacs] Running update for hacs/integration
2020-05-05 16:46:01 DEBUG (MainThread) [hacs.repository.integration.hacs.integration] Getting repository information
2020-05-05 16:46:10 DEBUG (MainThread) [hacs.repository.integration.hacs.integration] Running checks against 0.24.3
2020-05-05 16:46:13 INFO (MainThread) [hacs] Loading known repositories
2020-05-05 16:46:21 DEBUG (MainThread) [hacs] Starting recuring background task for installed repositories
2020-05-05 16:46:21 DEBUG (MainThread) [hacs] 4644
2020-05-05 16:46:21 DEBUG (MainThread) [hacs] 2020-05-05 21:05:10
2020-05-05 16:46:22 DEBUG (MainThread) [hacs.data] Saving data
2020-05-05 16:46:23 DEBUG (MainThread) [hacs] Recuring background task for installed repositories done
2020-05-05 16:46:23 DEBUG (MainThread) [queueman.manager] Checking out tasks to execute
2020-05-05 16:46:23 DEBUG (MainThread) [queueman.manager] Starting queue execution for 16 tasks
2020-05-05 16:46:23 DEBUG (MainThread) [hacs.repository.integration.hacs.integration] Getting repository information
2020-05-05 16:46:23 DEBUG (MainThread) [hacs.repository.integration.custom-components.alexa_media_player] Getting repository information
2020-05-05 16:46:23 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.dual-gauge-card] Getting repository information
2020-05-05 16:46:23 DEBUG (MainThread) [hacs.repository.plugin.iantrich.aftership-card] Getting repository information
2020-05-05 16:46:23 DEBUG (MainThread) [hacs.repository.plugin.kalkih.mini-graph-card] Getting repository information
2020-05-05 16:46:23 DEBUG (MainThread) [hacs.repository.plugin.ljmerza.calendar-card] Getting repository information
2020-05-05 16:46:23 DEBUG (MainThread) [hacs.repository.integration.custom-components.breaking_changes] Getting repository information
2020-05-05 16:46:23 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.decluttering-card] Getting repository information
2020-05-05 16:46:23 DEBUG (MainThread) [hacs.repository.plugin.bramkragten.weather-card] Getting repository information
2020-05-05 16:46:23 DEBUG (MainThread) [hacs.repository.integration.thomasloven.hass-browser_mod] Getting repository information
2020-05-05 16:46:23 DEBUG (MainThread) [hacs.repository.plugin.AmoebeLabs.flex-horseshoe-card] Getting repository information
2020-05-05 16:46:23 DEBUG (MainThread) [hacs.repository.integration.pinkywafer.Anniversaries] Getting repository information
2020-05-05 16:46:23 DEBUG (MainThread) [hacs.repository.integration.Limych.ha-car_wash] Getting repository information
2020-05-05 16:46:23 DEBUG (MainThread) [hacs.repository.theme.naofireblade.clear-theme-dark] Getting repository information
2020-05-05 16:46:23 DEBUG (MainThread) [hacs.repository.theme.aFFekopp.dark_teal] Getting repository information
2020-05-05 16:46:24 DEBUG (MainThread) [hacs.repository.integration.custom-components.alexa_media_player] Running checks against v2.6.1
2020-05-05 16:46:24 DEBUG (MainThread) [hacs.repository.integration.hacs.integration] Running checks against 0.24.3
2020-05-05 16:46:25 DEBUG (MainThread) [hacs.repository.plugin.iantrich.aftership-card] Running checks against 1.2.0
2020-05-05 16:46:25 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.dual-gauge-card] Running checks against 0.5.2
2020-05-05 16:46:25 DEBUG (MainThread) [hacs.repository.plugin.ljmerza.calendar-card] Running checks against 3.108.6
2020-05-05 16:46:25 DEBUG (MainThread) [hacs.repository.plugin.kalkih.mini-graph-card] Running checks against v0.9.3
2020-05-05 16:46:25 DEBUG (MainThread) [hacs.repository.plugin.bramkragten.weather-card] Running checks against v1.4.3
2020-05-05 16:46:25 DEBUG (MainThread) [hacs.repository.integration.custom-components.breaking_changes] Running checks against 0.3.6
2020-05-05 16:46:25 DEBUG (MainThread) [hacs.repository.plugin.AmoebeLabs.flex-horseshoe-card] Running checks against 0.8.3
2020-05-05 16:46:25 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.decluttering-card] Running checks against 0.6.2
2020-05-05 16:46:25 DEBUG (MainThread) [hacs.repository.integration.Limych.ha-car_wash] Running checks against master
2020-05-05 16:46:25 DEBUG (MainThread) [hacs.repository.integration.pinkywafer.Anniversaries] Running checks against 2.2.0
2020-05-05 16:46:25 DEBUG (MainThread) [hacs.repository.theme.naofireblade.clear-theme-dark] Running checks against v1.3
2020-05-05 16:46:25 DEBUG (MainThread) [hacs.repository.theme.aFFekopp.dark_teal] Running checks against 1.1
2020-05-05 16:46:25 DEBUG (MainThread) [hacs.repository.integration.thomasloven.hass-browser_mod] Running checks against 25
2020-05-05 16:46:31 DEBUG (MainThread) [hacs.repository.theme.fi-sch.ux_goodie_theme] Getting repository information
2020-05-05 16:46:31 DEBUG (MainThread) [hacs.repository.theme.fi-sch.ux_goodie_theme] Running checks against 1.0
2020-05-05 16:46:37 DEBUG (MainThread) [queueman.manager] Queue execution finished for 16 tasks finished in 14.28 seconds
2020-05-05 16:46:37 DEBUG (MainThread) [hacs.data] Saving data
2020-05-05 16:47:01 DEBUG (MainThread) [hacs] Running set_state for hacs/integration
2020-05-05 16:47:01 DEBUG (MainThread) [hacs.data] Saving data
2020-05-05 16:47:01 DEBUG (MainThread) [hacs] Running install for hacs/integration
2020-05-05 16:47:01 DEBUG (MainThread) [hacs.repository.integration.hacs.integration] Getting repository information
2020-05-05 16:47:02 DEBUG (MainThread) [hacs.repository.integration.hacs.integration] Running checks against 0.24.3
2020-05-05 16:47:03 INFO (MainThread) [hacs.repository.integration.hacs.integration] ref: tags/0.24.3  ---  tag: 0.24.3
2020-05-05 16:47:03 INFO (MainThread) [hacs.repository.integration.hacs.integration] ref: tags/0.24.3  ---  tag: 0.24.2
2020-05-05 16:47:03 INFO (MainThread) [hacs.repository.integration.hacs.integration] ref: tags/0.24.3  ---  tag: 0.24.1
2020-05-05 16:47:03 INFO (MainThread) [hacs.repository.integration.hacs.integration] ref: tags/0.24.3  ---  tag: 0.24.0
2020-05-05 16:47:03 INFO (MainThread) [hacs.repository.integration.hacs.integration] ref: tags/0.24.3  ---  tag: 0.23.2
2020-05-05 16:47:03 DEBUG (MainThread) [hacs.download.downloader] Downloading https://github.com/hacs/integration/releases/download/0.24.3/hacs.zip
2020-05-05 16:47:03 DEBUG (MainThread) [hacs.download.save] Saving /tmp/hacs.zip
2020-05-05 16:47:03 ERROR (MainThread) [hacs] Could not use repository with ID 172733314
```

**Comment by ludeeus** [comment] 2020-05-07 19:10
duplicate of https://github.com/hacs/integration/issues/1089

**Closed by ludeeus** 2020-05-07 19:10 UTC
