### ISSUE TITLE
HA logs show 'install' is deprecated, use 'async_install' instead when updating

### ISSUE THREAD

**Issue by RezzZ** [hacs/integration#1344] opened 2020-06-18 05:52 UTC
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS
   Integration version: | 1.1.0
   Frontend version: | 202006071141
| Home Assistant version     | 1.110.5
| Installation method for HA |

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue
HACS uses install to update an integration. This is depricated according to the logs in HA. HACS should use async_install instead.
![image](https://user-images.githubusercontent.com/70499/84983178-84a65680-b138-11ea-8450-a5e36ec7b68f.png)
![image](https://user-images.githubusercontent.com/70499/84983207-90921880-b138-11ea-853e-385399a59605.png)

### Steps to reproduce
update something in HACS

## Debug logs
<details>
  <summary>Logs</summary>

```
Logger: hacs.repository.theme.basnijholt.lovelace-ios-themes
Source: custom_components/hacs/repositories/helpers/methods/installation.py:17
First occurred: 7:42:53 AM (1 occurrences)
Last logged: 7:42:53 AM

'install' is deprecated, use 'async_install' instead
```

</details>

**Comment by ludeeus** [comment] 2020-06-18 06:04
Duplicate of #1320

**Closed by ludeeus** 2020-06-18 06:04 UTC
Labels: issue:backend

**Comment by RezzZ** [comment] 2020-06-18 06:33
weird, i searched.. sorry for the duplicate @ludeeus
