### ISSUE TITLE
Unable to uninstall frontend plugins

### ISSUE THREAD

**Issue by tomlut** [hacs/integration#1423] opened 2020-08-01 13:20 UTC
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.3.0b1
| Home Assistant version     |0.113.1
| Installation method for HA |HassOS

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ ] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I am unable to uninstall frontend plugins.

### Steps to reproduce

Click on the uninstall link on any frontend plugin.

## Debug logs

<details>
  <summary>Logs</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment] 2020-08-01 13:21
Duplicate of #1421

**Closed by ludeeus** 2020-08-01 13:21 UTC
Labels: issue:backend
