### ISSUE TITLE
Missing icon for sensor.hacs

### ISSUE THREAD

**Issue by chemelli74** [hacs/integration#1173] opened 2020-05-20 23:27 UTC
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         | 0.24.5
Home Assistant version         | 0.110.0
Installation method for HA    | Docker

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the backend of HACS.

## Describe the issue

Missing icons for hacs 

### Steps to reproduce

1. Add "sensor.hacs" to lovelace
2. Check icon

![image](https://user-images.githubusercontent.com/57354320/82507242-0dae7b80-9b02-11ea-8ae6-24395019d77f.png)

## Debug logs

<details>
  <summary>Logs</summary>

```text
-
```

</details>

**Comment by iptvcld** [comment] 2020-05-21 03:24
Same issue, thanks

**Comment by DavidFW1960** [comment] 2020-05-21 06:06
There is a pinned thread at the top of the issues page about this. The short term solution (from that thread) is to grab this file
https://github.com/hacs/integration/blob/master/custom_components/hacs/iconset.js

**Comment by ludeeus** [comment] 2020-05-21 08:39
duplicate of https://github.com/hacs/integration/issues/1157

**Closed by ludeeus** 2020-05-21 08:39 UTC
Labels: issue:backend
