### ISSUE TITLE
Unable to add custom repository in HA 0.110.0

### ISSUE THREAD

**Issue by GeorgeSG** [hacs/integration#1172] opened 2020-05-20 19:28 UTC
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         | 0.24.5
Home Assistant version         | 0.110.0
Installation method for HA    | Docker

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [ ] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [ ] This issue is related to the backend of HACS.

## Describe the issue

After upgrading Home Assistant to 0.110.0, I am unable to add custom repositories to HACS.

### Steps to reproduce

1. Open HACS -> Settings
1. Paste `https://github.com/GeorgeSG/hass-bha-icons` as custom repository, select Plugin category
1. Click save.

Outcome: Repository is not added. Error in browser console.

## Debug logs

Browser console error:
```
Uncaught TypeError: Cannot read property 'selectedItem' of undefined
    at HTMLElement.Save (frontend-20200426112021.js:2437)
    at T.handleEvent (frontend-20200426112021.js:1)
    at HTMLElement.T.__boundHandleEvent (frontend-20200426112021.js:1)
```

AFAIK [this](https://github.com/hacs/frontend/blob/41262f3ae3dd06be613b1c16ff28d0f66603b194/src/legacy/misc/CustomRepositories.ts#L95) is the problematic line. No idea why though.

**Comment by ludeeus** [comment] 2020-05-20 19:28
duplicate of https://github.com/hacs/integration/issues/1143

**Closed by ludeeus** 2020-05-20 19:28 UTC
Labels: issue:backend
