### ISSUE TITLE
Error setting up entry for hacs Traceback #44028

### ISSUE THREAD

**Issue by Zipsnet** [hacs/integration#1709] opened 2020-12-07 20:29 UTC
## Installation details

Version | 1.0.0b2
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.6
Operating System Family | Linux
Operating System Version | 5.4.81
CPU Architecture | x86_64
Timezone | America/New_York
HACS release 1.8.0

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.8.0
| Home Assistant version     | 1.0.0b2
| Installation method for HA |  Home Assistant OS

## Checklist

- [X ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X ] I have enabled debug logging for my installation.
- [X ] I have filled out the issue template to the best of my ability.
- [X ] I have read <https://hacs.xyz/docs/issues>
- [ ] This issue is related to the backend of HACS.
- [X ] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

A clear and concise description of what the issue is.

A Clean install will throw an error and HACS will not start.

![ Error IMage]
(https://imgur.com/a/O9hdjQF)

### Steps to reproduce

 Followed step by step 

1. https://hacs.xyz/docs/installation/manual
2. https://hacs.xyz/docs/configuration/pat
3. https://hacs.xyz/docs/configuration/basic

After finishing all 3 steps HACS will not start

## Debug logs

<details>
  <summary>Logs</summary>

```


2020-12-07 13:01:00 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry for hacs
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/hacs/init.py", line 30, in async_setup_entry
return await hacs_ui_setup(hass, config_entry)
File "/config/custom_components/hacs/operational/setup.py", line 67, in async_setup_entry
return await async_startup_wrapper_for_config_entry()
File "/config/custom_components/hacs/operational/setup.py", line 92, in async_startup_wrapper_for_config_entry
startup_result = await async_hacs_startup()
File "/config/custom_components/hacs/operational/setup.py", line 197, in async_hacs_startup
async_call_later(hacs.hass, 5, hacs.startup_tasks())
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1179, in async_call_later
return async_track_point_in_utc_time(
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1133, in async_track_point_in_utc_time
job = action if isinstance(action, HassJob) else HassJob(action)
File "/usr/src/homeassistant/homeassistant/core.py", line 174, in init
raise ValueError("Coroutine not allowed to be passed to HassJob")
ValueError: Coroutine not allowed to be passed to HassJob

```

</details>

**Comment by ludeeus** [comment] 2020-12-07 20:33
Duplicate of https://github.com/hacs/integration/issues/1693

**Closed by ludeeus** 2020-12-07 20:33 UTC
Labels: issue:backend
