### ISSUE TITLE
custom component not available

### ISSUE THREAD

**Issue by pilot1981** [hacs/integration#2471] opened 2022-01-25 10:13 UTC
### Describe the issue

custom component not available (greyed), not any background activity in pending (HA started from many and many hours)

### Link to action run

NA

### Link to action configuration

NA

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by ludeeus** [comment] 2022-01-25 10:14
Duplicate of #2440

**Closed by ludeeus** 2022-01-25 10:14 UTC
