### ISSUE TITLE
HACS can not start after GitHub auth

### ISSUE THREAD

**Issue by ikar303** [hacs/integration#3239] opened 2023-08-28 19:00 UTC
### System Health details

OK.

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

After installing with following command:
```
# wget -O - https://get.hacs.xyz | bash -
```

I am not able to complete HACS addon adding because it HANGS at the following image on the web interface:

- https://i.imgur.com/tHbllZ7.png

... and nothing more happens.

I have tried may times but without success.

I have tried Home Assistant versions: 10.3 and 10.5.

### Reproduction steps

As mentioned above.

### Debug logs

```text
2023-08-28 20:57:42.465 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-08-28 20:57:42.855 INFO (MainThread) [homeassistant.setup] Setup of domain logger took 0.0 seconds
2023-08-28 20:57:42.858 INFO (MainThread) [homeassistant.bootstrap] Setting up frontend: {'frontend'}
2023-08-28 20:57:42.951 INFO (MainThread) [homeassistant.setup] Setting up device_automation
2023-08-28 20:57:42.952 INFO (MainThread) [homeassistant.setup] Setup of domain device_automation took 0.0 seconds
2023-08-28 20:57:43.487 INFO (MainThread) [homeassistant.setup] Setting up lovelace
2023-08-28 20:57:43.497 INFO (MainThread) [homeassistant.setup] Setting up http
2023-08-28 20:57:43.508 INFO (MainThread) [homeassistant.setup] Setup of domain lovelace took 0.0 seconds
2023-08-28 20:57:43.571 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.1 seconds
2023-08-28 20:57:43.640 INFO (MainThread) [homeassistant.setup] Setting up api
2023-08-28 20:57:43.652 INFO (MainThread) [homeassistant.setup] Setup of domain api took 0.0 seconds
2023-08-28 20:57:43.658 INFO (MainThread) [homeassistant.setup] Setting up auth
2023-08-28 20:57:43.668 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.0 seconds
2023-08-28 20:57:43.723 INFO (MainThread) [homeassistant.setup] Setting up config
2023-08-28 20:57:43.784 INFO (MainThread) [homeassistant.setup] Setting up diagnostics
2023-08-28 20:57:43.853 INFO (MainThread) [homeassistant.setup] Setting up repairs
2023-08-28 20:57:43.856 INFO (MainThread) [homeassistant.setup] Setup of domain repairs took 0.0 seconds
2023-08-28 20:57:44.504 INFO (MainThread) [homeassistant.setup] Setup of domain config took 0.8 seconds
2023-08-28 20:57:44.509 INFO (MainThread) [homeassistant.setup] Setup of domain diagnostics took 0.7 seconds
2023-08-28 20:57:44.599 INFO (MainThread) [homeassistant.setup] Setting up file_upload
2023-08-28 20:57:44.600 INFO (MainThread) [homeassistant.setup] Setup of domain file_upload took 0.0 seconds
2023-08-28 20:57:44.884 INFO (MainThread) [homeassistant.setup] Setting up image_upload
2023-08-28 20:57:44.893 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2023-08-28 20:57:44.895 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.0 seconds
2023-08-28 20:57:44.908 INFO (MainThread) [homeassistant.setup] Setup of domain image_upload took 0.0 seconds
2023-08-28 20:57:44.926 INFO (SyncWorker_2) [homeassistant.loader] Loaded device_tracker from homeassistant.components.device_tracker
2023-08-28 20:57:44.932 INFO (SyncWorker_3) [homeassistant.loader] Loaded group from homeassistant.components.group
2023-08-28 20:57:49.687 INFO (MainThread) [homeassistant.setup] Setting up analytics
2023-08-28 20:57:49.699 INFO (MainThread) [homeassistant.setup] Setting up person
2023-08-28 20:57:50.023 INFO (MainThread) [homeassistant.setup] Setting up search
2023-08-28 20:57:50.024 INFO (MainThread) [homeassistant.setup] Setup of domain search took 0.0 seconds
2023-08-28 20:57:50.029 INFO (MainThread) [homeassistant.setup] Setup of domain analytics took 0.3 seconds
2023-08-28 20:57:50.053 INFO (MainThread) [homeassistant.setup] Setup of domain person took 0.4 seconds
2023-08-28 20:57:50.061 INFO (MainThread) [homeassistant.setup] Setting up onboarding
2023-08-28 20:57:50.066 INFO (MainThread) [homeassistant.setup] Setup of domain onboarding took 0.0 seconds
2023-08-28 20:57:50.080 INFO (MainThread) [homeassistant.setup] Setting up frontend
2023-08-28 20:57:50.098 INFO (MainThread) [homeassistant.setup] Setup of domain frontend took 0.0 seconds
2023-08-28 20:57:50.106 INFO (MainThread) [homeassistant.bootstrap] Setting up recorder: {'recorder'}
2023-08-28 20:57:50.119 INFO (MainThread) [homeassistant.setup] Setting up recorder
2023-08-28 20:57:50.197 INFO (MainThread) [homeassistant.components.http] Now listening on port 8123
2023-08-28 20:57:51.314 INFO (MainThread) [homeassistant.setup] Setup of domain recorder took 1.2 seconds
2023-08-28 20:57:51.323 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 1: {'usb', 'zeroconf', 'api', 'network', 'bluetooth', 'websocket_api', 'webhook', 'logger', 'hassio', 'http', 'dhcp', 'ssdp', 'cloud'}
2023-08-28 20:57:51.447 INFO (MainThread) [homeassistant.setup] Setting up webhook
2023-08-28 20:57:51.450 INFO (MainThread) [homeassistant.setup] Setup of domain webhook took 0.0 seconds
2023-08-28 20:57:51.457 INFO (MainThread) [homeassistant.setup] Setting up hassio
2023-08-28 20:57:51.644 INFO (MainThread) [homeassistant.setup] Setting up usb
2023-08-28 20:57:51.668 INFO (MainThread) [homeassistant.setup] Setup of domain usb took 0.0 seconds
2023-08-28 20:57:51.692 INFO (MainThread) [homeassistant.setup] Setting up network
2023-08-28 20:57:51.699 INFO (MainThread) [homeassistant.setup] Setup of domain network took 0.0 seconds
2023-08-28 20:57:54.542 INFO (MainThread) [homeassistant.setup] Setting up dhcp
2023-08-28 20:57:54.544 INFO (MainThread) [homeassistant.setup] Setup of domain dhcp took 0.0 seconds
2023-08-28 20:57:54.560 WARNING (MainThread) [homeassistant.setup] Setup of hassio is taking over 10 seconds.
2023-08-28 20:57:55.975 INFO (SyncWorker_1) [homeassistant.loader] Loaded google_assistant from homeassistant.components.google_assistant
2023-08-28 20:57:55.986 INFO (SyncWorker_2) [homeassistant.loader] Loaded alexa from homeassistant.components.alexa
2023-08-28 20:57:56.010 INFO (SyncWorker_0) [homeassistant.loader] Loaded camera from homeassistant.components.camera
2023-08-28 20:57:58.756 INFO (MainThread) [homeassistant.setup] Setting up bluetooth
2023-08-28 20:58:03.560 INFO (MainThread) [homeassistant.setup] Setting up zeroconf
2023-08-28 20:58:03.654 INFO (MainThread) [homeassistant.setup] Setup of domain zeroconf took 0.1 seconds
2023-08-28 20:58:03.694 INFO (SyncWorker_3) [homeassistant.loader] Loaded media_player from homeassistant.components.media_player
2023-08-28 20:58:03.736 INFO (MainThread) [homeassistant.components.zeroconf] Starting Zeroconf broadcast
2023-08-28 20:58:06.616 INFO (MainThread) [homeassistant.setup] Setting up cloud
2023-08-28 20:58:07.036 INFO (MainThread) [homeassistant.setup] Setting up ssdp
2023-08-28 20:58:07.225 INFO (MainThread) [homeassistant.setup] Setup of domain cloud took 0.6 seconds
2023-08-28 20:58:07.284 INFO (MainThread) [homeassistant.setup] Setup of domain ssdp took 0.2 seconds
2023-08-28 20:58:07.471 INFO (MainThread) [homeassistant.setup] Setup of domain bluetooth took 8.7 seconds
2023-08-28 20:58:07.607 INFO (MainThread) [homeassistant.setup] Setup of domain hassio took 23.2 seconds
2023-08-28 20:58:17.809 INFO (SyncWorker_1) [homeassistant.loader] Loaded binary_sensor from homeassistant.components.binary_sensor
2023-08-28 20:58:17.814 INFO (SyncWorker_0) [homeassistant.loader] Loaded update from homeassistant.components.update
2023-08-28 20:58:17.820 INFO (SyncWorker_1) [homeassistant.loader] Loaded sensor from homeassistant.components.sensor
2023-08-28 20:58:17.831 INFO (MainThread) [homeassistant.setup] Setting up binary_sensor
2023-08-28 20:58:17.835 INFO (MainThread) [homeassistant.setup] Setup of domain binary_sensor took 0.0 seconds
2023-08-28 20:58:17.863 INFO (MainThread) [homeassistant.setup] Setting up update
2023-08-28 20:58:17.874 INFO (MainThread) [homeassistant.setup] Setup of domain update took 0.0 seconds
2023-08-28 20:58:17.919 INFO (MainThread) [homeassistant.setup] Setting up sensor
2023-08-28 20:58:17.921 INFO (MainThread) [homeassistant.setup] Setup of domain sensor took 0.0 seconds
2023-08-28 20:58:17.967 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.hassio
2023-08-28 20:58:17.968 INFO (MainThread) [homeassistant.components.update] Setting up update.hassio
2023-08-28 20:58:17.970 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.hassio
2023-08-28 20:58:18.027 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'trace', 'hardware', 'zone', 'map', 'automation', 'config', 'input_number', 'timer', 'counter', 'system_health', 'input_button', 'analytics', 'conversation', 'radio_browser', 'sun', 'image_upload', 'scene', 'file_upload', 'tts', 'mobile_app', 'application_credentials', 'my', 'met', 'stt', 'schedule', 'media_source', 'default_config', 'history', 'input_boolean', 'search', 'repairs', 'input_select', 'lovelace', 'energy', 'device_automation', 'input_text', 'stream', 'input_datetime', 'person', 'blueprint', 'homeassistant_alerts', 'diagnostics', 'onboarding', 'cast', 'assist_pipeline', 'logbook', 'tag', 'auth', 'google_translate', 'script'}
2023-08-28 20:58:18.057 INFO (MainThread) [homeassistant.setup] Setting up trace
2023-08-28 20:58:18.058 INFO (MainThread) [homeassistant.setup] Setup of domain trace took 0.0 seconds
2023-08-28 20:58:18.667 INFO (MainThread) [homeassistant.setup] Setting up hardware
2023-08-28 20:58:18.671 INFO (MainThread) [homeassistant.setup] Setting up zone
2023-08-28 20:58:18.689 INFO (MainThread) [homeassistant.setup] Setting up input_number
2023-08-28 20:58:18.695 INFO (MainThread) [homeassistant.setup] Setting up timer
2023-08-28 20:58:18.739 INFO (MainThread) [homeassistant.setup] Setting up counter
2023-08-28 20:58:18.763 INFO (MainThread) [homeassistant.setup] Setting up input_button
2023-08-28 20:58:18.770 INFO (MainThread) [homeassistant.setup] Setting up conversation
2023-08-28 20:58:18.773 INFO (MainThread) [homeassistant.setup] Setup of domain conversation took 0.0 seconds
2023-08-28 20:58:18.797 INFO (MainThread) [homeassistant.setup] Setting up sun
2023-08-28 20:58:18.798 INFO (MainThread) [homeassistant.setup] Setup of domain sun took 0.0 seconds
2023-08-28 20:58:18.817 INFO (MainThread) [homeassistant.setup] Setting up scene
2023-08-28 20:58:18.833 INFO (MainThread) [homeassistant.setup] Setting up tts
2023-08-28 20:58:18.842 INFO (MainThread) [homeassistant.setup] Setting up stt
2023-08-28 20:58:18.845 INFO (MainThread) [homeassistant.setup] Setup of domain stt took 0.0 seconds
2023-08-28 20:58:18.897 INFO (MainThread) [homeassistant.setup] Setting up schedule
2023-08-28 20:58:19.234 INFO (MainThread) [homeassistant.setup] Setting up history
2023-08-28 20:58:19.237 INFO (MainThread) [homeassistant.setup] Setup of domain history took 0.0 seconds
2023-08-28 20:58:19.245 INFO (MainThread) [homeassistant.setup] Setting up input_boolean
2023-08-28 20:58:19.254 INFO (MainThread) [homeassistant.setup] Setting up input_select
2023-08-28 20:58:19.269 INFO (MainThread) [homeassistant.setup] Setting up input_text
2023-08-28 20:58:19.282 INFO (MainThread) [homeassistant.setup] Setting up input_datetime
2023-08-28 20:58:19.288 INFO (MainThread) [homeassistant.setup] Setting up blueprint
2023-08-28 20:58:19.289 INFO (MainThread) [homeassistant.setup] Setup of domain blueprint took 0.0 seconds
2023-08-28 20:58:19.408 INFO (MainThread) [homeassistant.setup] Setting up homeassistant_alerts
2023-08-28 20:58:19.410 INFO (MainThread) [homeassistant.setup] Setup of domain homeassistant_alerts took 0.0 seconds
2023-08-28 20:58:19.523 INFO (MainThread) [homeassistant.setup] Setting up tag
2023-08-28 20:58:19.953 INFO (MainThread) [homeassistant.setup] Setting up radio_browser
2023-08-28 20:58:19.954 INFO (MainThread) [homeassistant.setup] Setup of domain radio_browser took 0.0 seconds
2023-08-28 20:58:19.962 INFO (MainThread) [homeassistant.setup] Setup of domain hardware took 1.3 seconds
2023-08-28 20:58:20.106 INFO (MainThread) [homeassistant.setup] Setting up map
2023-08-28 20:58:20.108 INFO (MainThread) [homeassistant.setup] Setup of domain map took 0.0 seconds
2023-08-28 20:58:20.114 INFO (MainThread) [homeassistant.setup] Setting up system_health
2023-08-28 20:58:20.248 INFO (MainThread) [homeassistant.setup] Setting up application_credentials
2023-08-28 20:58:20.355 INFO (MainThread) [homeassistant.setup] Setting up my
2023-08-28 20:58:20.356 INFO (MainThread) [homeassistant.setup] Setup of domain my took 0.0 seconds
2023-08-28 20:58:20.366 INFO (MainThread) [homeassistant.setup] Setting up media_source
2023-08-28 20:58:20.389 INFO (MainThread) [homeassistant.setup] Setting up energy
2023-08-28 20:58:20.391 INFO (MainThread) [homeassistant.setup] Setup of domain energy took 0.0 seconds
2023-08-28 20:58:20.471 INFO (MainThread) [homeassistant.setup] Setting up logbook
2023-08-28 20:58:20.482 INFO (MainThread) [homeassistant.setup] Setting up script
2023-08-28 20:58:20.571 INFO (MainThread) [homeassistant.setup] Setup of domain timer took 1.9 seconds
2023-08-28 20:58:20.583 INFO (MainThread) [homeassistant.setup] Setup of domain counter took 1.8 seconds
2023-08-28 20:58:20.669 INFO (MainThread) [homeassistant.setup] Setting up automation
2023-08-28 20:58:20.772 INFO (MainThread) [homeassistant.setup] Setup of domain tag took 1.2 seconds
2023-08-28 20:58:20.814 INFO (MainThread) [homeassistant.setup] Setting up met
2023-08-28 20:58:20.814 INFO (MainThread) [homeassistant.setup] Setup of domain met took 0.0 seconds
2023-08-28 20:58:20.879 INFO (MainThread) [homeassistant.setup] Setup of domain system_health took 0.8 seconds
2023-08-28 20:58:20.908 INFO (MainThread) [homeassistant.setup] Setup of domain media_source took 0.5 seconds
2023-08-28 20:58:20.923 INFO (MainThread) [homeassistant.setup] Setup of domain logbook took 0.5 seconds
2023-08-28 20:58:20.933 INFO (MainThread) [homeassistant.setup] Setup of domain tts took 2.1 seconds
2023-08-28 20:58:20.934 INFO (MainThread) [homeassistant.setup] Setup of domain zone took 2.3 seconds
2023-08-28 20:58:20.948 INFO (MainThread) [homeassistant.setup] Setup of domain input_number took 2.3 seconds
2023-08-28 20:58:20.993 INFO (MainThread) [homeassistant.setup] Setup of domain input_button took 2.2 seconds
2023-08-28 20:58:21.011 INFO (MainThread) [homeassistant.setup] Setup of domain application_credentials took 0.8 seconds
2023-08-28 20:58:21.026 INFO (MainThread) [homeassistant.setup] Setup of domain schedule took 2.1 seconds
2023-08-28 20:58:21.081 INFO (MainThread) [homeassistant.setup] Setup of domain script took 0.6 seconds
2023-08-28 20:58:21.146 INFO (MainThread) [homeassistant.setup] Setup of domain automation took 0.5 seconds
2023-08-28 20:58:21.171 INFO (MainThread) [homeassistant.setup] Setup of domain input_boolean took 1.9 seconds
2023-08-28 20:58:21.197 INFO (MainThread) [homeassistant.setup] Setup of domain input_select took 1.9 seconds
2023-08-28 20:58:21.221 INFO (MainThread) [homeassistant.setup] Setup of domain input_text took 2.0 seconds
2023-08-28 20:58:21.234 INFO (MainThread) [homeassistant.setup] Setup of domain input_datetime took 2.0 seconds
2023-08-28 20:58:21.241 INFO (MainThread) [homeassistant.setup] Setting up assist_pipeline
2023-08-28 20:58:21.250 INFO (MainThread) [homeassistant.setup] Setting up stream
2023-08-28 20:58:21.692 INFO (MainThread) [homeassistant.setup] Setup of domain stream took 0.4 seconds
2023-08-28 20:58:21.702 INFO (MainThread) [homeassistant.setup] Setting up google_translate
2023-08-28 20:58:21.708 INFO (MainThread) [homeassistant.setup] Setup of domain google_translate took 0.0 seconds
2023-08-28 20:58:21.855 INFO (MainThread) [homeassistant.setup] Setup of domain assist_pipeline took 0.6 seconds
2023-08-28 20:58:21.860 INFO (SyncWorker_1) [homeassistant.loader] Loaded notify from homeassistant.components.notify
2023-08-28 20:58:21.872 INFO (MainThread) [homeassistant.components.scene] Setting up scene.homeassistant
2023-08-28 20:58:21.893 INFO (SyncWorker_0) [homeassistant.loader] Loaded plex from homeassistant.components.plex
2023-08-28 20:58:21.939 INFO (MainThread) [homeassistant.setup] Setup of domain scene took 3.1 seconds
2023-08-28 20:58:22.260 INFO (MainThread) [homeassistant.setup] Setting up mobile_app
2023-08-28 20:58:22.324 INFO (MainThread) [homeassistant.setup] Setup of domain mobile_app took 0.1 seconds
2023-08-28 20:58:22.565 INFO (MainThread) [homeassistant.setup] Setting up cast
2023-08-28 20:58:22.569 INFO (MainThread) [homeassistant.setup] Setup of domain cast took 0.0 seconds
2023-08-28 20:58:22.586 INFO (MainThread) [homeassistant.setup] Setting up notify
2023-08-28 20:58:22.590 INFO (MainThread) [homeassistant.setup] Setup of domain notify took 0.0 seconds
2023-08-28 20:58:23.139 INFO (MainThread) [homeassistant.setup] Setting up media_player
2023-08-28 20:58:23.202 INFO (MainThread) [homeassistant.setup] Setup of domain media_player took 0.1 seconds
2023-08-28 20:58:23.223 INFO (MainThread) [homeassistant.components.notify] Setting up notify.mobile_app
2023-08-28 20:58:23.244 INFO (SyncWorker_2) [homeassistant.loader] Loaded weather from homeassistant.components.weather
2023-08-28 20:58:23.331 INFO (MainThread) [homeassistant.setup] Setting up weather
2023-08-28 20:58:23.332 INFO (MainThread) [homeassistant.setup] Setup of domain weather took 0.0 seconds
2023-08-28 20:58:23.355 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.energy
2023-08-28 20:58:23.357 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.sun
2023-08-28 20:58:23.546 INFO (MainThread) [homeassistant.setup] Setting up default_config
2023-08-28 20:58:23.547 INFO (MainThread) [homeassistant.setup] Setup of domain default_config took 0.0 seconds
2023-08-28 20:58:23.567 INFO (MainThread) [homeassistant.components.tts] Setting up tts.google_translate
2023-08-28 20:58:23.595 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.cast
2023-08-28 20:58:23.596 INFO (MainThread) [homeassistant.components.weather] Setting up weather.met
2023-08-28 20:58:23.785 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 55.50s
2023-08-28 20:58:23.788 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2023-08-28 20:58:23.982 INFO (SyncWorker_3) [homeassistant.loader] Loaded spotify from homeassistant.components.spotify
2023-08-28 20:58:24.004 INFO (SyncWorker_0) [homeassistant.loader] Loaded androidtv_remote from homeassistant.components.androidtv_remote
2023-08-28 20:58:24.099 INFO (zeroconf-ServiceBrowser-_googlecast._tcp-100) [homeassistant.components.cast.helpers] Fetched cast details for unknown model 'MIBOX4' manufacturer: 'Xiaomi', type: 'cast'. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+cast%22
2023-08-28 20:58:25.751 INFO (SyncWorker_3) [homeassistant.loader] Loaded shelly from homeassistant.components.shelly
2023-08-28 20:58:27.045 INFO (SyncWorker_0) [homeassistant.loader] Loaded brother from homeassistant.components.brother
2023-08-28 20:58:34.079 INFO (MainThread) [homeassistant.components.shelly] Starting CoAP context with UDP port 5683
2023-08-28 20:58:34.418 INFO (SyncWorker_0) [homeassistant.loader] Loaded ipp from homeassistant.components.ipp
2023-08-28 20:58:34.787 INFO (SyncWorker_2) [homeassistant.loader] Loaded dlna_dms from homeassistant.components.dlna_dms
2023-08-28 20:58:34.914 INFO (SyncWorker_1) [homeassistant.loader] Loaded harmony from homeassistant.components.harmony
2023-08-28 20:58:34.923 INFO (SyncWorker_2) [homeassistant.loader] Loaded switch from homeassistant.components.switch
2023-08-28 20:58:34.925 INFO (SyncWorker_0) [homeassistant.loader] Loaded remote from homeassistant.components.remote
2023-08-28 20:58:34.938 INFO (MainThread) [homeassistant.setup] Setting up remote
2023-08-28 20:58:34.958 INFO (MainThread) [homeassistant.setup] Setup of domain remote took 0.0 seconds
2023-08-28 20:58:34.973 INFO (SyncWorker_1) [homeassistant.loader] Loaded switch_as_x from homeassistant.components.switch_as_x
2023-08-28 20:58:35.032 INFO (MainThread) [homeassistant.setup] Setting up switch
2023-08-28 20:58:35.044 INFO (MainThread) [homeassistant.setup] Setup of domain switch took 0.0 seconds
2023-08-28 20:59:21.468 DEBUG (MainThread) [aiogithubapi] The authorization request is still pending.
2023-08-28 20:59:26.677 DEBUG (MainThread) [aiogithubapi] Too many requests have been made in the same timeframe.
2023-08-28 20:59:29.834 DEBUG (MainThread) [aiogithubapi] Too many requests have been made in the same timeframe.
2023-08-28 20:59:40.038 DEBUG (MainThread) [aiogithubapi] Too many requests have been made in the same timeframe.
2023-08-28 20:59:50.256 DEBUG (MainThread) [aiogithubapi] Too many requests have been made in the same timeframe.
2023-08-28 20:59:53.401 DEBUG (MainThread) [aiogithubapi] Too many requests have been made in the same timeframe.
2023-08-28 21:00:03.633 DEBUG (MainThread) [aiogithubapi] Too many requests have been made in the same timeframe.
2023-08-28 21:00:13.830 DEBUG (MainThread) [aiogithubapi] Too many requests have been made in the same timeframe.
2023-08-28 21:00:16.992 DEBUG (MainThread) [aiogithubapi] Too many requests have been made in the same timeframe.
```

**Comment by ludeeus** [comment] 2023-08-28 19:03
Duplicate of #3218

**Closed by ludeeus** 2023-08-28 19:03 UTC
Labels: invalid
