### ISSUE TITLE
'hacs' accesses hass.components.frontend - This is deprecated 

### ISSUE THREAD

**Issue by berkavil** [hacs/integration#3542] opened 2024-03-07 10:56 UTC
### Web browser

chrome latest version 

### Web browser version

64 bit Window10

### System Health details

Hallo, after the last HomeAssistant core update this week - the warning msg below started to appear:
...
Logger: homeassistant.helpers.frame
Zdroj: helpers/frame.py:156
První výskyt: 11:06:59 (1 výskyty)
Naposledy logováno: 11:06:59

Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
...

not sure if it was mentioned somewhere else, but I didnt find it here anywhere so I hope this is not a duplicated issue entry.
thx. for checking it up.

Willy

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Warning from HA system logger

### Reproduction steps

Installed the latest core update this week and it started to appear
Warning msg from HA system logger with the link to send issue notice to this issue forum.

### Screenshots

Logger: homeassistant.helpers.frame
Zdroj: helpers/frame.py:156
První výskyt: 11:06:59 (1 výskyty)
Naposledy logováno: 11:06:59

Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues

### Javascript logs from your browser console

```text
sorry I cant create this
```

**Comment by tjorim** [comment] 2024-03-07 12:03
Duplicate of https://github.com/hacs/integration/issues/3534.

**Comment by codyc1515** [comment] 2024-03-08 02:47
Another duplicate #3543

**Comment by pbillerot** [comment] 2024-03-10 11:02
idem for me
`2024-03-10 11:21:37.553 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
`

**Closed** 2024-03-14 17:24 UTC
Labels: issue:frontend
