### ISSUE TITLE
Unable to add custom integration repository into HACS 0.24.5

### ISSUE THREAD

**Issue by dbruynb** [hacs/integration#1179] opened 2020-05-21 12:46 UTC
## Installation details

Description                            | Value
------------------------------- | ------------------------------
HACS version                         |0.24.5
Home Assistant version         |0.110.0
Installation method for HA    |Virtual Machine on Windows 10
Web browser                         |Chrome and Edge
Web browser version            | Chrome 81.0.4044.138 (Official Build) (64-bit) and Edge Version 81.0.416.77

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.

## Describe the issue

The same issue as [https://github.com/hacs/integration/issues/1143](url) but get a different error massage

"I am trying to add the AlexxIT/SonoffLAN custom repository into HACS in order to configure my Sonoff devices as described in https://github.com/AlexxIT/SonoffLAN but after clicking the save disk icon; nothing happens, just an error log entry in docker."

### Steps to reproduce

- Fresh install of latest home-assistant for virtual machine.
- Install HACS and wait until it finishes loading repositories.
- After that go to HACS >> Settings and add AlexxIT/SonoffLAN as Integration and click save.
- Nothing happens. Just the following line is logged.

### Screenshots

![image](https://user-images.githubusercontent.com/11042487/82560366-a0d2ca00-9b71-11ea-8c0c-555a1be12bd3.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text


`
2020-05-21 14:23:27 ERROR (MainThread) [frontend.js.latest.202005190] http://192.168.7.78:8123/hacsfiles/frontend-20200426112021.js:2437:1387 Uncaught TypeError: Cannot read property 'selectedItem' of undefined
`
```

</details>

**Comment by ludeeus** [comment] 2020-05-21 12:49
duplicate of https://github.com/hacs/integration/issues/1143

**Closed by ludeeus** 2020-05-21 12:49 UTC
Labels: issue:frontend
