### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes'

### ISSUE THREAD

**Issue by Gotanius** [hacs/integration#2243] opened 2021-10-16 17:49 UTC
### Web browser

Vivaldi / Edge Chromium / iOS app

### Web browser version

4.3.2439.44

## System Health

version | core-2021.10.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.70
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4986
Installed Version | 1.15.2
Stage | running
Available Repositories | 495
Installed Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | October 20, 2021, 2:00 AM
relayer_connected | true
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | false
remote_server | eu-west-2-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.5
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.0
docker_version | 20.10.7
disk_total | 30.8 GB
disk_used | 17.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), AirSonos (3.1.1), WireGuard (0.5.1), MariaDB (2.4.0), File editor (5.3.3), AirCast (3.1.1), Vaultwarden (Bitwarden) (0.13.0), motionEye (0.15.1), Portainer (2.0.0), Terminal & SSH (9.2.1), Duck DNS (1.14.0), Grocy (0.15.0), AdGuard Home (4.1.9), Tautulli (2.3.0), SSH & Web Terminal (9.0.1), motionEye (f4d4eef), Mosquitto broker (6.0.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 4
-- | --
resources | 1
views | 17
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

After a fresh install of hacs when I try to install any card/button/whatevs.
The installation 'popup' won't leave and keeps giving a spinning wheel on the install button after clicking it. 

Afterwards the front-end is broken and only shows an empty page or the addons and info button. 

HACS logs:
2021-10-16 19:39:15 DEBUG (MainThread) [queueman.manager] Checking out tasks to execute
2021-10-16 19:39:15 DEBUG (MainThread) [queueman.manager] Starting queue execution for 1 tasks
2021-10-16 19:39:15 DEBUG (MainThread) [custom_components.hacs] Downloading button-card.js
2021-10-16 19:39:15 DEBUG (MainThread) [custom_components.hacs] Downloading https://github.com/custom-cards/button-card/releases/download/v3.4.2/button-card.js
2021-10-16 19:39:16 DEBUG (MainThread) [custom_components.hacs] Saving /config/www/community/button-card/button-card.js
2021-10-16 19:39:16 INFO (MainThread) [custom_components.hacs] Download of button-card.js completed
2021-10-16 19:39:16 DEBUG (MainThread) [queueman.manager] Queue execution finished for 1 tasks finished in 1.02 seconds
2021-10-16 19:39:16 INFO (MainThread) [custom_components.hacs] Installation steps completed
2021-10-16 19:39:16 INFO (MainThread) [custom_components.hacs] Running post installation steps
2021-10-16 19:39:16 INFO (MainThread) [custom_components.hacs] Post installation steps completed
2021-10-16 19:39:16 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-10-16 19:39:16 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-10-16 19:47:24 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue

### Reproduction steps

1. Fresh install
2. Try to install a theme/card/whatevs
3. Refresh Hacs page
...

### Screenshots

![Screenshot from 2021-10-16 19-48-09@2x](https://user-images.githubusercontent.com/20792988/137597241-18e8fce6-2233-442c-8dff-452bc91ee242.png)

### Javascript logs from your browser console

```text
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at c.997269e7.js:1
    at Array.find (<anonymous>)
    at i (c.997269e7.js:1)
    at async HTMLElement.value (c.4d32e8cc.js:87)
2main-60575625.js:1217 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at main-60575625.js:1217
    at Array.some (<anonymous>)
    at Object._s [as addedToLovelace] (main-60575625.js:1217)
    at c.100894b4.js:676
    at Array.map (<anonymous>)
    at HTMLElement.value (c.100894b4.js:668)
    at HTMLElement.value (c.100894b4.js:657)
    at HTMLElement.update (main-60575625.js:1)
    at HTMLElement.performUpdate (main-60575625.js:1)
    at HTMLElement._$EC (main-60575625.js:1)
```

*edit: I saw something in the logs about a websocket error, but I can't find it anymore. Could it have something to do with lovelace storage mode and multiple dasboards?

**Comment by ludeeus** [comment] 2021-10-17 07:42
Duplicate of https://github.com/hacs/integration/issues/2234

**Closed by ludeeus** 2021-10-17 07:42 UTC
Labels: issue:frontend
