### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by HarryMcGill2022** [hacs/integration#3581] opened 2024-04-07 22:41 UTC
### Web browser

Home assistant app

### Web browser version

No idea

## System Information

version | core-2024.4.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4955
Installed Version | 1.34.0
Stage | running
Available Repositories | 1400
Downloaded Repositories | 6
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 30 April 2024 at 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-19.ui.nabu.casa
certificate_status | ready
instance_id | 3f31934eae054e14917830a09f10ef77
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.03.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 28.5 GB
disk_used | 6.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Terminal & SSH (9.10.0), Home Assistant Google Drive Backup (0.112.1), Mosquitto broker (6.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 1
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 3 April 2024 at 23:44
-- | --
current_recorder_run | 7 April 2024 at 23:11
estimated_db_size | 12.22 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Issue when looking through logs at another Issue I found this also on the other hand themes back grounds aren’t showing up. Not sure if that’s anything to do with this.

### Reproduction steps

I’m not sure as found in logs and background not showing up.

### Screenshots

![IMG_0322](https://github.com/hacs/integration/assets/95884758/1f7d88e0-6859-4abc-be15-b18730605365)
![IMG_0323](https://github.com/hacs/integration/assets/95884758/b85533bf-4f50-41ab-820e-b76c018d634a)
![IMG_0325](https://github.com/hacs/integration/assets/95884758/23a6897b-43cb-4118-8948-cac39ab78942)
![IMG_0324](https://github.com/hacs/integration/assets/95884758/80e27230-66d2-4a49-9a7b-710a001a2c07)

### Javascript logs from your browser console

```text
.
```

### Diagnostics dump

[config_entry-hacs-064854fb564274e728a47480ff1890bd.json](https://github.com/hacs/integration/files/14899252/config_entry-hacs-064854fb564274e728a47480ff1890bd.json)

**Comment by elchininet** [comment] 2024-04-07 23:55
Duplicate of https://github.com/hacs/integration/issues/3557 and https://github.com/hacs/integration/issues/3534

**Closed** 2024-04-09 15:57 UTC
Labels: issue:frontend
