### ISSUE TITLE
Repository exists, unable to find or add manually

### ISSUE THREAD

**Issue by Tosko4** [hacs/integration#2082] opened 2021-06-10 10:41 UTC
### Web browser

Safari

### Web browser version

Version 14.1.1 (16611.2.7.1.4)

## System Health

version | core-2021.6.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4909
Installed Version | 1.12.4
Stage | running
Available Repositories | 823
Installed Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | June 30, 2021, 2:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.0.rc1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.05.4
docker_version | 20.10.6
disk_total | 228.5 GB
disk_used | 5.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.1), Samba share (9.5.0), Visual Studio Code (3.4.1), SSH & Web Terminal (8.2.3), Ring Livestream (1.35), RPi Temp Monitor (0.4)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 15
views | 2
mode | yaml

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

I am trying to add this repository to my HA installation: https://github.com/r-renato/ha-card-weather-conditions
When I search for it in HACS -> Integration -> Explorer & Add Repository ->

I Searched for the following terms:
- HA (Lovelace) Card Weather Conditions
- Weather
- Condition

Example:
<img width="637" alt="Screenshot 2021-06-10 at 12 26 10" src="https://user-images.githubusercontent.com/1294707/121509617-1f9ddd80-c9e7-11eb-8549-4a971d2141f6.png">

Nothing shows me this repository. So I figured, I might have to add a custom repository. So when I do that;
- URL: https://github.com/r-renato/ha-card-weather-conditions
- Type: integration

HACS shows me the error/warning: Repository 'r-renato/ha-card-weather-conditions' exists in the store.

### Reproduction steps

1. Click on HACS (duh)
2. Go to Integration
3. Click on "Explorer & Add Repository" and search for the terms mentioned above

### Screenshots

<img width="637" alt="Screenshot 2021-06-10 at 12 26 10" src="https://user-images.githubusercontent.com/1294707/121511338-ce8ee900-c9e8-11eb-88d1-af4e64cec1ac.png">

### Javascript logs from your browser console

```text
[Info]   ALARMO-CARD   (alarmo-card.js, line 669)
  Version: v1.6.0 
[Info]   BAR-CARD  (bar-card.js, line 4855)
  Version 3.1.7    
[Info]   BUTTON-CARD   (button-card.js, line 425)
 Version 3.4.2 
[Info] ≡ kiosk-mode            ⋮  (kiosk-mode.js, line 49)
version 1.6.5            
[Info]   LIGHT-ENTITY-CARD    (light-entity-card.js, line 9160)
  Version 4.2.2       
[Info] CARD-MOD 3.0.12 IS INSTALLED – "" (card-mod.js, line 5)
[Info] HUI-ELEMENT 1.0.1 IS INSTALLED – "" (hui-element.js, line 1)
[Info] LAYOUT-CARD 2.2.3 IS INSTALLED – "" (layout-card.js, line 210)
[Info] SLIDER-ENTITY-ROW 17.0.1 IS INSTALLED – "" (slider-entity-row.js, line 59)
[Info]  MINI-GRAPH-CARD  0.10.0  (mini-graph-card-bundle.js, line 1)
[Info]    SWIPE-CARD   (swipe-card.js, line 21)
 Version 4.0.0 
[Info]   CALENDAR-CARD    (calendar-card.js, line 1065)
  Version 3.109.0 
[Info] BROWSER_MOD 1.3.1 IS INSTALLED (browser_mod.js, line 142)
    DeviceID: mydeviceID
```

**Comment by ludeeus** [comment] 2021-06-10 10:44
duplicate of #2081

**Closed by ludeeus** 2021-06-10 10:44 UTC
Labels: issue:frontend

**Comment by Tosko4** [comment] 2021-06-10 10:45
Wut? You told me to fill in the frontend issue. So I did, see itts issue:frontend and now its a duplicate??
@ludeeus What's wrong?

**Comment by ludeeus** [comment] 2021-06-10 10:47
No I did not...
I told you to go to the frontend **tab**
it is **not** and _integration_

**Comment by Tosko4** [comment] 2021-06-10 10:49
Gotcha, sorry about that. Few more words in your previous closure would have avoided this. Nonetheless, thanks!
