### ISSUE TITLE
Feature Request: Show some form of release notes in the update modal

### ISSUE THREAD

**Issue by vanstinator** [hacs/integration#1263] opened 2020-05-26 12:46 UTC
## Category

- [ ] Backend/Integration
- [x] Frontend
- [ ] Documentation
- [ ] Bot
- [ ] Other

## Checklist

- [x] This Feature Request only contain 1 request (if you have multiple open multiple feature requests).

## The idea

As both an integration maintainer and a user of HACS I would find it helpful if release notes were featured more prominently inside HACS. The current upgrade flow contains a modal with a bit of metadata and a few actions. But it requires to user to click `changelog` to see what changed. I'd love to see the ability to put notes right inside the upgrade dialog.
 
## Implementation

I have 2 ideas. I'll start with the simpler approach as it's the easiest:

1. I'm not super familiar with GitHub's API. But I think we can probably just pull the raw markdown from the releases page and render it right in the modal. Similarly to how README.md and INFO.md are already supported today for the information page. Showing the most recent release is slightly deceiving if a user is behind. But maintainers could include a rollup of point release notes for small fixes. And users still have the `changelog` button to go view the releases page.

1. Alternatively we could use the templating abilities of the info.md parser to include a patch notes section in that file that only appears inside the upgrade modal. If the maintainer used it correctly a user would have access to complete patch notes for _all_ versions that they've currently missed. This is probably more complicated to implement, more complicated for maintainers, and potentially a lot of extra UI noise.

## Alternatives

INFO.md support is obviously implemented and quite rich. But it still requires user interaction inside HACS to bring it up during the update flow.

## Additional context

I recently started maintaining a HACS module. And the 1.0 release upgrade modal feels like the perfect place for such a feature

**Comment by ludeeus** [comment] 2020-05-26 12:49
Thanks for this, but this is a duplicate of https://github.com/hacs/integration/issues/1248
If you have views that are not covered in the description/comments please add those there 👍

**Closed by ludeeus** 2020-05-26 12:49 UTC
Labels: Feature Request

**Comment by vanstinator** [comment] 2020-05-26 12:51
Thanks. Apparently I can't search.
